const fs = require('fs');
const path = require('path');

const root = process.cwd();
const workflowName = 'Lunch-Recommendation-Alert';
const workflowDir = path.join(root, 'workflows', workflowName);
const workflowPath = path.join(workflowDir, `${workflowName}_api.json`);
const workflowEnvPath = path.join(workflowDir, '.env');

function loadSimpleEnv(filePath) {
  const values = {};
  if (!fs.existsSync(filePath)) return values;
  const text = fs.readFileSync(filePath, 'utf8');
  for (const line of text.split(/\r?\n/)) {
    if (!line || /^\s*#/.test(line)) continue;
    const match = line.match(/^(.*?)=(.*)$/);
    if (match) values[match[1]] = match[2];
  }
  return values;
}

const workflowEnv = loadSimpleEnv(workflowEnvPath);
const EXPORT_WITH_SECRETS = process.env.EXPORT_WITH_SECRETS === '1';
const REDACTED_TEAMS_WEBHOOK = 'https://redacted.invalid/powerautomate/lunch-recommendation-webhook';
const REDACTED_GEMINI_API_KEY = '__REDACTED_GEMINI_API_KEY__';

const TEAMS_WEBHOOK =
  process.env.TS_LUNCH_TEAMS_WEBHOOK || REDACTED_TEAMS_WEBHOOK;

const MORE_RECOMMEND_WEBHOOK_PATH = 'lunch-menu-recommend-more';
const MORE_RECOMMEND_WEBHOOK_URL = `https://n8n.vmsmozart-test.com:8443/webhook/${MORE_RECOMMEND_WEBHOOK_PATH}`;
const GEMINI_MODEL = 'gemini-3.5-flash';
const GEMINI_API_KEY = EXPORT_WITH_SECRETS
  ? (workflowEnv.GEMINI_TS_LUNCH_API_KEY || '')
  : REDACTED_GEMINI_API_KEY;
const KAKAO_CREDENTIAL = {
  id: 'vnfOZARBTxbJ1sJU',
  name: 'kakao-local-lunch-recommendation',
};

const CONFIG = {
  locationLabel: '분당수지유타워',
  locationQuery: '경기도 용인시 수지구 신수로 767',
  nearbySearchQuery: '분당수지유타워 맛집',
  walkRadiusMeters: 1200,
  driveRadiusMeters: 6500,
  driveSearchOffsetMeters: 1800,
  driveSearchRadiusMeters: 2500,
  walkCandidateLimit: 14,
  driveCandidateLimit: 18,
  budgetPerPersonKrw: 10000,
  interviewBudgetPerPersonKrw: 30000,
  interviewParticipantCount: 4,
};

function uuid(seed) {
  const text = `${workflowName}:${seed}`;
  let hash = 0;
  for (let i = 0; i < text.length; i += 1) {
    hash = ((hash << 5) - hash + text.charCodeAt(i)) | 0;
  }
  const hex = (n) => (Math.abs(n).toString(16).padStart(8, '0')).slice(0, 8);
  return `${hex(hash + 1)}-${hex(hash + 2).slice(0, 4)}-${hex(hash + 3).slice(0, 4)}-${hex(hash + 4).slice(0, 4)}-${hex(hash + 5)}${hex(hash + 6)}`;
}

function toUnicodeEscape(ch) {
  return `\\u${ch.charCodeAt(0).toString(16).padStart(4, '0')}`;
}

function asciiJson(value) {
  return JSON.stringify(value).replace(/[^\x20-\x7E]/g, toUnicodeEscape);
}

function lines(...items) {
  return items.join('\n');
}

if (EXPORT_WITH_SECRETS && !GEMINI_API_KEY) {
  throw new Error(`Missing GEMINI_TS_LUNCH_API_KEY in ${workflowEnvPath}`);
}

const weekdayBaselineCode = lines(
  "const source = $input.first()?.json ?? {};",
  "const query = source.query && typeof source.query === 'object' ? source.query : {};",
  "const now = new Date();",
  "const parts = new Intl.DateTimeFormat('en-CA', {",
  "  timeZone: 'Asia/Seoul',",
  "  year: 'numeric',",
  "  month: '2-digit',",
  "  day: '2-digit',",
  "  weekday: 'long',",
  "}).formatToParts(now);",
  "const pick = (type) => parts.find((part) => part.type === type)?.value || '';",
  "const year = pick('year');",
  "const month = pick('month');",
  "const day = pick('day');",
  "const weekdayEn = pick('weekday');",
  'const weekdayMap = {',
  "  Monday: '\\uC6D4\\uC694\\uC77C',",
  "  Tuesday: '\\uD654\\uC694\\uC77C',",
  "  Wednesday: '\\uC218\\uC694\\uC77C',",
  "  Thursday: '\\uBAA9\\uC694\\uC77C',",
  "  Friday: '\\uAE08\\uC694\\uC77C',",
  "  Saturday: '\\uD1A0\\uC694\\uC77C',",
  "  Sunday: '\\uC77C\\uC694\\uC77C',",
  '};',
  "const isWeekend = weekdayEn === 'Saturday' || weekdayEn === 'Sunday';",
  "const nextWeek = new Date(now.getTime() + (7 * 24 * 60 * 60 * 1000));",
  'const isLastWeekOfMonth = now.getMonth() !== nextWeek.getMonth();',
  `const interviewBudgetPerPersonKrw = ${CONFIG.interviewBudgetPerPersonKrw};`,
  `const interviewParticipantCount = ${CONFIG.interviewParticipantCount};`,
  "const excludeRaw = String(query.exclude || source.exclude || '').trim();",
  "const excludedPlaceNames = excludeRaw ? excludeRaw.split('|').map((value) => String(value || '').trim()).filter(Boolean) : [];",
  "const requestSource = excludedPlaceNames.length > 0 || String(query.source || source.source || '').toLowerCase() === 'teams' ? 'teams-reroll' : 'scheduled';",
  'return [{',
  '  json: {',
  '    ...source,',
  '    query,',
  '    todayDate: `${year}-${month}-${day}`,',
  '    todayInt: `${year}${month}${day}`,',
  '    todayMMDD: `${month}${day}`,',
  '    WeekdayName: weekdayMap[weekdayEn] || weekdayEn,',
  '    IsWeekend: isWeekend,',
  '    DefaultIsHoliday: isWeekend,',
  "    DefaultHolidayName: isWeekend ? '\\uC8FC\\uB9D0' : '\\uD3C9\\uC77C',",
  `    locationLabel: ${asciiJson(CONFIG.locationLabel)},`,
  `    locationQuery: ${asciiJson(CONFIG.locationQuery)},`,
  `    nearbySearchQuery: ${asciiJson(CONFIG.nearbySearchQuery)},`,
  `    budgetPerPersonKrw: ${CONFIG.budgetPerPersonKrw},`,
  '    isLastWeekOfMonth,',
  '    interviewBudgetPerPersonKrw,',
  '    interviewParticipantCount,',
  '    interviewBudgetTotalKrw: interviewBudgetPerPersonKrw * interviewParticipantCount,',
  `    walkRadiusMeters: ${CONFIG.walkRadiusMeters},`,
  `    driveRadiusMeters: ${CONFIG.driveRadiusMeters},`,
  `    driveSearchOffsetMeters: ${CONFIG.driveSearchOffsetMeters},`,
  `    driveSearchRadiusMeters: ${CONFIG.driveSearchRadiusMeters},`,
  `    walkCandidateLimit: ${CONFIG.walkCandidateLimit},`,
  `    driveCandidateLimit: ${CONFIG.driveCandidateLimit},`,
  '    requestSource,',
  '    excludedPlaceNames,',
  '  }',
  '}];'
);

const determineHolidayCode = lines(
  "const baseline = $('Weekday Baseline').first()?.json ?? {};",
  "const dbPayload = $('Holiday DB Fallback').first()?.json ?? {};",
  "const dbFound = !dbPayload.error && [true, 1, '1', 'true'].includes(dbPayload.found_in_db);",
  '',
  'let isHoliday = !!baseline.DefaultIsHoliday;',
  "let holidayName = baseline.DefaultHolidayName || (isHoliday ? '\\uC8FC\\uB9D0' : '\\uD3C9\\uC77C');",
  "let holidayLookupSource = isHoliday ? 'default-weekend' : 'default-weekday';",
  '',
  'if (dbFound) {',
  '  isHoliday = true;',
  "  holidayName = String(dbPayload.holiday_name || '\\uACF5\\uD734\\uC77C');",
  "  holidayLookupSource = dbPayload.source_type ? `db:${dbPayload.source_type}` : 'db';",
  '}',
  '',
  'return [{',
  '  json: {',
  '    ...baseline,',
  '    check_date: baseline.todayInt,',
  '    today_date: baseline.todayDate,',
  '    is_holiday: isHoliday,',
  '    holiday_name: holidayName,',
  '    is_weekend: !!baseline.IsWeekend,',
  '    weekday_name: baseline.WeekdayName,',
  '    holiday_lookup_source: holidayLookupSource,',
  "    db_error: dbPayload.error || '',",
  '  }',
  '}];'
);

const buildSearchCenterCode = lines(
  "const source = $('Weekday Baseline').first()?.json ?? {};",
  'const payload = $input.first()?.json ?? {};',
  'const docs = Array.isArray(payload.documents) ? payload.documents : [];',
  'const first = docs[0] || null;',
  'const locationError = first ? "" : String(payload.error?.message || payload.message || payload.error || "Failed to resolve lunch recommendation center.");',
  'const centerX = first ? String(first.x || "") : "";',
  'const centerY = first ? String(first.y || "") : "";',
  'const centerXNumber = Number(centerX || 0);',
  'const centerYNumber = Number(centerY || 0);',
  'const driveSearchOffsetMeters = Number(source.driveSearchOffsetMeters || 1800);',
  'const driveSearchRadiusMeters = Number(source.driveSearchRadiusMeters || 2500);',
  'const latOffset = driveSearchOffsetMeters / 111320;',
  'const lonOffset = driveSearchOffsetMeters / (111320 * Math.max(0.2, Math.cos((centerYNumber * Math.PI) / 180)));',
  'const driveSearchPoints = first ? {',
  '  east: { x: String(centerXNumber + lonOffset), y: String(centerYNumber), label: "east" },',
  '  west: { x: String(centerXNumber - lonOffset), y: String(centerYNumber), label: "west" },',
  '  north: { x: String(centerXNumber), y: String(centerYNumber + latOffset), label: "north" },',
  '  south: { x: String(centerXNumber), y: String(centerYNumber - latOffset), label: "south" },',
  '} : {};',
  'const centerLocationText = first',
  '  ? String(first.road_address?.address_name || first.address?.address_name || first.address_name || "").trim()',
  '  : "";',
  'return [{',
  '  json: {',
  '    ...source,',
  '    centerX,',
  '    centerY,',
  '    centerDisplayName: source.locationLabel || "",',
  '    centerAddressQuery: source.locationQuery || "",',
  '    centerLocationText,',
  '    driveSearchOffsetMeters,',
  '    driveSearchRadiusMeters,',
  '    driveSearchPoints,',
  '    locationResolved: Boolean(first),',
  '    locationError,',
  '    nearbySearchLink: "https://map.kakao.com/link/search/" + encodeURIComponent(source.nearbySearchQuery || source.locationLabel || ""),',
  `    moreRecommendationsUrlBase: ${asciiJson(MORE_RECOMMEND_WEBHOOK_URL)},`,
  '  }',
  '}];'
);

const summarizeWeatherCode = lines(
  "const source = $('Build Search Center').first()?.json ?? {};",
  'const payload = $input.first()?.json ?? {};',
  'const daily = payload.daily && typeof payload.daily === "object" ? payload.daily : {};',
  'const current = payload.current && typeof payload.current === "object" ? payload.current : {};',
  'const weatherCodeMap = {',
  "  0: '\\uB9D1\\uC74C',",
  "  1: '\\uB300\\uCCB4\\uB85C \\uB9D1\\uC74C',",
  "  2: '\\uAD6C\\uB984 \\uC870\\uAE08',",
  "  3: '\\uD750\\uB9BC',",
  "  45: '\\uC548\\uAC1C',",
  "  48: '\\uC9D9\\uC740 \\uC548\\uAC1C',",
  "  51: '\\uC57D\\uD55C \\uC774\\uC2AC\\uBE44',",
  "  53: '\\uC774\\uC2AC\\uBE44',",
  "  55: '\\uAC15\\uD55C \\uC774\\uC2AC\\uBE44',",
  "  56: '\\uC57D\\uD55C \\uC5BC\\uC74C \\uC774\\uC2AC\\uBE44',",
  "  57: '\\uAC15\\uD55C \\uC5BC\\uC74C \\uC774\\uC2AC\\uBE44',",
  "  61: '\\uC57D\\uD55C \\uBE44',",
  "  63: '\\uBE44',",
  "  65: '\\uAC15\\uD55C \\uBE44',",
  "  66: '\\uC5BC\\uC74C \\uBE44',",
  "  67: '\\uAC15\\uD55C \\uC5BC\\uC74C \\uBE44',",
  "  71: '\\uC57D\\uD55C \\uB208',",
  "  73: '\\uB208',",
  "  75: '\\uAC15\\uD55C \\uB208',",
  "  77: '\\uC9C4\\uB208\\uAE68\\uBE44',",
  "  80: '\\uC18C\\uB098\\uAE30',",
  "  81: '\\uC18C\\uB098\\uAE30 \\uBE44',",
  "  82: '\\uAC15\\uD55C \\uC18C\\uB098\\uAE30',",
  "  85: '\\uC18C\\uB098\\uAE30 \\uB208',",
  "  86: '\\uAC15\\uD55C \\uC18C\\uB098\\uAE30 \\uB208',",
  "  95: '\\uB1CC\\uC6B0\\uB97C \\uB3D9\\uBC18\\uD55C \\uBE44',",
  "  96: '\\uC57D\\uD55C \\uC6B0\\uBC15',",
  "  99: '\\uAC15\\uD55C \\uC6B0\\uBC15',",
  '};',
  'function labelForCode(code) {',
  '  return weatherCodeMap[Number(code)] || "Unknown";',
  '}',
  'const dates = Array.isArray(daily.time) ? daily.time : [];',
  'const maxTemps = Array.isArray(daily.temperature_2m_max) ? daily.temperature_2m_max : [];',
  'const minTemps = Array.isArray(daily.temperature_2m_min) ? daily.temperature_2m_min : [];',
  'const rainProb = Array.isArray(daily.precipitation_probability_max) ? daily.precipitation_probability_max : [];',
  'const rainSum = Array.isArray(daily.precipitation_sum) ? daily.precipitation_sum : [];',
  'const codes = Array.isArray(daily.weather_code) ? daily.weather_code : [];',
  'const dailyForecast = dates.slice(0, 7).map((date, index) => ({',
  '  date: String(date || ""),',
  '  weatherCode: Number(codes[index] ?? -1),',
  '  weatherLabel: labelForCode(codes[index]),',
  '  temperatureMax: Number(maxTemps[index] ?? NaN),',
  '  temperatureMin: Number(minTemps[index] ?? NaN),',
  '  precipitationProbabilityMax: Number(rainProb[index] ?? 0),',
  '  precipitationSum: Number(rainSum[index] ?? 0),',
  '}));',
  'const today = dailyForecast[0] || null;',
  'const hotDays = dailyForecast.filter((day) => Number.isFinite(day.temperatureMax) && day.temperatureMax >= 28).length;',
  'const coldDays = dailyForecast.filter((day) => Number.isFinite(day.temperatureMin) && day.temperatureMin <= 5).length;',
  'const rainyDays = dailyForecast.filter((day) => day.precipitationProbabilityMax >= 50 || day.precipitationSum >= 3 || [51,53,55,61,63,65,66,67,80,81,82,95,96,99].includes(day.weatherCode)).length;',
  'const currentTemp = Number(current.temperature_2m ?? NaN);',
  'const currentFeelsLike = Number(current.apparent_temperature ?? NaN);',
  'const currentLabel = labelForCode(current.weather_code);',
  'const todaySummaryText = today',
  '  ? [',
  '      String(today.weatherLabel || currentLabel || "").trim(),',
  '      Number.isFinite(currentTemp) ? `현재 ${Math.round(currentTemp)}°C` : "",',
  '      Number.isFinite(currentFeelsLike) ? `체감 ${Math.round(currentFeelsLike)}°C` : "",',
  '      Number.isFinite(today.temperatureMax) && Number.isFinite(today.temperatureMin) ? `최고 ${Math.round(today.temperatureMax)}°C / 최저 ${Math.round(today.temperatureMin)}°C` : "",',
  '      today.precipitationProbabilityMax > 0 ? `강수확률 ${Math.round(today.precipitationProbabilityMax)}%` : "",',
  '    ].filter(Boolean).join(" | ")',
  '  : (Number.isFinite(currentTemp) ? `현재 ${Math.round(currentTemp)}°C` : "날씨 정보 없음");',
  'const weekBits = [];',
  'if (rainyDays > 0) weekBits.push(`비 예보 ${rainyDays}일`);',
  'if (hotDays > 0) weekBits.push(`더운 날 ${hotDays}일`);',
  'if (coldDays > 0) weekBits.push(`쌀쌀한 날 ${coldDays}일`);',
  'if (weekBits.length === 0 && dailyForecast.length > 0) weekBits.push("이번 주는 비교적 무난한 날씨");',
  'const weekSummaryText = weekBits.join(" | ");',
  'const weatherHints = [];',
  'if (today && (today.precipitationProbabilityMax >= 50 || today.precipitationSum >= 3 || [51,53,55,61,63,65,66,67,80,81,82,95,96,99].includes(today.weatherCode))) {',
  '  weatherHints.push("\\uBE44 \\uC624\\uB294 \\uB0A0\\uC740 \\uAD6D\\uBB3C, \\uB530\\uB73B\\uD55C \\uBA54\\uB274, \\uC2E4\\uB0B4 \\uCCB4\\uB958\\uAC00 \\uD3B8\\uD55C \\uACF3\\uC744 \\uC6B0\\uC120\\uD55C\\uB2E4.");',
  '}',
  'if (today && Number.isFinite(today.temperatureMax) && today.temperatureMax >= 28) {',
  '  weatherHints.push("\\uB354\\uC6B4 \\uB0A0\\uC740 \\uCC28\\uAC11\\uAC70\\uB098 \\uB9E4\\uCF64\\uD558\\uC9C0 \\uC54A\\uC740 \\uBA54\\uB274, \\uC2DC\\uC6D0\\uD55C \\uB9E4\\uC7A5 \\uC704\\uC8FC\\uB85C \\uACE0\\uB978\\uB2E4.");',
  '}',
  'if (today && Number.isFinite(today.temperatureMin) && today.temperatureMin <= 5) {',
  '  weatherHints.push("\\uC30D\\uC30D\\uD55C \\uB0A0\\uC740 \\uD0D5, \\uC804\\uACE8, \\uBA74\\uB958 \\uAC19\\uC740 \\uB530\\uB73B\\uD55C \\uBA54\\uB274\\uB97C \\uC6B0\\uC120\\uD55C\\uB2E4.");',
  '}',
  'if (rainyDays >= 3) {',
  '  weatherHints.push("\\uC774\\uBC88 \\uC8FC\\uB294 \\uBE44 \\uC608\\uBCF4\\uAC00 \\uC788\\uC5B4 \\uC2E4\\uB0B4\\uC5D0\\uC11C \\uB300\\uAE30\\uD558\\uAE30 \\uD3B8\\uD55C \\uACF3\\uC744 \\uC120\\uD638\\uD55C\\uB2E4.");',
  '}',
  'return [{',
  '  json: {',
  '    ...source,',
  '    weatherFetchError: payload.error ? String(payload.error?.message || payload.error || "") : "",',
  '    weatherContext: {',
  '      todaySummaryText,',
  '      weekSummaryText,',
  '      weatherHints,',
  '      dailyForecast,',
  '      current: {',
  '        temperatureC: Number.isFinite(currentTemp) ? currentTemp : null,',
  '        apparentTemperatureC: Number.isFinite(currentFeelsLike) ? currentFeelsLike : null,',
  '        weatherCode: current.weather_code ?? null,',
  '        weatherLabel: currentLabel || "",',
  '      },',
  '    },',
  '  }',
  '}];'
);

const selectCandidatePlacesCode = lines(
  "const source = $('Summarize Weather').first()?.json ?? {};",
  "const walkPayload = $('Search Walkable Restaurants').first()?.json ?? {};",
  "const drivePayloadEast = $('Search Drive Restaurants East').first()?.json ?? {};",
  "const drivePayloadWest = $('Search Drive Restaurants West').first()?.json ?? {};",
  "const drivePayloadNorth = $('Search Drive Restaurants North').first()?.json ?? {};",
  "const drivePayloadSouth = $('Search Drive Restaurants South').first()?.json ?? {};",
  'const excludedNames = Array.isArray(source.excludedPlaceNames) ? source.excludedPlaceNames : [];',
  'function normalize(value) {',
  '  return String(value || "").normalize("NFC").replace(/\\s+/g, "").toLowerCase();',
  '}',
  'const excludedSet = new Set(excludedNames.map(normalize));',
  'const hardExcludeKeywords = [',
  "  '\\uC220\\uC9D1',",
  "  '\\uD638\\uD504',",
  "  '\\uC774\\uC790\\uCE74\\uC57C',",
  "  '\\uBC14',",
  "  '\\uCE74\\uD398',",
  "  '\\uB514\\uC800\\uD2B8',",
  "  '\\uBCA0\\uC774\\uCEE4\\uB9AC',",
  "  '\\uC8FC\\uC810',",
  '].map(normalize);',
  'function shouldExcludeText(text) {',
  '  const target = normalize(text);',
  '  return hardExcludeKeywords.some((keyword) => target.includes(keyword));',
  '}',
  'const centerX = Number(source.centerX || 0);',
  'const centerY = Number(source.centerY || 0);',
  'function haversineMeters(lat1, lon1, lat2, lon2) {',
  '  const toRad = (value) => (Number(value) * Math.PI) / 180;',
  '  const earthRadiusMeters = 6371000;',
  '  const dLat = toRad(lat2 - lat1);',
  '  const dLon = toRad(lon2 - lon1);',
  '  const a = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2;',
  '  return 2 * earthRadiusMeters * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));',
  '}',
  'function mapDocs(payload, useCenterDistance = false) {',
  '  const docs = Array.isArray(payload.documents) ? payload.documents : [];',
  '  const mapped = docs',
  '    .filter((row) => row && typeof row === "object")',
  '    .map((row) => ({',
  '      xNumber: Number(row.x || 0),',
  '      yNumber: Number(row.y || 0),',
      '      placeName: String(row.place_name || "").trim(),',
      '      categoryName: String(row.category_name || "").trim(),',
      '      roadAddress: String(row.road_address_name || "").trim(),',
      '      address: String(row.address_name || "").trim(),',
      '      phone: String(row.phone || "").trim(),',
  '      distanceMeters: useCenterDistance && Number.isFinite(centerX) && Number.isFinite(centerY) && Number.isFinite(Number(row.x || NaN)) && Number.isFinite(Number(row.y || NaN))',
  '        ? Math.round(haversineMeters(centerY, centerX, Number(row.y || 0), Number(row.x || 0)))',
  '        : Number(row.distance || 0),',
      '      placeUrl: String(row.place_url || "").trim(),',
      '      x: String(row.x || "").trim(),',
      '      y: String(row.y || "").trim(),',
  '    }))',
  '    .filter((row) => row.placeName)',
  '    .filter((row) => !shouldExcludeText(row.placeName) && !shouldExcludeText(row.categoryName))',
  '    .sort((a, b) => a.distanceMeters - b.distanceMeters);',
  '  const result = [];',
  '  const seen = new Set();',
  '  for (const row of mapped) {',
  '    const key = normalize(row.placeName) + "|" + normalize(row.roadAddress || row.address);',
  '    if (seen.has(key)) continue;',
  '    seen.add(key);',
  '    result.push(row);',
  '  }',
  '  return result;',
  '}',
  'const walkPool = mapDocs(walkPayload).filter((row) => !excludedSet.has(normalize(row.placeName)));',
  'const walkCandidates = walkPool.slice(0, Math.max(6, Number(source.walkCandidateLimit || 14)));',
  'const walkKeys = new Set(walkCandidates.map((row) => normalize(row.placeName) + "|" + normalize(row.roadAddress || row.address)));',
  'const drivePayload = {',
  '  documents: [',
  '    ...(Array.isArray(drivePayloadEast.documents) ? drivePayloadEast.documents : []),',
  '    ...(Array.isArray(drivePayloadWest.documents) ? drivePayloadWest.documents : []),',
  '    ...(Array.isArray(drivePayloadNorth.documents) ? drivePayloadNorth.documents : []),',
  '    ...(Array.isArray(drivePayloadSouth.documents) ? drivePayloadSouth.documents : []),',
  '  ],',
  '  error: drivePayloadEast.error || drivePayloadWest.error || drivePayloadNorth.error || drivePayloadSouth.error || "",',
  '};',
  'const drivePool = mapDocs(drivePayload, true)',
  '  .filter((row) => !excludedSet.has(normalize(row.placeName)))',
  '  .filter((row) => Number(row.distanceMeters || 0) > Number(source.walkRadiusMeters || 1200))',
  '  .filter((row) => !walkKeys.has(normalize(row.placeName) + "|" + normalize(row.roadAddress || row.address)));',
  'const driveCandidates = drivePool.slice(0, Math.max(8, Number(source.driveCandidateLimit || 18)));',
  'const searchErrors = [',
  '  source.locationResolved ? "" : String(source.locationError || ""),',
  '  walkPayload.error ? String(walkPayload.error?.message || walkPayload.error || "") : "",',
  '  drivePayload.error ? String(drivePayload.error?.message || drivePayload.error || "") : "",',
  '].filter(Boolean);',
  'return [{',
  '  json: {',
  '    ...source,',
  '    walkCandidates,',
  '    driveCandidates,',
  '    totalWalkCandidateCount: walkPool.length,',
  '    totalDriveCandidateCount: drivePool.length,',
  '    totalCandidateCount: walkPool.length + drivePool.length,',
  '    searchError: searchErrors.join(" | "),',
  '  }',
  '}];'
);

const buildGeminiRequestCode = lines(
  "const selected = $('Select Candidate Places').first()?.json ?? {};",
  "const holiday = $('Determine Holiday').first()?.json ?? {};",
  'const weatherContext = selected.weatherContext || {};',
  'const schema = {',
  '  type: "OBJECT",',
  '  properties: {',
  '    title: { type: "STRING" },',
  '    summary: { type: "STRING" },',
  '    weather_comment: { type: "STRING" },',
  '    walk_recommendations: {',
  '      type: "ARRAY",',
  '      items: {',
  '        type: "OBJECT",',
  '        properties: {',
  '          rank: { type: "INTEGER" },',
  '          place_name: { type: "STRING" },',
  '          reason: { type: "STRING" },',
  '          menu_hint: { type: "STRING" },',
  '          distance_meters: { type: "INTEGER" },',
  '          place_url: { type: "STRING" },',
  '          budget_fit_note: { type: "STRING" }',
  '        },',
  '        required: ["rank", "place_name", "reason", "menu_hint", "distance_meters", "place_url", "budget_fit_note"]',
  '      }',
  '    },',
  '    drive_recommendations: {',
  '      type: "ARRAY",',
  '      items: {',
  '        type: "OBJECT",',
  '        properties: {',
  '          rank: { type: "INTEGER" },',
  '          place_name: { type: "STRING" },',
  '          reason: { type: "STRING" },',
  '          menu_hint: { type: "STRING" },',
  '          distance_meters: { type: "INTEGER" },',
  '          place_url: { type: "STRING" },',
  '          budget_fit_note: { type: "STRING" }',
  '        },',
  '        required: ["rank", "place_name", "reason", "menu_hint", "distance_meters", "place_url", "budget_fit_note"]',
  '      }',
  '    },',
  '    fallback_note: { type: "STRING" }',
  '  },',
  '  required: ["title", "summary", "weather_comment", "walk_recommendations", "drive_recommendations", "fallback_note"]',
  '};',
  'const userPayload = JSON.stringify({',
  '  target_location: selected.centerDisplayName || "",',
  '  location_query: selected.centerAddressQuery || "",',
  '  resolved_location: selected.centerLocationText || "",',
  '  date: holiday.today_date || "",',
  '  weekday: holiday.weekday_name || "",',
  '  request_source: selected.requestSource || "scheduled",',
  '  excluded_place_names: Array.isArray(selected.excludedPlaceNames) ? selected.excludedPlaceNames : [],',
  '  budget_per_person_krw: Number(selected.budgetPerPersonKrw || 10000),',
  '  walk_radius_meters: Number(selected.walkRadiusMeters || 1200),',
  '  drive_radius_meters: Number(selected.driveRadiusMeters || 6500),',
  '  weather: weatherContext,',
  '  rules: [',
  '    "Return up to 5 walkable recommendations and up to 5 driveable recommendations.",',
  '    "Walkable means appropriate for about 15 minutes on foot. Driveable means appropriate for about 20 minutes by car using the provided distance bucket only.",',
  '    "Use weather and this week forecast trend to bias the menu style and category.",',
  '    "Favor places that are plausible for about 10000 KRW per person, but never present exact price claims unless they are explicitly given.",',
  '    "If request_source is teams-reroll, avoid excluded_place_names unless there are not enough alternatives.",',
  '    "Balance cuisine variety when possible."',
  '  ],',
  '  walk_candidates: Array.isArray(selected.walkCandidates) ? selected.walkCandidates : [],',
  '  drive_candidates: Array.isArray(selected.driveCandidates) ? selected.driveCandidates : [],',
  '}, null, 2);',
  'const requestPayload = {',
  '  systemInstruction: {',
  '    parts: [',
  '      {',
  '        text: "You recommend weekday team lunch options for an office team. Use only the provided candidate places. Do not invent restaurants, prices, ratings, parking, opening hours, or menus not grounded in the input. Budget is 10000 KRW per person as a target only, so describe budget fit cautiously and say when it is uncertain."',
  '      }',
  '    ]',
  '  },',
  '  contents: [',
  '    {',
  '      role: "user",',
  '      parts: [',
  '        { text: userPayload }',
  '      ]',
  '    }',
  '  ],',
  '  generationConfig: {',
  '    responseMimeType: "application/json",',
  '    responseSchema: schema',
  '  }',
  '};',
  'return [{',
  '  json: {',
  '    ...selected,',
  '    geminiRequest: requestPayload,',
  '  }',
  '}];'
);

const parseRecommendationCode = lines(
  "const selected = $('Select Candidate Places').first()?.json ?? {};",
  'const payload = $input.first()?.json ?? {};',
  'const walkCandidates = Array.isArray(selected.walkCandidates) ? selected.walkCandidates : [];',
  'const driveCandidates = Array.isArray(selected.driveCandidates) ? selected.driveCandidates : [];',
  'function normalize(value) {',
  '  return String(value || "").normalize("NFC").replace(/\\s+/g, "").toLowerCase();',
  '}',
  'function compact(value, max = 220) {',
  '  const text = String(value || "").replace(/\\s+/g, " ").trim();',
  '  return text.length > max ? text.slice(0, max - 3) + "..." : text;',
  '}',
  'function summarizeRecommendationError(errorValue) {',
  '  const message = compact(errorValue);',
  '  if (!message) return "";',
  '  const upper = message.toUpperCase();',
  '  if (upper.includes("503") || upper.includes("UNAVAILABLE") || upper.includes("HIGH DEMAND")) {',
  '    return "\\uCD94\\uCC9C \\uBAA8\\uB378 \\uC751\\uB2F5\\uC774 \\uC9C0\\uC5F0\\uB418\\uC5B4 \\uD6C4\\uBCF4 \\uAE30\\uBC18 \\uAE30\\uBCF8 \\uCD94\\uCC9C\\uC73C\\uB85C \\uB300\\uCCB4\\uD588\\uC2B5\\uB2C8\\uB2E4.";',
  '  }',
  '  return message;',
  '}',
  'function extractOutputText(response) {',
  '  if (typeof response === "string" && response.trim()) return response.trim();',
  '  if (response && typeof response === "object" && !Array.isArray(response) && typeof response.title === "string" && Array.isArray(response.walk_recommendations)) {',
  '    return JSON.stringify(response);',
  '  }',
  '  const candidates = Array.isArray(response?.candidates) ? response.candidates : [];',
  '  const chunks = [];',
  '  for (const candidate of candidates) {',
  '    const parts = Array.isArray(candidate?.content?.parts) ? candidate.content.parts : [];',
  '    for (const part of parts) {',
  '      if (typeof part?.text === "string" && part.text.trim()) chunks.push(part.text.trim());',
  '    }',
  '  }',
  '  return chunks.join("\\n").trim();',
  '}',
  'const outputText = extractOutputText(payload);',
  'let parsed = null;',
  'let recommendationApiError = "";',
  'if (payload.error) {',
  '  recommendationApiError = summarizeRecommendationError(payload.error?.message || payload.error || payload.message || "Gemini request failed.");',
  '} else if (!outputText) {',
  '  recommendationApiError = summarizeRecommendationError("Gemini returned no recommendation text.");',
  '} else {',
  '  try {',
  '    parsed = JSON.parse(outputText);',
  '  } catch (error) {',
  '    recommendationApiError = summarizeRecommendationError("Failed to parse Gemini JSON: " + error.message);',
  '  }',
  '}',
  'function hydrate(rawItems, defaults, fallbackReason) {',
  '  const candidateMap = new Map(defaults.map((item) => [normalize(item.placeName), item]));',
  '  const hydrated = [];',
  '  const used = new Set();',
  '  const sourceItems = Array.isArray(rawItems) ? rawItems : [];',
  '  for (let index = 0; index < sourceItems.length; index += 1) {',
  '    const item = sourceItems[index] || {};',
  '    const matched = candidateMap.get(normalize(item.place_name));',
  '    if (!matched) continue;',
  '    const key = normalize(matched.placeName);',
  '    if (used.has(key)) continue;',
  '    used.add(key);',
  '    hydrated.push({',
  '      rank: Number(item.rank || hydrated.length + 1),',
  '      placeName: matched.placeName,',
  '      reason: compact(item.reason || fallbackReason),',
  '      menuHint: compact(item.menu_hint || matched.categoryName || ""),',
  '      budgetFitNote: compact(item.budget_fit_note || "\\uC608\\uC0B0 \\uC801\\uD569\\uC131\\uC740 \\uC5C5\\uC885 \\uAE30\\uBC18 \\uCD94\\uC815\\uCE58\\uC785\\uB2C8\\uB2E4."),',
  '      distanceMeters: Number(item.distance_meters || matched.distanceMeters || 0),',
  '      placeUrl: String(item.place_url || matched.placeUrl || ""),',
  '      categoryName: matched.categoryName || "",',
  '      roadAddress: matched.roadAddress || matched.address || "",',
  '    });',
  '    if (hydrated.length >= 5) break;',
  '  }',
  '  for (const candidate of defaults) {',
  '    if (hydrated.length >= 5) break;',
  '    const key = normalize(candidate.placeName);',
  '    if (used.has(key)) continue;',
  '    used.add(key);',
  '    hydrated.push({',
  '      rank: hydrated.length + 1,',
  '      placeName: candidate.placeName,',
  '      reason: compact(fallbackReason),',
  '      menuHint: compact(candidate.categoryName || ""),',
  '      budgetFitNote: "\\uC608\\uC0B0 \\uC801\\uD569\\uC131\\uC740 \\uC5C5\\uC885 \\uAE30\\uBC18 \\uCD94\\uC815\\uCE58\\uC785\\uB2C8\\uB2E4.",',
  '      distanceMeters: Number(candidate.distanceMeters || 0),',
  '      placeUrl: String(candidate.placeUrl || ""),',
  '      categoryName: candidate.categoryName || "",',
  '      roadAddress: candidate.roadAddress || candidate.address || "",',
  '    });',
  '  }',
  '  return hydrated;',
  '}',
  'const walkRecommendations = hydrate(',
  '  parsed?.walk_recommendations,',
  '  walkCandidates,',
  '  recommendationApiError ? "\\uCD94\\uCC9C API \\uC751\\uB2F5\\uC744 \\uD655\\uC815\\uD558\\uC9C0 \\uBABB\\uD574 \\uAC70\\uB9AC\\uC640 \\uC5C5\\uC885 \\uAE30\\uC900\\uC758 \\uB3C4\\uBCF4 \\uD6C4\\uBCF4\\uB97C \\uC81C\\uC2DC\\uD569\\uB2C8\\uB2E4." : "\\uB3C4\\uBCF4 \\uC774\\uB3D9\\uC5D0 \\uBB34\\uB9AC\\uAC00 \\uC801\\uC740 \\uD6C4\\uBCF4\\uB97C \\uC6B0\\uC120\\uD588\\uC2B5\\uB2C8\\uB2E4."',
  ');',
  'const driveRecommendations = hydrate(',
  '  parsed?.drive_recommendations,',
  '  driveCandidates,',
  '  recommendationApiError ? "\\uCD94\\uCC9C API \\uC751\\uB2F5\\uC744 \\uD655\\uC815\\uD558\\uC9C0 \\uBABB\\uD574 \\uCC28\\uB7C9 \\uC774\\uB3D9 \\uD6C4\\uBCF4\\uB97C \\uAC70\\uB9AC \\uAE30\\uC900\\uC73C\\uB85C \\uC81C\\uC2DC\\uD569\\uB2C8\\uB2E4." : "\\uCC28\\uB7C9\\uC73C\\uB85C \\uC774\\uB3D9\\uD558\\uAE30 \\uBB34\\uB9AC\\uAC00 \\uC801\\uC740 \\uD6C4\\uBCF4\\uB97C \\uACE8\\uB790\\uC2B5\\uB2C8\\uB2E4."',
  ');',
  'return [{',
  '  json: {',
  '    ...selected,',
  '    title: String(parsed?.title || (selected.requestSource === "teams-reroll" ? "\\uCD94\\uAC00 \\uC810\\uC2EC \\uCD94\\uCC9C" : "\\uC624\\uB298\\uC758 \\uC810\\uC2EC \\uCD94\\uCC9C")),',
  '    summary: String(parsed?.summary || "\\uAE30\\uC900 \\uC704\\uCE58 \\uADFC\\uCC98 \\uD6C4\\uBCF4\\uC5D0\\uC11C \\uB3C4\\uBCF4\\uAD8C\\uACFC \\uCC28\\uB7C9\\uAD8C\\uC744 \\uB098\\uB220 \\uC120\\uC815\\uD588\\uC2B5\\uB2C8\\uB2E4."),',
  '    weatherComment: String(parsed?.weather_comment || selected.weatherContext?.todaySummaryText || ""),',
  '    fallbackNote: String(parsed?.fallback_note || ""),',
  '    recommendationApiError,',
  '    walkRecommendations,',
  '    driveRecommendations,',
  '  }',
  '}];'
);

const buildTeamsPayloadCode = lines(
  "const recommendation = $('Parse Recommendation').first()?.json ?? {};",
  'const walkRecommendations = Array.isArray(recommendation.walkRecommendations) ? recommendation.walkRecommendations : [];',
  'const driveRecommendations = Array.isArray(recommendation.driveRecommendations) ? recommendation.driveRecommendations : [];',
  'const excludedBase = Array.isArray(recommendation.excludedPlaceNames) ? recommendation.excludedPlaceNames : [];',
  'function unique(values) {',
  '  return Array.from(new Set(values.filter(Boolean).map((value) => String(value).trim()).filter(Boolean)));',
  '}',
  'function formatTravel(mode, distanceMeters) {',
  '  const distance = Math.max(0, Math.round(Number(distanceMeters || 0)));',
  '  if (mode === "walk") {',
  '    const minutes = Math.max(1, Math.round(distance / 70));',
  '    return `${distance}m, 도보 약 ${minutes}분`;',
  '  }',
  '  const minutes = Math.max(3, Math.round(distance / 400));',
  '  return `${distance}m, 차량 약 ${minutes}분`;',
  '}',
  'function pushRecommendationSection(body, title, items, mode) {',
  '  body.push({ type: "TextBlock", text: title, weight: "Bolder", size: "Medium", wrap: true, spacing: "Medium" });',
  '  if (!Array.isArray(items) || items.length === 0) {',
  '    body.push({ type: "TextBlock", text: "\\uD6C4\\uBCF4\\uB97C \\uD655\\uBCF4\\uD558\\uC9C0 \\uBABB\\uD588\\uC2B5\\uB2C8\\uB2E4.", wrap: true, spacing: "Small", isSubtle: true });',
  '    return;',
  '  }',
  '  for (let index = 0; index < items.length; index += 1) {',
  '    const item = items[index] || {};',
  '    const displayRank = index + 1;',
  '    const placeText = item.placeUrl ? `[${item.placeName}](${item.placeUrl})` : String(item.placeName || "").trim();',
  '    const menuText = String(item.menuHint || item.categoryName || "\\uBA54\\uB274 \\uC815\\uBCF4 \\uC5C6\\uC74C").trim();',
  '    const travelText = formatTravel(mode, item.distanceMeters);',
  '    body.push({',
  '      type: "TextBlock",',
  '      text: `${displayRank}\\\\. ${placeText} (${menuText}) (${travelText})`,',
  '      wrap: true,',
  '      spacing: "Small",',
  '    });',
  '    if (displayRank === 1 && String(item.reason || "").trim()) {',
  '      body.push({',
  '        type: "TextBlock",',
  '        text: `1\\uBC88 \\uCD94\\uCC9C \\uC774\\uC720: ${String(item.reason).trim()}`,',
  '        wrap: true,',
  '        spacing: "None",',
  '        isSubtle: true,',
  '      });',
  '    }',
  '  }',
  '}',
  'const cardBody = [',
  '  { type: "TextBlock", text: recommendation.title || "\\uC810\\uC2EC \\uCD94\\uCC9C", weight: "Bolder", size: "Large", wrap: true },',
  '  { type: "TextBlock", text: String(recommendation.centerDisplayName || ""), wrap: true, spacing: "Small", isSubtle: true },',
  '];',
  'pushRecommendationSection(cardBody, "\\uB3C4\\uBCF4 \\uC774\\uC6A9 \\uCD94\\uCC9C \\uC2DD\\uB2F9 - 5\\uAC1C", walkRecommendations, "walk");',
  'pushRecommendationSection(cardBody, "\\uCC28\\uB7C9 \\uC774\\uC6A9 \\uCD94\\uCC9C \\uC2DD\\uB2F9 - 5\\uAC1C", driveRecommendations, "drive");',
  'if (recommendation.recommendationApiError) {',
  '  cardBody.push({ type: "TextBlock", text: "\\uCC38\\uACE0: " + String(recommendation.recommendationApiError), wrap: true, spacing: "Medium", color: "Attention" });',
  '}',
  'if (recommendation.searchError) {',
  '  cardBody.push({ type: "TextBlock", text: "\\uCC38\\uACE0: " + String(recommendation.searchError), wrap: true, spacing: "Small", color: "Attention" });',
  '}',
  'if (recommendation.weatherFetchError) {',
  '  cardBody.push({ type: "TextBlock", text: "\\uB0A0\\uC528 API \\uCC38\\uACE0: " + String(recommendation.weatherFetchError), wrap: true, spacing: "Small", color: "Warning" });',
  '}',
  'if (recommendation.fallbackNote) {',
  '  cardBody.push({ type: "TextBlock", text: String(recommendation.fallbackNote), wrap: true, spacing: "Small", isSubtle: true });',
  '}',
  'const excludeNames = unique([',
  '  ...excludedBase,',
  '  ...walkRecommendations.map((item) => item.placeName),',
  '  ...driveRecommendations.map((item) => item.placeName),',
  ']);',
  'const remainingCandidateCount = Math.max(0, Number(recommendation.totalCandidateCount || 0) - excludeNames.length);',
  'const actions = [];',
  'if (recommendation.moreRecommendationsUrlBase && remainingCandidateCount > 0) {',
  '  const query = "?exclude=" + encodeURIComponent(excludeNames.join("|")) + "&source=teams";',
  '  actions.push({ type: "Action.OpenUrl", title: "\\uB2E4\\uB978 \\uCD94\\uCC9C \\uB354 \\uBC1B\\uAE30", url: recommendation.moreRecommendationsUrlBase + query });',
  '}',
  'if (recommendation.nearbySearchLink) {',
  '  actions.push({ type: "Action.OpenUrl", title: "\\uCE74\\uCE74\\uC624\\uB9F5\\uC5D0\\uC11C \\uBCF4\\uAE30", url: recommendation.nearbySearchLink });',
  '}',
  'return [{',
  '  json: {',
  '    cardBody,',
  '    cardActions: actions,',
  '  }',
  '}];'
);

const workflow = {
  name: workflowName,
  nodes: [
    {
      parameters: {
        rule: {
          interval: [{ field: 'cronExpression', expression: '0 30 11 * * 1-5' }],
        },
      },
      type: 'n8n-nodes-base.scheduleTrigger',
      typeVersion: 1.3,
      position: [-1760, -160],
      id: uuid('schedule'),
      name: 'Lunch Recommendation Schedule',
      alwaysOutputData: true,
    },
    {
      parameters: {
        httpMethod: 'GET',
        path: MORE_RECOMMEND_WEBHOOK_PATH,
        options: {},
      },
      type: 'n8n-nodes-base.webhook',
      typeVersion: 2.1,
      position: [-1760, 16],
      id: uuid('more-webhook'),
      name: 'More Recommendation Webhook',
      webhookId: uuid('more-webhook-id'),
    },
    {
      parameters: { jsCode: weekdayBaselineCode },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [-1504, -72],
      id: uuid('weekday-baseline'),
      name: 'Weekday Baseline',
      alwaysOutputData: true,
    },
    {
      parameters: {
        operation: 'executeQuery',
        query:
          "=DECLARE @d DATE = CAST('{{ $('Weekday Baseline').item.json.todayDate }}' AS date);\nSELECT\n    CONVERT(VARCHAR(8), @d, 112) AS check_date,\n    CAST(CASE WHEN EXISTS (\n        SELECT 1\n        FROM TsMgmt.dbo.HolidayCalendarKR\n        WHERE HolidayDate = @d\n    ) THEN 1 ELSE 0 END AS bit) AS found_in_db,\n    ISNULL((SELECT TOP 1 HolidayName FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), '') AS holiday_name,\n    ISNULL((SELECT TOP 1 SourceType FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), '') AS source_type,\n    ISNULL((SELECT TOP 1 SourceYear FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), 0) AS source_year;",
      },
      type: 'n8n-nodes-base.microsoftSql',
      typeVersion: 1.1,
      position: [-1248, -72],
      id: uuid('holiday-db'),
      name: 'Holiday DB Fallback',
      alwaysOutputData: true,
      onError: 'continueRegularOutput',
      credentials: {
        microsoftSql: {
          id: '2dZb5OQPbTyO3052',
          name: 'TsMgmt(DevTest_SQL2022_26)',
        },
      },
    },
    {
      parameters: { jsCode: determineHolidayCode },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [-992, -72],
      id: uuid('determine-holiday'),
      name: 'Determine Holiday',
      alwaysOutputData: true,
    },
    {
      parameters: {
        conditions: {
          options: {
            caseSensitive: true,
            leftValue: '',
            typeValidation: 'loose',
            version: 2,
          },
          conditions: [
            {
              id: uuid('not-holiday-condition'),
              leftValue: '={{ $json.is_holiday }}',
              rightValue: false,
              operator: { type: 'boolean', operation: 'equals' },
            },
          ],
          combinator: 'and',
        },
        options: {},
      },
      type: 'n8n-nodes-base.if',
      typeVersion: 2.2,
      position: [-736, -72],
      id: uuid('not-holiday'),
      name: 'Not Holiday',
      alwaysOutputData: false,
    },
    {
      parameters: {
        method: 'GET',
        url: 'https://dapi.kakao.com/v2/local/search/address.json',
        authentication: 'predefinedCredentialType',
        nodeCredentialType: 'httpHeaderAuth',
        sendHeaders: true,
        headerParameters: {
          parameters: [
            { name: 'Accept', value: 'application/json' },
          ],
        },
        sendQuery: true,
        queryParameters: {
          parameters: [{ name: 'query', value: CONFIG.locationQuery }],
        },
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.3,
      position: [-480, -72],
      id: uuid('resolve-location'),
      name: 'Resolve Recommendation Center',
      alwaysOutputData: true,
      onError: 'continueRegularOutput',
      credentials: {
        httpHeaderAuth: KAKAO_CREDENTIAL,
      },
    },
    {
      parameters: { jsCode: buildSearchCenterCode },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [-224, -72],
      id: uuid('build-center'),
      name: 'Build Search Center',
      alwaysOutputData: true,
    },
    {
      parameters: {
        method: 'GET',
        url: 'https://api.open-meteo.com/v1/forecast',
        sendQuery: true,
        queryParameters: {
          parameters: [
            { name: 'latitude', value: '={{ $json.centerY }}' },
            { name: 'longitude', value: '={{ $json.centerX }}' },
            { name: 'timezone', value: 'Asia/Seoul' },
            { name: 'forecast_days', value: '7' },
            { name: 'current', value: 'temperature_2m,apparent_temperature,weather_code' },
            { name: 'daily', value: 'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum' },
          ],
        },
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.3,
      position: [32, -72],
      id: uuid('weather-forecast'),
      name: 'Fetch Weather Forecast',
      alwaysOutputData: true,
      onError: 'continueRegularOutput',
    },
    {
      parameters: { jsCode: summarizeWeatherCode },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [288, -72],
      id: uuid('weather-summary'),
      name: 'Summarize Weather',
      alwaysOutputData: true,
    },
    {
      parameters: {
        method: 'GET',
        url: 'https://dapi.kakao.com/v2/local/search/category.json',
        authentication: 'predefinedCredentialType',
        nodeCredentialType: 'httpHeaderAuth',
        sendHeaders: true,
        headerParameters: {
          parameters: [
            { name: 'Accept', value: 'application/json' },
          ],
        },
        sendQuery: true,
        queryParameters: {
          parameters: [
            { name: 'category_group_code', value: 'FD6' },
            { name: 'x', value: "={{ $('Summarize Weather').first().json.centerX }}" },
            { name: 'y', value: "={{ $('Summarize Weather').first().json.centerY }}" },
            { name: 'radius', value: "={{ String($('Summarize Weather').first().json.walkRadiusMeters || 1200) }}" },
            { name: 'sort', value: 'distance' },
            { name: 'size', value: '15' },
          ],
        },
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.3,
      position: [544, -168],
      id: uuid('walk-search'),
      name: 'Search Walkable Restaurants',
      alwaysOutputData: true,
      onError: 'continueRegularOutput',
      credentials: {
        httpHeaderAuth: KAKAO_CREDENTIAL,
      },
    },
    {
      parameters: {
        method: 'GET',
        url: 'https://dapi.kakao.com/v2/local/search/category.json',
        authentication: 'predefinedCredentialType',
        nodeCredentialType: 'httpHeaderAuth',
        sendHeaders: true,
        headerParameters: {
          parameters: [
            { name: 'Accept', value: 'application/json' },
          ],
        },
        sendQuery: true,
        queryParameters: {
          parameters: [
            { name: 'category_group_code', value: 'FD6' },
            { name: 'x', value: "={{ $('Summarize Weather').first().json.driveSearchPoints?.east?.x || $('Summarize Weather').first().json.centerX }}" },
            { name: 'y', value: "={{ $('Summarize Weather').first().json.driveSearchPoints?.east?.y || $('Summarize Weather').first().json.centerY }}" },
            { name: 'radius', value: "={{ String($('Summarize Weather').first().json.driveSearchRadiusMeters || 2500) }}" },
            { name: 'sort', value: 'distance' },
            { name: 'size', value: '15' },
          ],
        },
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.3,
      position: [544, 24],
      id: uuid('drive-search'),
      name: 'Search Drive Restaurants East',
      alwaysOutputData: true,
      onError: 'continueRegularOutput',
      credentials: {
        httpHeaderAuth: KAKAO_CREDENTIAL,
      },
    },
    {
      parameters: {
        method: 'GET',
        url: 'https://dapi.kakao.com/v2/local/search/category.json',
        authentication: 'predefinedCredentialType',
        nodeCredentialType: 'httpHeaderAuth',
        sendHeaders: true,
        headerParameters: {
          parameters: [
            { name: 'Accept', value: 'application/json' },
          ],
        },
        sendQuery: true,
        queryParameters: {
          parameters: [
            { name: 'category_group_code', value: 'FD6' },
            { name: 'x', value: "={{ $('Summarize Weather').first().json.driveSearchPoints?.west?.x || $('Summarize Weather').first().json.centerX }}" },
            { name: 'y', value: "={{ $('Summarize Weather').first().json.driveSearchPoints?.west?.y || $('Summarize Weather').first().json.centerY }}" },
            { name: 'radius', value: "={{ String($('Summarize Weather').first().json.driveSearchRadiusMeters || 2500) }}" },
            { name: 'sort', value: 'distance' },
            { name: 'size', value: '15' },
          ],
        },
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.3,
      position: [544, 120],
      id: uuid('drive-search-page-2'),
      name: 'Search Drive Restaurants West',
      alwaysOutputData: true,
      onError: 'continueRegularOutput',
      credentials: {
        httpHeaderAuth: KAKAO_CREDENTIAL,
      },
    },
    {
      parameters: {
        method: 'GET',
        url: 'https://dapi.kakao.com/v2/local/search/category.json',
        authentication: 'predefinedCredentialType',
        nodeCredentialType: 'httpHeaderAuth',
        sendHeaders: true,
        headerParameters: {
          parameters: [
            { name: 'Accept', value: 'application/json' },
          ],
        },
        sendQuery: true,
        queryParameters: {
          parameters: [
            { name: 'category_group_code', value: 'FD6' },
            { name: 'x', value: "={{ $('Summarize Weather').first().json.driveSearchPoints?.north?.x || $('Summarize Weather').first().json.centerX }}" },
            { name: 'y', value: "={{ $('Summarize Weather').first().json.driveSearchPoints?.north?.y || $('Summarize Weather').first().json.centerY }}" },
            { name: 'radius', value: "={{ String($('Summarize Weather').first().json.driveSearchRadiusMeters || 2500) }}" },
            { name: 'sort', value: 'distance' },
            { name: 'size', value: '15' },
          ],
        },
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.3,
      position: [544, 216],
      id: uuid('drive-search-page-3'),
      name: 'Search Drive Restaurants North',
      alwaysOutputData: true,
      onError: 'continueRegularOutput',
      credentials: {
        httpHeaderAuth: KAKAO_CREDENTIAL,
      },
    },
    {
      parameters: {
        method: 'GET',
        url: 'https://dapi.kakao.com/v2/local/search/category.json',
        authentication: 'predefinedCredentialType',
        nodeCredentialType: 'httpHeaderAuth',
        sendHeaders: true,
        headerParameters: {
          parameters: [
            { name: 'Accept', value: 'application/json' },
          ],
        },
        sendQuery: true,
        queryParameters: {
          parameters: [
            { name: 'category_group_code', value: 'FD6' },
            { name: 'x', value: "={{ $('Summarize Weather').first().json.driveSearchPoints?.south?.x || $('Summarize Weather').first().json.centerX }}" },
            { name: 'y', value: "={{ $('Summarize Weather').first().json.driveSearchPoints?.south?.y || $('Summarize Weather').first().json.centerY }}" },
            { name: 'radius', value: "={{ String($('Summarize Weather').first().json.driveSearchRadiusMeters || 2500) }}" },
            { name: 'sort', value: 'distance' },
            { name: 'size', value: '15' },
          ],
        },
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.3,
      position: [544, 312],
      id: uuid('drive-search-south'),
      name: 'Search Drive Restaurants South',
      alwaysOutputData: true,
      onError: 'continueRegularOutput',
      credentials: {
        httpHeaderAuth: KAKAO_CREDENTIAL,
      },
    },
    {
      parameters: { jsCode: selectCandidatePlacesCode },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [800, -72],
      id: uuid('select-candidates'),
      name: 'Select Candidate Places',
      alwaysOutputData: true,
    },
    {
      parameters: { jsCode: buildGeminiRequestCode },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [1056, -72],
      id: uuid('build-gemini-request'),
      name: 'Build Gemini Request',
      alwaysOutputData: true,
    },
    {
      parameters: {
        method: 'POST',
        url: `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`,
        sendHeaders: true,
        headerParameters: {
          parameters: [
            { name: 'x-goog-api-key', value: GEMINI_API_KEY },
            { name: 'Content-Type', value: 'application/json' },
          ],
        },
        sendBody: true,
        contentType: 'json',
        specifyBody: 'json',
        bodyParameters: { parameters: [{}] },
        jsonBody: '={{ $json.geminiRequest }}',
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.3,
      position: [1312, -72],
      id: uuid('gemini-recommend'),
      name: 'Ask Gemini Lunch Recommendation',
      alwaysOutputData: true,
      onError: 'continueRegularOutput',
    },
    {
      parameters: { jsCode: parseRecommendationCode },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [1568, -72],
      id: uuid('parse-recommendation'),
      name: 'Parse Recommendation',
      alwaysOutputData: true,
    },
    {
      parameters: { jsCode: buildTeamsPayloadCode },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [1824, -72],
      id: uuid('build-teams-payload'),
      name: 'Build Teams Payload',
      alwaysOutputData: true,
    },
    {
      parameters: {
        method: 'POST',
        url: TEAMS_WEBHOOK,
        sendBody: true,
        contentType: 'json',
        specifyBody: 'json',
        bodyParameters: { parameters: [{}] },
        jsonBody:
          "={{ ({ type: 'message', attachments: [{ contentType: 'application/vnd.microsoft.card.adaptive', content: { type: 'AdaptiveCard', body: Array.isArray($json.cardBody) ? $json.cardBody : [], actions: Array.isArray($json.cardActions) ? $json.cardActions : [], '$schema': 'http://adaptivecards.io/schemas/adaptive-card.json', version: '1.4' } }] }) }}",
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.3,
      position: [2080, -72],
      id: uuid('teams-webhook'),
      name: 'Lunch Teams Webhook',
      alwaysOutputData: false,
    },
  ],
  connections: {
    'Lunch Recommendation Schedule': {
      main: [[{ node: 'Weekday Baseline', type: 'main', index: 0 }]],
    },
    'More Recommendation Webhook': {
      main: [[{ node: 'Weekday Baseline', type: 'main', index: 0 }]],
    },
    'Weekday Baseline': {
      main: [[{ node: 'Holiday DB Fallback', type: 'main', index: 0 }]],
    },
    'Holiday DB Fallback': {
      main: [[{ node: 'Determine Holiday', type: 'main', index: 0 }]],
    },
    'Determine Holiday': {
      main: [[{ node: 'Not Holiday', type: 'main', index: 0 }]],
    },
    'Not Holiday': {
      main: [[{ node: 'Resolve Recommendation Center', type: 'main', index: 0 }], []],
    },
    'Resolve Recommendation Center': {
      main: [[{ node: 'Build Search Center', type: 'main', index: 0 }]],
    },
    'Build Search Center': {
      main: [[{ node: 'Fetch Weather Forecast', type: 'main', index: 0 }]],
    },
    'Fetch Weather Forecast': {
      main: [[{ node: 'Summarize Weather', type: 'main', index: 0 }]],
    },
    'Summarize Weather': {
      main: [[{ node: 'Search Walkable Restaurants', type: 'main', index: 0 }]],
    },
    'Search Walkable Restaurants': {
      main: [[{ node: 'Search Drive Restaurants East', type: 'main', index: 0 }]],
    },
    'Search Drive Restaurants East': {
      main: [[{ node: 'Search Drive Restaurants West', type: 'main', index: 0 }]],
    },
    'Search Drive Restaurants West': {
      main: [[{ node: 'Search Drive Restaurants North', type: 'main', index: 0 }]],
    },
    'Search Drive Restaurants North': {
      main: [[{ node: 'Search Drive Restaurants South', type: 'main', index: 0 }]],
    },
    'Search Drive Restaurants South': {
      main: [[{ node: 'Select Candidate Places', type: 'main', index: 0 }]],
    },
    'Select Candidate Places': {
      main: [[{ node: 'Build Gemini Request', type: 'main', index: 0 }]],
    },
    'Build Gemini Request': {
      main: [[{ node: 'Ask Gemini Lunch Recommendation', type: 'main', index: 0 }]],
    },
    'Ask Gemini Lunch Recommendation': {
      main: [[{ node: 'Parse Recommendation', type: 'main', index: 0 }]],
    },
    'Parse Recommendation': {
      main: [[{ node: 'Build Teams Payload', type: 'main', index: 0 }]],
    },
    'Build Teams Payload': {
      main: [[{ node: 'Lunch Teams Webhook', type: 'main', index: 0 }]],
    },
  },
  settings: {
    executionOrder: 'v1',
  },
};

fs.mkdirSync(workflowDir, { recursive: true });
fs.writeFileSync(workflowPath, JSON.stringify(workflow, null, 2) + '\n', 'utf8');
console.log(workflowPath);
