const fs = require('fs');
const path = require('path');

function loadEnvFile(envPath) {
  const env = {};
  if (!fs.existsSync(envPath)) return env;
  const text = fs.readFileSync(envPath, 'utf8');
  for (const line of text.split(/\r?\n/)) {
    if (!line || /^\s*#/.test(line)) continue;
    const match = line.match(/^(.*?)=(.*)$/);
    if (match) env[match[1]] = match[2];
  }
  return env;
}

const root = process.cwd();
const env = loadEnvFile(path.join(root, 'n8n.env'));
const workflowDir = path.join(root, 'workflows', 'Check-Active-Workflow');
const workflowPath = path.join(workflowDir, 'Check-Active-Workflow_api.json');

const N8N_BASE_URL = 'http://192.168.1.85:5678';
const N8N_DISPLAY_BASE_URL = 'https://n8n.vmsmozart-test.com:8443';
const N8N_API_KEY = env.N8N_API_KEY || '';
const MONITOR_WEBHOOK =
  process.env.TS_MONITOR_TEAMS_WEBHOOK || 'https://redacted.invalid/powerautomate/check-active-workflow-webhook';
const NOTION_CREDENTIAL = { id: 'LrLyYGhPvHMbPfZm', name: 'tsupport API' };

function requestHeaders() {
  return [
    { name: 'accept', value: 'application/json' },
    { name: 'accept-encoding', value: 'identity' },
    { name: 'ngrok-skip-browser-warning', value: 'true' },
    { name: 'X-N8N-API-KEY', value: N8N_API_KEY },
  ];
}

function scheduleNode() {
  return {
    parameters: {
      rule: {
        interval: [
          { field: 'cronExpression', expression: '0 0 7 * * 1-5' },
          { field: 'cronExpression', expression: '0 5 16 * * 1-5' },
        ],
      },
    },
    type: 'n8n-nodes-base.scheduleTrigger',
    typeVersion: 1.3,
    position: [-920, 0],
    id: '8d267ed2-f58a-4fd0-8d4d-5f23eea90567',
    name: 'Health Schedule',
    alwaysOutputData: true,
  };
}

const weekdayBaselineCode = [
  'const now = new Date();',
  'const pad = (value) => String(value).padStart(2, "0");',
  'const weekdayNames = ["\\uC77C\\uC694\\uC77C", "\\uC6D4\\uC694\\uC77C", "\\uD654\\uC694\\uC77C", "\\uC218\\uC694\\uC77C", "\\uBAA9\\uC694\\uC77C", "\\uAE08\\uC694\\uC77C", "\\uD1A0\\uC694\\uC77C"];',
  'const year = String(now.getFullYear());',
  'const month = pad(now.getMonth() + 1);',
  'const day = pad(now.getDate());',
  'const weekdayIndex = now.getDay();',
  'const isWeekend = weekdayIndex === 0 || weekdayIndex === 6;',
  'return [{',
  '  json: {',
  '    todayDate: `${year}-${month}-${day}`,',
  '    todayInt: `${year}${month}${day}`,',
  '    todayMMDD: `${month}${day}`,',
  '    WeekdayName: weekdayNames[weekdayIndex],',
  '    IsWeekend: isWeekend,',
  '    DefaultIsHoliday: isWeekend,',
  "    DefaultHolidayName: isWeekend ? '\\uC8FC\\uB9D0' : '\\uD3C9\\uC77C',",
  '  }',
  '}];',
].join('\n');

const determineHolidayCode = [
  "const baseline = $('Weekday Baseline').first()?.json ?? {};",
  "const dbPayload = $('Holiday DB Fallback').first()?.json ?? {};",
  "const dbFound = !dbPayload.error && [true, 1, '1', 'true'].includes(dbPayload.found_in_db);",
  'let isHoliday = !!baseline.DefaultIsHoliday;',
  "let holidayName = baseline.DefaultHolidayName || (isHoliday ? '\\uC8FC\\uB9D0' : '\\uD3C9\\uC77C');",
  "let holidayLookupSource = isHoliday ? 'default-weekend' : 'default-weekday';",
  'if (dbFound) {',
  '  isHoliday = true;',
  "  holidayName = String(dbPayload.holiday_name || '\\uACF5\\uD734\\uC77C');",
  "  holidayLookupSource = dbPayload.source_type ? `db:${dbPayload.source_type}` : 'db';",
  '}',
  'return [{',
  '  json: {',
  '    today_date: baseline.todayDate || "",',
  '    is_holiday: isHoliday,',
  '    holiday_name: holidayName,',
  '    holiday_lookup_source: holidayLookupSource,',
  '    is_weekend: !!baseline.IsWeekend,',
  "    db_error: dbPayload.error || '',",
  '  }',
  '}];',
].join('\n');

const expandActiveWorkflowsCode = [
  `const baseUrl = ${JSON.stringify(N8N_BASE_URL)};`,
  `const displayBaseUrl = ${JSON.stringify(N8N_DISPLAY_BASE_URL)};`,
  "const payload = $input.first()?.json ?? {};",
  "const list = Array.isArray(payload.data) ? payload.data : [];",
  "const fallbackUrl = baseUrl + '/api/v1/workflows?limit=1';",
  "const workflowBaseUrl = displayBaseUrl + '/workflow/';",
  "function compactText(value, max = 220) {",
  "  const text = String(value ?? '').replace(/\\s+/g, ' ').trim();",
  "  return text.length > max ? text.slice(0, max - 3) + '...' : text;",
  "}",
  "function extractErrorText(obj) {",
  "  return compactText(obj?.error?.message || obj?.error || obj?.message || 'Unknown workflow list error.');",
  "}",
  "if (!Array.isArray(payload.data)) {",
  "  return [{ json: { workflowFetchError: extractErrorText(payload), workflowId: '', workflowName: '', executionUrl: fallbackUrl, fallbackUrl, workflowLink: '', hasScheduleTrigger: false } }];",
  "}",
  "const active = list",
  "  .filter((wf) => wf && wf.active && !wf.isArchived && wf.name !== 'Check-Active-Workflow')",
  "  .sort((a, b) => String(a.name || '').localeCompare(String(b.name || '')));",
  "if (active.length === 0) {",
  "  return [{ json: { workflowNote: 'No active workflows found.', workflowId: '', workflowName: '\\uC810\\uAC80 \\uB300\\uC0C1 \\uC5C6\\uC74C', executionUrl: fallbackUrl, fallbackUrl, workflowLink: '', hasScheduleTrigger: false } }];",
  "}",
  "return active.map((wf) => {",
  "  const nodes = Array.isArray(wf.nodes) ? wf.nodes : [];",
  "  const hasScheduleTrigger = nodes.some((node) => node?.type === 'n8n-nodes-base.scheduleTrigger');",
  "  return {",
  "    json: {",
  "      workflowId: String(wf.id || ''),",
  "      workflowName: String(wf.name || ''),",
  "      workflowLink: workflowBaseUrl + String(wf.id || ''),",
  "      hasScheduleTrigger,",
  "      executionUrl: baseUrl + '/api/v1/executions?workflowId=' + encodeURIComponent(String(wf.id || '')) + '&limit=5&includeData=true',",
  "      fallbackUrl,",
  "    },",
  "  };",
  "});",
].join('\n');

const normalizeStatusCode = [
  "const sourceItems = $('Expand Active Workflows').all().map((item) => item.json ?? {});",
  "const payloadItems = $('Fetch Latest Executions').all().map((item) => item.json ?? {});",
  "const runningPayload = $('Fetch Running Executions').first()?.json ?? {};",
  "const runningExecs = Array.isArray(runningPayload.data) ? runningPayload.data : [];",
  "const K = {",
  "  none: '\\uC5C6\\uC74C',",
  "  scheduleType: '\\uC2A4\\uCF00\\uC904',",
  "  eventType: '\\uC774\\uBCA4\\uD2B8',",
  "  unknown: '\\uD655\\uC778 \\uBD88\\uAC00',",
  "  healthyReason: '\\uCD5C\\uADFC \\uC2E4\\uD589\\uC774 \\uC815\\uC0C1\\uC785\\uB2C8\\uB2E4.',",
  "  runningReason: '\\uD604\\uC7AC \\uC2E4\\uD589 \\uC911\\uC785\\uB2C8\\uB2E4.',",
  "  noExecEvent: '\\uC774\\uBCA4\\uD2B8 \\uAE30\\uBC18 \\uC6CC\\uD06C\\uD50C\\uB85C\\uC6B0\\uB85C \\uCD5C\\uADFC \\uC2E4\\uD589 \\uC774\\uB825\\uC774 \\uC5C6\\uC2B5\\uB2C8\\uB2E4.',",
  "  noExecSchedule: '\\uC2A4\\uCF00\\uC904 \\uC6CC\\uD06C\\uD50C\\uB85C\\uC6B0\\uC778\\uB370 \\uCD5C\\uADFC \\uC2E4\\uD589 \\uC774\\uB825\\uC774 \\uC5C6\\uC2B5\\uB2C8\\uB2E4.',",
  "  oldExecSchedule: '\\uCD5C\\uADFC 72\\uC2DC\\uAC04 \\uB0B4 \\uC2E4\\uD589 \\uC774\\uB825\\uC774 \\uC5C6\\uC2B5\\uB2C8\\uB2E4.',",
  "  errorExec: '\\uB9C8\\uC9C0\\uB9C9 \\uC2E4\\uD589\\uC774 error \\uC0C1\\uD0DC\\uC785\\uB2C8\\uB2E4.',",
  "  executionFetchError: '\\uC2E4\\uD589 \\uC774\\uB825 \\uC870\\uD68C \\uC2E4\\uD328',",
  "  workflowFetchError: '\\uC6CC\\uD06C\\uD50C\\uB85C\\uC6B0 \\uBAA9\\uB85D \\uC870\\uD68C \\uC2E4\\uD328',",
  "  statusNormal: '\\uC815\\uC0C1',",
  "  statusIssue: '\\uC774\\uC0C1',",
  "  statusNote: '\\uCC38\\uACE0',",
  "};",
  "function compactText(value, max = 220) {",
  "  const text = String(value ?? '').replace(/\\s+/g, ' ').trim();",
  "  return text.length > max ? text.slice(0, max - 3) + '...' : text;",
  "}",
  "function toLocalDateTimeString(isoString) {",
  "  if (!isoString) return K.none;",
  "  const date = new Date(isoString);",
  "  if (Number.isNaN(date.getTime())) return String(isoString ?? K.none);",
  "  const pad = (value) => String(value).padStart(2, '0');",
  "  return date.getFullYear() + '-' + pad(date.getMonth() + 1) + '-' + pad(date.getDate()) + ' ' + pad(date.getHours()) + ':' + pad(date.getMinutes()) + ':' + pad(date.getSeconds()) + ' KST';",
  "}",
  "function extractErrorText(obj) {",
  "  return compactText(obj?.error?.message || obj?.error || obj?.message || obj?.description || 'Unknown execution error.');",
  "}",
  "function extractErrorDetail(exec) {",
  "  const err = exec?.data?.resultData?.error;",
  "  if (!err) return '';",
  "  const nodeName = err.node?.name || err.context?.nodeName || '';",
  "  const parts = [err.description, Array.isArray(err.messages) ? err.messages[0] : '', err.message].filter(Boolean);",
  "  const text = compactText(parts.join(' / '));",
  "  return nodeName ? '[' + nodeName + '] ' + text : text;",
  "}",
  "const statuses = sourceItems.map((source, index) => {",
  "  const payload = payloadItems[index] ?? {};",
  "  if (source.workflowFetchError) {",
  "    return { json: { name: K.workflowFetchError, id: '', link: '', typeText: K.unknown, lastStatus: K.unknown, lastRunText: K.none, stateLabel: K.statusIssue, reason: compactText(source.workflowFetchError), errorDetail: K.none } };",
  "  }",
  "  if (source.workflowNote) {",
  "    return { json: { name: source.workflowName || '\\uC810\\uAC80 \\uB300\\uC0C1 \\uC5C6\\uC74C', id: '', link: '', typeText: K.unknown, lastStatus: K.none, lastRunText: K.none, stateLabel: K.statusNote, reason: compactText(source.workflowNote), errorDetail: K.none } };",
  "  }",
  "  const typeText = source.hasScheduleTrigger ? K.scheduleType : K.eventType;",
  "  if (!Array.isArray(payload.data)) {",
  "    return { json: { name: source.workflowName || K.unknown, id: source.workflowId || '', link: source.workflowLink || '', typeText, lastStatus: K.unknown, lastRunText: K.none, stateLabel: K.statusIssue, reason: K.executionFetchError, errorDetail: extractErrorText(payload) } };",
  "  }",
  "  const runningExec = runningExecs.find((row) => String(row?.workflowId || '') === String(source.workflowId || '')) || null;",
  "  const execs = [...payload.data].sort((a, b) => new Date(b.startedAt || 0) - new Date(a.startedAt || 0));",
  "  const refExec = source.hasScheduleTrigger ? (execs.find((row) => row.mode !== 'manual') || execs[0] || null) : (execs[0] || null);",
  "  const base = { name: source.workflowName || K.unknown, id: source.workflowId || '', link: source.workflowLink || '', typeText, lastStatus: refExec?.status || K.none, lastRunText: refExec?.startedAt ? toLocalDateTimeString(refExec.startedAt) : K.none, errorDetail: extractErrorDetail(refExec) || K.none };",
  "  if (runningExec) {",
  "    return { json: { ...base, lastStatus: 'running', lastRunText: runningExec?.startedAt ? toLocalDateTimeString(runningExec.startedAt) : base.lastRunText, stateLabel: K.statusNote, reason: K.runningReason, errorDetail: K.none } };",
  "  }",
  "  if (refExec && refExec.status === 'error') {",
  "    return { json: { ...base, stateLabel: K.statusIssue, reason: K.errorExec } };",
  "  }",
  "  if (source.hasScheduleTrigger) {",
  "    if (!refExec) return { json: { ...base, stateLabel: K.statusIssue, reason: K.noExecSchedule } };",
  "    const ageHours = (Date.now() - new Date(refExec.startedAt).getTime()) / 3600000;",
  "    if (!Number.isFinite(ageHours) || ageHours > 72) return { json: { ...base, stateLabel: K.statusIssue, reason: K.oldExecSchedule } };",
  "    return { json: { ...base, stateLabel: K.statusNormal, reason: K.healthyReason } };",
  "  }",
  "  if (!refExec) {",
  "    return { json: { ...base, stateLabel: K.statusNote, reason: K.noExecEvent } };",
  "  }",
  "  return { json: { ...base, stateLabel: K.statusNormal, reason: K.healthyReason } };",
  "});",
  "return statuses;",
].join('\n');

const buildPayloadCode = [
  "const holiday = $('Determine Holiday').first()?.json ?? {};",
  "const workflowStatuses = $input.all().map((item) => item.json).filter(Boolean).sort((a, b) => String(a.name || '').localeCompare(String(b.name || '')));",
  "const vacationItems = $('Vacation Calendar').all();",
  "const people = [",
  "  { name: '\\uAE40\\uC9C4\\uC6B1', email: 'jwkim@vms-solutions.com' },",
  "  { name: '\\uAE40\\uBBFC\\uC601', email: 'mykim@vms-solutions.com' },",
  "  { name: '\\uC870\\uD604\\uC7AC', email: 'jyi30@vms-solutions.com' },",
  "];",
  "const K = {",
  "  none: '\\uC5C6\\uC74C',",
  "  normalTitle: 'Active \\uC6CC\\uD06C\\uD50C\\uB85C\\uC6B0 \\uC0C1\\uD0DC \\uC810\\uAC80 \\uACB0\\uACFC \\uC815\\uC0C1\\uC785\\uB2C8\\uB2E4.',",
  "  warnTitle: '\\uD655\\uC778\\uC774 \\uD544\\uC694\\uD55C Active \\uC6CC\\uD06C\\uD50C\\uB85C\\uC6B0\\uAC00 \\uC788\\uC2B5\\uB2C8\\uB2E4.',",
  "  checkedCount: '\\uC810\\uAC80 \\uB300\\uC0C1',",
  "  normalCount: '\\uC815\\uC0C1',",
  "  issueCount: '\\uC2E4\\uD328/\\uC624\\uB958',",
  "  noteCount: '\\uCC38\\uACE0',",
  "  vacationUsers: '\\uD734\\uAC00\\uC790',",
  "  alertTargets: '\\uC54C\\uB9BC \\uB300\\uC0C1',",
  "  checkedAt: '\\uC810\\uAC80 \\uC2DC\\uAC01',",
  "  lastStatus: '\\uB9C8\\uC9C0\\uB9C9 \\uC0C1\\uD0DC',",
  "  lastRun: '\\uB9C8\\uC9C0\\uB9C9 \\uC2E4\\uD589',",
  "  triggerType: '\\uC720\\uD615',",
  "  reason: '\\uD310\\uC815 \\uC0AC\\uC720',",
  "  errorDetail: '\\uC624\\uB958 \\uB0B4\\uC6A9',",
  "  workflowStatus: '\\uC6CC\\uD06C\\uD50C\\uB85C\\uC6B0\\uBCC4 \\uC0C1\\uD0DC',",
  "  healthySummary: '\\uC815\\uC0C1 \\uC694\\uC57D',",
  "  issueSummary: '\\uC2E4\\uD328/\\uC624\\uB958 \\uC694\\uC57D',",
  "  noteSummary: '\\uCC38\\uACE0 \\uC694\\uC57D',",
  "  statusNormal: '\\uC815\\uC0C1',",
  "  statusIssue: '\\uC774\\uC0C1',",
  "  statusNote: '\\uCC38\\uACE0',",
  "};",
  "function normalize(value) { return String(value ?? '').normalize('NFC').replace(/\\s+/g, '').toLowerCase(); }",
  "function contains(value, keyword) { return normalize(value).includes(normalize(keyword)); }",
  "function collectStrings(value, out = [], depth = 0) {",
  "  if (depth > 10 || value == null) return out;",
  "  if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') { out.push(String(value)); return out; }",
  "  if (Array.isArray(value)) { for (const item of value) collectStrings(item, out, depth + 1); return out; }",
  "  if (typeof value === 'object') { for (const nested of Object.values(value)) collectStrings(nested, out, depth + 1); }",
  "  return out;",
  "}",
  "function isVacationText(text) { return ['\\uD734\\uAC00','\\uC5F0\\uCC28','\\uBC18\\uCC28','\\uC624\\uC804\\uBC18\\uCC28','\\uC624\\uD6C4\\uBC18\\uCC28','\\uC548\\uC2DD\\uC6D4','\\uACF5\\uAC00','\\uACF5\\uD734\\uC77C','\\uD734\\uC77C','vacation','leave','pto','dayoff','off'].some((keyword) => contains(text, keyword)); }",
  "function ymd(text) { const match = String(text ?? '').match(/\\d{4}-\\d{2}-\\d{2}/); return match ? match[0] : ''; }",
  "function ymds(text) { return String(text ?? '').match(/\\d{4}-\\d{2}-\\d{2}/g) || []; }",
  "function ranges(item) {",
  "  const found = [];",
  "  const uniq = new Set();",
  "  function push(label, start, end) {",
  "    const s = ymd(start);",
  "    const e = ymd(end || start);",
  "    if (!s) return;",
  "    const key = label + '|' + s + '|' + e;",
  "    if (uniq.has(key)) return;",
  "    uniq.add(key);",
  "    found.push({ start: s, end: e || s });",
  "  }",
  "  function walk(value, label, depth) {",
  "    if (depth > 8 || value == null) return;",
  "    if (typeof value === 'string') { const items = ymds(value); if (items.length === 1) push(label, items[0], items[0]); if (items.length >= 2) push(label, items[0], items[1]); return; }",
  "    if (typeof value === 'number' || typeof value === 'boolean') return;",
  "    if (Array.isArray(value)) { value.forEach((item, idx) => walk(item, label + '[' + idx + ']', depth + 1)); return; }",
  "    if (typeof value === 'object') {",
  "      if ('start' in value && ymd(value.start)) push(label + '.start', value.start, value.end || value.start);",
  "      if ('date' in value && value.date && typeof value.date === 'object' && ymd(value.date.start)) push(label + '.date', value.date.start, value.date.end || value.date.start);",
  "      if ('property_date' in value && value.property_date && typeof value.property_date === 'object' && ymd(value.property_date.start)) push(label + '.property_date', value.property_date.start, value.property_date.end || value.property_date.start);",
  "      for (const [key, nested] of Object.entries(value)) walk(nested, label + '.' + key, depth + 1);",
  "    }",
  "  }",
  "  walk(item?.json ?? item, 'root', 0);",
  "  return found;",
  "}",
  "function toLocalDateTimeString(isoString) {",
  "  if (!isoString) return K.none;",
  "  const date = new Date(isoString);",
  "  if (Number.isNaN(date.getTime())) return String(isoString ?? K.none);",
  "  const pad = (value) => String(value).padStart(2, '0');",
  "  return date.getFullYear() + '-' + pad(date.getMonth() + 1) + '-' + pad(date.getDate()) + ' ' + pad(date.getHours()) + ':' + pad(date.getMinutes()) + ':' + pad(date.getSeconds()) + ' KST';",
  "}",
  "const today = String(holiday.today_date || $('Weekday Baseline').first()?.json?.todayDate || '');",
  "const checkedAtText = toLocalDateTimeString(new Date().toISOString());",
  "const isHoliday = !!holiday.is_holiday;",
  "const vacationLookupFailed = vacationItems.some((item) => item?.json?.error);",
  "const todayVacationItems = vacationLookupFailed ? [] : vacationItems.filter((item) => { const text = collectStrings(item?.json ?? item).join(' '); if (!isVacationText(text)) return false; const itemRanges = ranges(item); return itemRanges.length > 0 && itemRanges.some((range) => range.start <= today && today <= range.end); });",
  "const vacationUsers = people.filter((person) => todayVacationItems.some((item) => { const text = collectStrings(item?.json ?? item).join(' '); return contains(text, person.name) || contains(text, person.email); }));",
  "const vacationSet = new Set(vacationUsers.map((person) => person.email));",
  "const activeUsers = people.filter((person) => !vacationSet.has(person.email));",
  "const workflowStatusesWithVacation = vacationLookupFailed",
  "  ? [{ name: '\\uD734\\uAC00 \\uC815\\uBCF4 \\uC870\\uD68C \\uC2E4\\uD328', id: '', link: '', typeText: '\\uD655\\uC778 \\uBD88\\uAC00', lastStatus: '\\uD655\\uC778 \\uBD88\\uAC00', lastRunText: '\\uC5C6\\uC74C', stateLabel: K.statusIssue, reason: '\\uD734\\uAC00\\uC790 \\uC81C\\uC678 \\uC5C6\\uC774 \\uC804\\uC6D0 \\uB300\\uC0C1 \\uAE30\\uC900\\uC73C\\uB85C \\uCC98\\uB9AC\\uD588\\uC2B5\\uB2C8\\uB2E4.', errorDetail: K.none }, ...workflowStatuses]",
  "  : workflowStatuses;",
  "const healthy = workflowStatusesWithVacation.filter((item) => item.stateLabel === K.statusNormal);",
  "const issues = workflowStatusesWithVacation.filter((item) => item.stateLabel === K.statusIssue);",
  "const notes = workflowStatusesWithVacation.filter((item) => item.stateLabel === K.statusNote);",
  "const healthyNames = healthy.filter((item) => item.id).map((item) => item.name);",
  "const issueNames = issues.filter((item) => item.id).map((item) => item.name);",
  "const noteNames = notes.filter((item) => item.id).map((item) => item.name);",
  "const activeWorkflowCount = workflowStatuses.filter((item) => item.id).length;",
  "const hasProblem = issues.length > 0;",
  "function bulletLines(items, formatter, emptyText) {",
  "  if (!items.length) return emptyText;",
  "  return items.map((item) => '* ' + formatter(item)).join('\\n');",
  "}",
  "const teamsEntities = hasProblem ? activeUsers.map((person) => ({ type: 'mention', text: '<at>' + person.name + '</at>', mentioned: { id: person.email, name: person.name } })) : [];",
  "const teamsText = hasProblem ? activeUsers.map((person) => '<at>' + person.name + '</at>').join(', ') : '';",
  "const titleText = hasProblem ? (teamsText ? '\\u26A0\\uFE0F ' + teamsText + ' \\uB2D8, ' + K.warnTitle : '\\u26A0\\uFE0F ' + K.warnTitle) : '\\u2705 ' + K.normalTitle;",
  "const healthyText = K.healthySummary + ': ' + String(healthyNames.length) + '\\uAC74\\n' + bulletLines(healthy.filter((item) => item.id), (item) => item.name + '(' + (item.lastRunText || K.none) + ')', '* ' + K.none);",
  "const issueText = K.issueSummary + ': ' + String(issueNames.length) + '\\uAC74\\n' + bulletLines(issues.filter((item) => item.id), (item) => '[' + item.name + '](' + item.link + '): ' + (item.errorDetail && item.errorDetail !== K.none ? item.errorDetail : item.reason || K.none), '* ' + K.none);",
  "const noteText = K.noteSummary + ': ' + String(noteNames.length) + '\\uAC74\\n' + bulletLines(notes.filter((item) => item.id), (item) => item.name + ': ' + (item.reason || K.none), '* ' + K.none);",
  "const cardBody = [",
  "  { type: 'TextBlock', text: titleText, weight: 'Bolder', size: 'Medium', wrap: true },",
  "  { type: 'FactSet', facts: [",
  "    { title: K.checkedCount, value: String(activeWorkflowCount) + '\\uAC74' },",
  "    { title: K.normalCount, value: String(healthyNames.length) + '\\uAC74' },",
  "    { title: K.issueCount, value: String(issueNames.length) + '\\uAC74' },",
  "    { title: K.noteCount, value: String(noteNames.length) + '\\uAC74' },",
  "    { title: K.vacationUsers, value: vacationUsers.length > 0 ? vacationUsers.map((person) => person.name).join(', ') : K.none },",
  "    { title: K.alertTargets, value: hasProblem ? (activeUsers.length > 0 ? activeUsers.map((person) => person.name).join(', ') : K.none) : K.none },",
  "    { title: K.checkedAt, value: checkedAtText },",
  "  ] },",
  "  { type: 'TextBlock', text: healthyText, wrap: true, spacing: 'Medium' },",
  "  { type: 'TextBlock', text: issueText, wrap: true, spacing: 'Small', color: hasProblem ? 'Attention' : 'Default' },",
  "  { type: 'TextBlock', text: noteText, wrap: true, spacing: 'Small', isSubtle: true },",
  "];",
  "return [{ json: { issueCount: issueNames.length, teamsEntities, cardBody, skipSend: isHoliday, debug: { isHoliday, holidayName: holiday.holiday_name || '', holidayLookupSource: holiday.holiday_lookup_source || '', holidayDbError: holiday.db_error || '' } } }];",
].join('\n');

const workflow = {
  name: 'Check-Active-Workflow',
  nodes: [
    scheduleNode(),
    {
      parameters: {
        resource: 'databasePage',
        operation: 'getAll',
        databaseId: {
          __rl: true,
          value: '205cb995-8309-80e4-ac2a-c8589a1783eb',
          mode: 'list',
          cachedResultName: 'TS Calendar DB',
          cachedResultUrl: 'https://www.notion.so/205cb995830980e4ac2ac8589a1783eb',
        },
        options: {
          sort: {
            sortValue: [{ key: 'Date|date', direction: 'descending' }],
          },
        },
      },
      type: 'n8n-nodes-base.notion',
      typeVersion: 2.2,
      position: [-680, 0],
      id: '892213b5-4525-4dd7-b8e5-7d36c6d859aa',
      name: 'Vacation Calendar',
      onError: 'continueRegularOutput',
      credentials: {
        notionApi: NOTION_CREDENTIAL,
      },
    },
    {
      parameters: { jsCode: weekdayBaselineCode },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [-680, -160],
      id: '78a09190-f145-4ee4-aa98-98749cb4ff0f',
      name: 'Weekday Baseline',
      alwaysOutputData: true,
    },
    {
      parameters: {
        operation: 'executeQuery',
        query:
          "=DECLARE @d DATE = CAST('{{ $('Weekday Baseline').item.json.todayDate }}' AS date);\nSELECT\n    CONVERT(VARCHAR(8), @d, 112) AS check_date,\n    CAST(CASE WHEN EXISTS (\n        SELECT 1\n        FROM TsMgmt.dbo.HolidayCalendarKR\n        WHERE HolidayDate = @d\n    ) THEN 1 ELSE 0 END AS bit) AS found_in_db,\n    ISNULL((SELECT TOP 1 HolidayName FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), '') AS holiday_name,\n    ISNULL((SELECT TOP 1 SourceType FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), '') AS source_type,\n    ISNULL((SELECT TOP 1 SourceYear FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), 0) AS source_year;",
      },
      type: 'n8n-nodes-base.microsoftSql',
      typeVersion: 1.1,
      position: [-420, -160],
      id: 'e0e11648-202a-432f-a279-15e7af9c69dc',
      name: 'Holiday DB Fallback',
      alwaysOutputData: true,
      onError: 'continueRegularOutput',
      credentials: {
        microsoftSql: {
          id: '2dZb5OQPbTyO3052',
          name: 'TsMgmt(DevTest_SQL2022_26)',
        },
      },
    },
    {
      parameters: {
        jsCode: determineHolidayCode,
      },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [-160, -160],
      id: '801f6f08-a46d-4a99-a77b-c1d0ee601875',
      name: 'Determine Holiday',
      alwaysOutputData: true,
    },
    {
      parameters: {
        method: 'GET',
        url: `${N8N_BASE_URL}/api/v1/workflows?limit=250`,
        sendHeaders: true,
        headerParameters: {
          parameters: requestHeaders(),
        },
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.2,
      position: [-680, 220],
      id: '5d5332d2-9d9f-4958-b96f-9c8afcfb8696',
      name: 'Fetch Active Workflows',
      onError: 'continueRegularOutput',
      alwaysOutputData: true,
    },
    {
      parameters: {
        mode: 'runOnceForAllItems',
        jsCode: expandActiveWorkflowsCode,
      },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [-420, 220],
      id: 'bc9f130a-6d34-4dfb-b07a-8e1f16ef5b12',
      name: 'Expand Active Workflows',
      alwaysOutputData: true,
    },
    {
      parameters: {
        method: 'GET',
        url: "={{ $json.workflowId ? $json.executionUrl : $json.fallbackUrl }}",
        sendHeaders: true,
        headerParameters: {
          parameters: requestHeaders(),
        },
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.2,
      position: [-160, 220],
      id: '6d5806e6-e3b8-411c-9f1f-8a56b183851a',
      name: 'Fetch Latest Executions',
      onError: 'continueRegularOutput',
      alwaysOutputData: true,
    },
    {
      parameters: {
        method: 'GET',
        url: `${N8N_BASE_URL}/api/v1/executions?limit=250&status=running`,
        sendHeaders: true,
        headerParameters: {
          parameters: requestHeaders(),
        },
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.2,
      position: [-160, 60],
      id: 'eac04317-4d31-4540-b9fd-e1676a3681bd',
      name: 'Fetch Running Executions',
      onError: 'continueRegularOutput',
      alwaysOutputData: true,
    },
    {
      parameters: {
        mode: 'runOnceForAllItems',
        jsCode: normalizeStatusCode,
      },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [100, 220],
      id: 'd1039f9a-cde2-4490-a838-6c1d85020fdd',
      name: 'Normalize Workflow Status',
      alwaysOutputData: true,
    },
    {
      parameters: {
        mode: 'runOnceForAllItems',
        jsCode: buildPayloadCode,
      },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [360, 220],
      id: '7cfe4c5f-5638-49d6-b3ce-3ce7cbbd0178',
      name: 'Build Monitor Payload',
      alwaysOutputData: true,
    },
    {
      parameters: {
        conditions: {
          options: { caseSensitive: true, leftValue: '', typeValidation: 'strict', version: 2 },
          conditions: [
            {
              id: '00f6ecc7-5dad-4f29-81ab-a5d305485d24',
              leftValue: '={{ $json.skipSend !== true }}',
              rightValue: true,
              operator: { type: 'boolean', operation: 'equals' },
            },
          ],
          combinator: 'and',
        },
        options: {},
      },
      type: 'n8n-nodes-base.if',
      typeVersion: 2.2,
      position: [620, 220],
      id: '5f8a756b-df4c-48dd-a5d7-5702104380c3',
      name: 'Should Send Monitor',
      alwaysOutputData: false,
    },
    {
      parameters: {
        method: 'POST',
        url: MONITOR_WEBHOOK,
        sendBody: true,
        contentType: 'json',
        specifyBody: 'json',
        bodyParameters: { parameters: [{}] },
        jsonBody: "={{ ({ type: 'message', attachments: [{ contentType: 'application/vnd.microsoft.card.adaptive', content: { type: 'AdaptiveCard', body: Array.isArray($json.cardBody) ? $json.cardBody : [], msteams: { entities: Array.isArray($json.teamsEntities) ? $json.teamsEntities : [] }, '$schema': 'http://adaptivecards.io/schemas/adaptive-card.json', version: '1.4' } }] }) }}",
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.3,
      position: [880, 220],
      id: '0d0dd0d4-aa5d-4f78-8cd0-b2db06efbc6d',
      name: 'Monitor Teams Webhook',
      alwaysOutputData: false,
    },
  ],
  connections: {
    'Health Schedule': {
      main: [[
        { node: 'Vacation Calendar', type: 'main', index: 0 },
        { node: 'Weekday Baseline', type: 'main', index: 0 },
        { node: 'Fetch Active Workflows', type: 'main', index: 0 },
      ]],
    },
    'Weekday Baseline': {
      main: [[{ node: 'Holiday DB Fallback', type: 'main', index: 0 }]],
    },
    'Holiday DB Fallback': {
      main: [[{ node: 'Determine Holiday', type: 'main', index: 0 }]],
    },
    'Fetch Active Workflows': {
      main: [[{ node: 'Expand Active Workflows', type: 'main', index: 0 }]],
    },
    'Expand Active Workflows': {
      main: [[
        { node: 'Fetch Latest Executions', type: 'main', index: 0 },
        { node: 'Fetch Running Executions', type: 'main', index: 0 },
      ]],
    },
    'Fetch Latest Executions': {
      main: [[{ node: 'Normalize Workflow Status', type: 'main', index: 0 }]],
    },
    'Fetch Running Executions': {
      main: [[{ node: 'Normalize Workflow Status', type: 'main', index: 1 }]],
    },
    'Normalize Workflow Status': {
      main: [[{ node: 'Build Monitor Payload', type: 'main', index: 0 }]],
    },
    'Build Monitor Payload': {
      main: [[{ node: 'Should Send Monitor', type: 'main', index: 0 }]],
    },
    'Should Send Monitor': {
      main: [[{ node: 'Monitor Teams Webhook', type: 'main', index: 0 }]],
    },
  },
  settings: {
    executionOrder: 'v1',
  },
};

fs.mkdirSync(workflowDir, { recursive: true });
fs.writeFileSync(workflowPath, JSON.stringify(workflow, null, 2) + '\n', 'utf8');
console.log(workflowPath);
