const fs = require('fs');
const path = require('path');

const workflowDir = path.join(process.cwd(), 'workflows', 'License-Approval-Alert');
const workflowPath = path.join(workflowDir, 'License-Approval-Alert_api.json');

const SUPPORT_CREDENTIAL = { id: 'QfudWXK5AulrLxFd', name: 'support' };
const NOTION_CREDENTIAL = { id: 'LrLyYGhPvHMbPfZm', name: 'tsupport API' };
const ALERT_WEBHOOK =
  process.env.TS_LICENSE_ALERT_WEBHOOK || 'https://redacted.invalid/powerautomate/license-approval-webhook';
const LICENSE_MANAGE_URL = 'http://192.168.1.17/view/8B521E26-8B31-0EA5-0AC3-3B40CE4BDBAB/21616A03-5394-067D-BAFD-1F00637BFF9E/lms';

function scheduleNode(name, expressions, position, id) {
  return {
    parameters: {
      rule: {
        interval: expressions.map((expression) => ({
          field: 'cronExpression',
          expression,
        })),
      },
    },
    type: 'n8n-nodes-base.scheduleTrigger',
    typeVersion: 1.3,
    position,
    id,
    name,
    alwaysOutputData: true,
  };
}

function codeNode(name, jsCode, position, id) {
  return {
    parameters: { jsCode },
    type: 'n8n-nodes-base.code',
    typeVersion: 2,
    position,
    id,
    name,
    alwaysOutputData: true,
  };
}

function outlookHttpNode(name, url, position, id) {
  return {
    parameters: {
      url,
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'microsoftOutlookOAuth2Api',
      options: {},
    },
    type: 'n8n-nodes-base.httpRequest',
    typeVersion: 4.3,
    position,
    id,
    name,
    alwaysOutputData: true,
    onError: 'continueRegularOutput',
    credentials: {
      microsoftOutlookOAuth2Api: SUPPORT_CREDENTIAL,
    },
  };
}

function codeNodeOnce(name, jsCode, position, id) {
  return {
    parameters: {
      mode: 'runOnceForAllItems',
      jsCode,
    },
    type: 'n8n-nodes-base.code',
    typeVersion: 2,
    position,
    id,
    name,
    alwaysOutputData: true,
  };
}

const weekdayBaselineCode = [
  'const now = new Date();',
  'const pad = (value) => String(value).padStart(2, "0");',
  'const weekdayNames = ["\\uC77C\\uC694\\uC77C", "\\uC6D4\\uC694\\uC77C", "\\uD654\\uC694\\uC77C", "\\uC218\\uC694\\uC77C", "\\uBAA9\\uC694\\uC77C", "\\uAE08\\uC694\\uC77C", "\\uD1A0\\uC694\\uC77C"];',
  'const year = String(now.getFullYear());',
  'const month = pad(now.getMonth() + 1);',
  'const day = pad(now.getDate());',
  'const weekdayIndex = now.getDay();',
  'const isWeekend = weekdayIndex === 0 || weekdayIndex === 6;',
  'return [{',
  '  json: {',
  '    todayDate: `${year}-${month}-${day}`,',
  '    todayInt: `${year}${month}${day}`,',
  '    todayMMDD: `${month}${day}`,',
  '    WeekdayName: weekdayNames[weekdayIndex],',
  '    IsWeekend: isWeekend,',
  '    DefaultIsHoliday: isWeekend,',
  "    DefaultHolidayName: isWeekend ? '\\uC8FC\\uB9D0' : '\\uD3C9\\uC77C',",
  '  }',
  '}];',
].join('\n');

const determineHolidayCode = [
  "const baseline = $('Weekday Baseline').first()?.json ?? {};",
  "const dbPayload = $('Holiday DB Fallback').first()?.json ?? {};",
  "const dbFound = !dbPayload.error && [true, 1, '1', 'true'].includes(dbPayload.found_in_db);",
  'let isHoliday = !!baseline.DefaultIsHoliday;',
  "let holidayName = baseline.DefaultHolidayName || (isHoliday ? '\\uC8FC\\uB9D0' : '\\uD3C9\\uC77C');",
  "let holidayLookupSource = isHoliday ? 'default-weekend' : 'default-weekday';",
  'if (dbFound) {',
  '  isHoliday = true;',
  "  holidayName = String(dbPayload.holiday_name || '\\uACF5\\uD734\\uC77C');",
  "  holidayLookupSource = dbPayload.source_type ? `db:${dbPayload.source_type}` : 'db';",
  '}',
  'return [{',
  '  json: {',
  '    today_date: baseline.todayDate || "",',
  '    is_holiday: isHoliday,',
  '    holiday_name: holidayName,',
  '    holiday_lookup_source: holidayLookupSource,',
  '    is_weekend: !!baseline.IsWeekend,',
  "    db_error: dbPayload.error || '',",
  '  }',
  '}];',
].join('\n');

const resolveFolderCode = [
  "const raw = $('Inbox Child Folders').first()?.json ?? {};",
  'const folders = Array.isArray(raw.value) ? raw.value : [];',
  "const targetName = '01. \\uB77C\\uC774\\uC120\\uC2A4 \\uC694\\uCCAD';",
  "const normalize = (value) => String(value ?? '').normalize('NFC').replace(/\\\\s+/g, '').toLowerCase();",
  'const target = folders.find((folder) => normalize(folder.displayName) === normalize(targetName));',
  'return [{ json: {',
  '  folderFound: Boolean(target),',
  "  folderId: target?.id || '',",
  "  folderName: target?.displayName || '',",
  '  folderError: raw.error?.message || raw.error?.description || raw.error || "",',
  '} }];',
].join('\n');

const buildPayloadCode = [
  "const holiday = $('Determine Holiday').first()?.json ?? {};",
  "const folderInfo = $('Resolve License Folder').first()?.json ?? {};",
  "const inboxPayload = $('Inbox Messages').first()?.json ?? {};",
  "const folderPayload = $('License Folder Messages').first()?.json ?? {};",
  "const vacationItems = $('Vacation Calendar').all();",
  '',
  'const K = {',
  "  approval: '\\uC2B9\\uC778\\uD544\\uC694',",
  "  folderName: '01. \\uB77C\\uC774\\uC120\\uC2A4 \\uC694\\uCCAD',",
  "  license1: '\\uB77C\\uC774\\uC120\\uC2A4',",
  "  license2: 'license',",
  "  license3: '\\uB77C\\uC774\\uC13C\\uC2A4',",
  "  vacation1: '\\uD734\\uAC00',",
  "  vacation2: '\\uC5F0\\uCC28',",
  "  vacation3: '\\uBC18\\uCC28',",
  "  vacation4: '\\uC624\\uC804\\uBC18\\uCC28',",
  "  vacation5: '\\uC624\\uD6C4\\uBC18\\uCC28',",
  "  vacation6: '\\uC548\\uC2DD\\uC6D4',",
  "  vacation7: '\\uACF5\\uAC00',",
  "  vacation8: '\\uACF5\\uD734\\uC77C',",
  "  vacation9: '\\uD734\\uC77C',",
  "  applicantTag: '\\uC2E0\\uCCAD\\uC790:',",
  "  componentTag: '\\uBC1C\\uAE09 \\uBC1B\\uC744 Component:',",
  "  machineTag: '\\uB77C\\uC774\\uC120\\uC2A4 \\uC778\\uC99D \\uB418\\uB294 PC\\uC758 MAC \\uC8FC\\uC18C \\uB610\\uB294 \\uCEF4\\uD4E8\\uD130 \\uC774\\uB984:',",
  "  productTag: '\\uBC1C\\uAE09 \\uBC1B\\uC744 \\uC81C\\uD488:',",
  "  titleAlert: '\\uD655\\uC778\\uC774 \\uD544\\uC694\\uD55C \\uB77C\\uC774\\uC120\\uC2A4 \\uC694\\uCCAD \\uBA54\\uC77C\\uC774 \\uC788\\uC2B5\\uB2C8\\uB2E4.',",
  "  factRecipients: '\\uC54C\\uB9BC \\uB300\\uC0C1',",
  "  factVacation: '\\uD734\\uAC00\\uC790',",
  "  factRequestCount: '\\uB77C\\uC774\\uC120\\uC2A4 \\uC694\\uCCAD',",
  "  factApplicant: '\\uBCF4\\uB0B8\\uC0AC\\uB78C',",
  "  factComponent: '\\uBC1C\\uD589\\uC81C\\uD488',",
  "  factQuantity: '\\uBC1C\\uD589\\uC218\\uB7C9',",
  "  factReceived: '\\uC218\\uC2E0\\uC2DC\\uAC01',",
  "  linkText: '\\uB77C\\uC774\\uC120\\uC2A4 \\uAD00\\uB9AC \\uD398\\uC774\\uC9C0\\uB85C \\uC774\\uB3D9',",
  "  none: '\\uC5C6\\uC74C',",
  "  unknown: '\\uD655\\uC778 \\uBD88\\uAC00',",
  '};',
  '',
  'const people = [',
  "  { name: '\\uAE40\\uC9C4\\uC6B1', email: 'jwkim@vms-solutions.com' },",
  "  { name: '\\uAE40\\uBBFC\\uC601', email: 'mykim@vms-solutions.com' },",
  "  { name: '\\uC870\\uD604\\uC7AC', email: 'jyi30@vms-solutions.com' },",
  '];',
  '',
  'const recentWindowMs = 7 * 24 * 60 * 60 * 1000;',
  `const fallbackManageUrl = ${JSON.stringify(LICENSE_MANAGE_URL)};`,
  '',
  "function normalize(value) { return String(value ?? '').normalize('NFC').replace(/\\\\s+/g, '').toLowerCase(); }",
  "function contains(value, keyword) { return normalize(value).includes(normalize(keyword)); }",
  'function arr(value) { return Array.isArray(value) ? value : []; }',
  "function distinct(values) { return [...new Set(values.filter(Boolean))]; }",
  "function isCompleted(flagStatus) { return flagStatus === 'complete' || flagStatus === 'completed'; }",
  "function recent(row) { const ts = Date.parse(row?.receivedDateTime || ''); return Number.isFinite(ts) && ts >= (Date.now() - recentWindowMs); }",
  "function alertable(row) { const status = row?.flag?.flagStatus ?? ''; return contains(row?.subject, K.approval) && (row?.isRead === false || (row?.isRead === true && !isCompleted(status))); }",
  'function decode(html) {',
  "  return String(html ?? '')",
  "    .replace(/&nbsp;/gi, ' ')",
  "    .replace(/&amp;/gi, '&')",
  "    .replace(/&lt;/gi, '<')",
  "    .replace(/&gt;/gi, '>')",
  "    .replace(/&quot;/gi, '\"')",
  "    .replace(/&#39;/g, \"'\")",
  "    .replace(/&#(\\\\d+);/g, (_, code) => String.fromCodePoint(Number(code)))",
  "    .replace(/&#x([0-9a-f]+);/gi, (_, code) => String.fromCodePoint(parseInt(code, 16)));",
  '}',
  'function htmlToText(html) {',
  "  return decode(String(html ?? '')",
  "    .replace(/<br[^>]*>/gi, '\\n')",
  "    .replace(/<\\/p>/gi, '\\n')",
  "    .replace(/<\\/div>/gi, '\\n')",
  "    .replace(/<[^>]+>/g, ' '))",
  "    .replace(/\\\\r/g, '')",
  "    .replace(/\\n{3,}/g, '\\n\\n')",
  "    .trim();",
  '}',
  "function getField(line, label) { const match = String(line ?? '').match(new RegExp(label + '\\\\s*:\\\\s*(.+)$', 'i')); return match ? match[1].trim() : ''; }",
  'function parseEntries(html) {',
  "  const blocks = htmlToText(html).split(/={5,}/).map((block) => block.trim()).filter(Boolean);",
  '  const entries = [];',
  '  for (const block of blocks) {',
  "    const lines = block.split('\\n').map((line) => line.trim()).filter(Boolean);",
  "    const applicantLine = lines.find((line) => line.includes(K.applicantTag)) || '';",
  "    const componentLine = lines.find((line) => line.includes(K.componentTag)) || '';",
  "    const machineLine = lines.find((line) => line.includes(K.machineTag)) || '';",
  "    const productLine = lines.find((line) => line.includes(K.productTag)) || '';",
  "    const applicantMatch = applicantLine.match(/\\uC2E0\\uCCAD\\uC790:\\s*([^\\)\\]\\s]+)/);",
  "    const applicant = applicantMatch ? applicantMatch[1].trim() : '';",
  "    const component = getField(componentLine, K.componentTag.replace(':', ''));",
  "    const machine = getField(machineLine, K.machineTag.replace(':', ''));",
  "    const product = getField(productLine, K.productTag.replace(':', ''));",
  '    if (applicant || component || machine || product) entries.push({ applicant, component, machine, product });',
  '  }',
  '  return entries;',
  '}',
  'function extractManageUrl(html, webLink) {',
  "  const match = String(html ?? '').match(/href=\"(http:\\/\\/192\\.168\\.1\\.17[^\"]+)\"/i);",
  "  return match ? match[1] : (fallbackManageUrl || webLink || '');",
  '}',
  'function toLocalString(isoString) {',
  "  if (!isoString) return '';",
  '  const date = new Date(isoString);',
  "  if (Number.isNaN(date.getTime())) return String(isoString ?? '');",
  '  const pad = (value) => String(value).padStart(2, "0");',
  '  return date.getFullYear() + \'-\' + pad(date.getMonth() + 1) + \'-\' + pad(date.getDate()) + \' \' + pad(date.getHours()) + \':\' + pad(date.getMinutes()) + \':\' + pad(date.getSeconds()) + \' KST\';',
  '}',
  'function mapCandidate(row) {',
  "  const entries = parseEntries(row.body?.content || '');",
  '  const applicants = distinct(entries.map((entry) => entry.applicant));',
  '  const components = distinct(entries.map((entry) => entry.component));',
  '  const machines = distinct(entries.map((entry) => entry.machine));',
  "  const component = components[0] || '';",
  '  const groupedMachines = component ? distinct(entries.filter((entry) => entry.component === component).map((entry) => entry.machine)) : machines;',
  '  return {',
  "    id: row.internetMessageId || row.id,",
  "    subject: row.subject || '(no subject)',",
  "    applicantText: applicants.join(', ') || row.from?.emailAddress?.name || row.from?.emailAddress?.address || K.unknown,",
  "    productText: (component || components.join(', ') || K.unknown) + (entries[0]?.product ? ' (' + entries[0].product + ')' : ''),",
  "    quantityText: String(groupedMachines.length || machines.length || 1),",
  "    receivedDateTime: row.receivedDateTime || '',",
  '    receivedText: toLocalString(row.receivedDateTime),',
  "    manageUrl: extractManageUrl(row.body?.content || '', row.webLink || ''),",
  '  };',
  '}',
  '',
  'const inboxRows = inboxPayload.error ? [] : arr(inboxPayload.value);',
  'const folderRows = folderPayload.error ? [] : arr(folderPayload.value);',
  '',
  'const inboxMatches = inboxRows',
  '  .filter((row) => recent(row))',
  "  .filter((row) => [K.license1, K.license2, K.license3].some((keyword) => contains((row.subject || '') + ' ' + (row.body?.content || '') + ' ' + (row.bodyPreview || ''), keyword)))",
  '  .filter((row) => alertable(row))',
  '  .map((row) => mapCandidate(row));',
  '',
  'const folderMatches = folderRows',
  '  .filter((row) => recent(row))',
  '  .filter((row) => alertable(row))',
  '  .map((row) => mapCandidate(row));',
  '',
  'const deduped = [];',
  'const seen = new Set();',
  'for (const item of [...folderMatches, ...inboxMatches]) {',
  "  const key = item.id || item.subject + '|' + item.receivedDateTime;",
  '  if (seen.has(key)) continue;',
  '  seen.add(key);',
  '  deduped.push(item);',
  '}',
  "deduped.sort((a, b) => new Date(b.receivedDateTime || 0) - new Date(a.receivedDateTime || 0));",
  '',
  'function collectStrings(value, out = [], depth = 0) {',
  '  if (depth > 10 || value == null) return out;',
  "  if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') { out.push(String(value)); return out; }",
  '  if (Array.isArray(value)) { for (const item of value) collectStrings(item, out, depth + 1); return out; }',
  "  if (typeof value === 'object') { for (const nested of Object.values(value)) collectStrings(nested, out, depth + 1); }",
  '  return out;',
  '}',
  "function ymds(text) { return String(text ?? '').match(/\\d{4}-\\d{2}-\\d{2}/g) || []; }",
  "function ymd(text) { const match = String(text ?? '').match(/\\d{4}-\\d{2}-\\d{2}/); return match ? match[0] : ''; }",
  'function ranges(item) {',
  '  const found = [];',
  '  const uniq = new Set();',
  '  function push(label, start, end) {',
  '    const s = ymd(start);',
  '    const e = ymd(end || start);',
  '    if (!s) return;',
  "    const key = label + '|' + s + '|' + e;",
  '    if (uniq.has(key)) return;',
  '    uniq.add(key);',
  '    found.push({ start: s, end: e || s });',
  '  }',
  '  function walk(value, label, depth) {',
  '    if (depth > 8 || value == null) return;',
  "    if (typeof value === 'string') { const items = ymds(value); if (items.length === 1) push(label, items[0], items[0]); if (items.length >= 2) push(label, items[0], items[1]); return; }",
  "    if (typeof value === 'number' || typeof value === 'boolean') return;",
  '    if (Array.isArray(value)) { value.forEach((item, idx) => walk(item, label + "[" + idx + "]", depth + 1)); return; }',
  "    if (typeof value === 'object') {",
  "      if ('start' in value && ymd(value.start)) push(label + '.start', value.start, value.end || value.start);",
  "      if ('date' in value && value.date && typeof value.date === 'object' && ymd(value.date.start)) push(label + '.date', value.date.start, value.date.end || value.date.start);",
  "      if ('property_date' in value && value.property_date && typeof value.property_date === 'object' && ymd(value.property_date.start)) push(label + '.property_date', value.property_date.start, value.property_date.end || value.property_date.start);",
  '      for (const [key, nested] of Object.entries(value)) walk(nested, label + "." + key, depth + 1);',
  '    }',
  '  }',
  "  walk(item?.json ?? item, 'root', 0);",
  '  return found;',
  '}',
  "function isVacationText(text) { return [K.vacation1, K.vacation2, K.vacation3, K.vacation4, K.vacation5, K.vacation6, K.vacation7, K.vacation8, K.vacation9, 'vacation', 'leave', 'pto', 'dayoff', 'off'].some((keyword) => contains(text, keyword)); }",
  "const today = String(holiday.today_date || $('Weekday Baseline').first()?.json?.todayDate || '');",
  'const isHoliday = !!holiday.is_holiday;',
  'const vacationLookupFailed = vacationItems.some((item) => item?.json?.error);',
  'const todayVacationItems = vacationLookupFailed ? [] : vacationItems.filter((item) => {',
  '  const text = collectStrings(item?.json ?? item).join(" ");',
  '  if (!isVacationText(text)) return false;',
  '  const itemRanges = ranges(item);',
  '  return itemRanges.length > 0 && itemRanges.some((range) => range.start <= today && today <= range.end);',
  '});',
  'const vacationUsers = people.filter((person) => todayVacationItems.some((item) => {',
  '  const text = collectStrings(item?.json ?? item).join(" ");',
  '  return contains(text, person.name) || contains(text, person.email);',
  '}));',
  'const vacationSet = new Set(vacationUsers.map((person) => person.email));',
  'const activeUsers = people.filter((person) => !vacationSet.has(person.email));',
  'const teamsEntities = activeUsers.map((person) => ({ type: "mention", text: "<at>" + person.name + "</at>", mentioned: { id: person.email, name: person.name } }));',
  'const teamsText = activeUsers.map((person) => "<at>" + person.name + "</at>").join(", ");',
  '',
  'const warningParts = [',
  '  holiday.db_error ? "\\uACF5\\uD734\\uC77C DB \\uC870\\uD68C \\uC2E4\\uD328: " + String(holiday.db_error) : "",',
  '  folderInfo.folderError || (!folderInfo.folderFound ? "01. \\uB77C\\uC774\\uC120\\uC2A4 \\uC694\\uCCAD \\uD3F4\\uB354\\uB97C \\uCC3E\\uC9C0 \\uBABB\\uD588\\uC2B5\\uB2C8\\uB2E4." : ""),',
  '  inboxPayload.error?.message || inboxPayload.error?.description || inboxPayload.error || "",',
  '  folderPayload.error?.message || folderPayload.error?.description || folderPayload.error || "",',
  '  vacationLookupFailed ? "\\uD734\\uAC00 \\uC815\\uBCF4 \\uC870\\uD68C \\uC2E4\\uD328 \\uC2DC \\uAE30\\uBCF8\\uAC12(\\uC804\\uC6D0 \\uADFC\\uBB34)\\uC73C\\uB85C \\uCC98\\uB9AC\\uD588\\uC2B5\\uB2C8\\uB2E4." : "",',
  '].filter(Boolean);',
  '',
  'const alertCardBody = [];',
  'if (!isHoliday && deduped.length > 0) {',
  '  alertCardBody.push({ type: "TextBlock", text: teamsText ? "\\uD83D\\uDCEC " + teamsText + " \\uB2D8, " + K.titleAlert : "\\uD83D\\uDCEC " + K.titleAlert, weight: "Bolder", size: "Medium", wrap: true });',
  '  alertCardBody.push({ type: "FactSet", facts: [',
  '    { title: K.factRecipients, value: activeUsers.length > 0 ? activeUsers.map((person) => person.name).join(", ") : K.none },',
  '    { title: K.factVacation, value: vacationUsers.length > 0 ? vacationUsers.map((person) => person.name).join(", ") : K.none },',
  '    { title: K.factRequestCount, value: String(deduped.length) + "\\uAC74" },',
  '  ] });',
  '  alertCardBody.push({ type: "TextBlock", text: "-------------------------------------------------", wrap: true, spacing: "Medium", isSubtle: true });',
  '  deduped.forEach((item, index) => {',
  '    alertCardBody.push({ type: "TextBlock", text: item.subject, weight: "Bolder", wrap: true, spacing: index === 0 ? "Medium" : "Large" });',
  '    alertCardBody.push({ type: "FactSet", facts: [',
  '      { title: K.factApplicant, value: item.applicantText },',
  '      { title: K.factComponent, value: item.productText },',
  '      { title: K.factQuantity, value: item.quantityText },',
  '      { title: K.factReceived, value: item.receivedText || item.receivedDateTime || K.unknown },',
  '    ] });',
  '    alertCardBody.push({ type: "TextBlock", text: "-------------------------------------------------", wrap: true, spacing: "Medium", isSubtle: true });',
  '  });',
  '  alertCardBody.push({ type: "TextBlock", text: "[" + K.linkText + "](" + ((deduped[0]?.manageUrl) || fallbackManageUrl) + ")", wrap: true, spacing: "Medium" });',
  '  if (warningParts.length > 0) alertCardBody.push({ type: "TextBlock", text: warningParts.join(" / "), wrap: true, spacing: "Medium", color: "Attention" });',
  '}',
  '',
  'return [{ json: {',
  '  alertCount: isHoliday ? 0 : deduped.length,',
  '  teamsEntities,',
  '  alertCardBody,',
  '  debug: {',
  '    isHoliday,',
  '    holidayName: holiday.holiday_name || "",',
  '    holidayLookupSource: holiday.holiday_lookup_source || "",',
  '  },',
  '} }];',
].join('\n');

const workflow = {
  name: 'License-Approval-Alert',
  nodes: [
    scheduleNode('Alert Schedule', ['0 0 7 * * 1-5', '0 */20 8-16 * * 1-5', '0 0 18 * * 1-5'], [-1160, 0], '5f54525f-b5de-43dd-885d-7fbd1ce508ae'),
    codeNode('Set Alert Mode', "return [{ json: { runMode: 'alert' } }];", [-920, 0], 'b6f33f34-7af7-4b82-a62d-741a4e76db58'),
    codeNode('Weekday Baseline', weekdayBaselineCode, [-680, 220], '24e44449-6709-470a-a621-c570525c0db8'),
    {
      parameters: {
        operation: 'executeQuery',
        query:
          "=DECLARE @d DATE = CAST('{{ $('Weekday Baseline').item.json.todayDate }}' AS date);\nSELECT\n    CONVERT(VARCHAR(8), @d, 112) AS check_date,\n    CAST(CASE WHEN EXISTS (\n        SELECT 1\n        FROM TsMgmt.dbo.HolidayCalendarKR\n        WHERE HolidayDate = @d\n    ) THEN 1 ELSE 0 END AS bit) AS found_in_db,\n    ISNULL((SELECT TOP 1 HolidayName FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), '') AS holiday_name,\n    ISNULL((SELECT TOP 1 SourceType FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), '') AS source_type,\n    ISNULL((SELECT TOP 1 SourceYear FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), 0) AS source_year;",
      },
      type: 'n8n-nodes-base.microsoftSql',
      typeVersion: 1.1,
      position: [-440, 220],
      id: '7f633c02-2932-40e4-b1ca-f54928ae97cf',
      name: 'Holiday DB Fallback',
      alwaysOutputData: true,
      onError: 'continueRegularOutput',
      credentials: {
        microsoftSql: {
          id: '2dZb5OQPbTyO3052',
          name: 'TsMgmt(DevTest_SQL2022_26)',
        },
      },
    },
    codeNode('Determine Holiday', determineHolidayCode, [-200, 220], '6f32c893-403a-413c-91ea-f4b09d32ab48'),
    outlookHttpNode('Inbox Child Folders', 'https://graph.microsoft.com/v1.0/me/mailFolders/inbox/childFolders?$top=200&$select=id,displayName,parentFolderId,childFolderCount,totalItemCount,unreadItemCount', [-680, -120], '47814dff-b354-41ce-a3db-c5985f71effb'),
    codeNode('Resolve License Folder', resolveFolderCode, [-440, -120], '8e6cecfc-11d3-4991-940c-2db4a3d60eca'),
    outlookHttpNode('Inbox Messages', 'https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$top=1000&$orderby=receivedDateTime desc&$select=id,internetMessageId,subject,isRead,flag,receivedDateTime,from,webLink,bodyPreview,body', [-680, 60], '61e96ef4-f68c-4f2e-b4fd-4b6ddfb48ca8'),
    outlookHttpNode('License Folder Messages', "={{ $json.folderId ? 'https://graph.microsoft.com/v1.0/me/mailFolders/' + encodeURIComponent($json.folderId) + '/messages?$top=1000&$orderby=receivedDateTime desc&$select=id,internetMessageId,subject,isRead,flag,receivedDateTime,from,webLink,bodyPreview,body' : 'https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$top=1&$select=id' }}", [-200, -120], 'efd3f4f6-e42c-458f-9c95-e37a0ac1fd46'),
    {
      parameters: {
        resource: 'databasePage',
        operation: 'getAll',
        databaseId: {
          __rl: true,
          value: '205cb995-8309-80e4-ac2a-c8589a1783eb',
          mode: 'list',
          cachedResultName: 'TS Calendar DB',
          cachedResultUrl: 'https://www.notion.so/205cb995830980e4ac2ac8589a1783eb',
        },
        options: {
          sort: {
            sortValue: [{ key: 'Date|date', direction: 'descending' }],
          },
        },
      },
      type: 'n8n-nodes-base.notion',
      typeVersion: 2.2,
      position: [-200, 60],
      id: 'd6589c10-bf2c-4d46-99da-c1ee7570e770',
      name: 'Vacation Calendar',
      onError: 'continueRegularOutput',
      credentials: {
        notionApi: NOTION_CREDENTIAL,
      },
    },
    codeNode('Build Teams Payload', buildPayloadCode, [120, -20], 'e267f131-661d-4dbd-8232-0bd476177880'),
    {
      parameters: {
        conditions: {
          options: { caseSensitive: true, leftValue: '', typeValidation: 'strict', version: 2 },
          conditions: [
            {
              id: '8d3b63f7-1b11-4dd6-a520-6d0998d4ec8d',
              leftValue: '={{ $json.alertCount > 0 }}',
              rightValue: true,
              operator: { type: 'boolean', operation: 'equals' },
            },
          ],
          combinator: 'and',
        },
        options: {},
      },
      type: 'n8n-nodes-base.if',
      typeVersion: 2.2,
      position: [360, -20],
      id: '3ff54e92-6cef-4bb7-a1c7-a5281d01eb2b',
      name: 'Should Send Alert',
    },
    {
      parameters: {
        method: 'POST',
        url: ALERT_WEBHOOK,
        sendBody: true,
        contentType: 'json',
        specifyBody: 'json',
        bodyParameters: { parameters: [{}] },
        jsonBody: "={{ ({ type: 'message', attachments: [{ contentType: 'application/vnd.microsoft.card.adaptive', content: { type: 'AdaptiveCard', body: Array.isArray($json.alertCardBody) ? $json.alertCardBody : [], msteams: { entities: Array.isArray($json.teamsEntities) ? $json.teamsEntities : [] }, '$schema': 'http://adaptivecards.io/schemas/adaptive-card.json', version: '1.4' } }] }) }}",
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.3,
      position: [620, -20],
      id: '780a40fd-a9ea-4819-a64d-a608a22b3db7',
      name: 'Alert Teams Webhook',
      alwaysOutputData: false,
    },
  ],
  connections: {
    'Alert Schedule': {
      main: [[{ node: 'Set Alert Mode', type: 'main', index: 0 }]],
    },
    'Set Alert Mode': {
      main: [[
        { node: 'Weekday Baseline', type: 'main', index: 0 },
        { node: 'Inbox Child Folders', type: 'main', index: 0 },
        { node: 'Inbox Messages', type: 'main', index: 0 },
      ]],
    },
    'Weekday Baseline': {
      main: [[{ node: 'Holiday DB Fallback', type: 'main', index: 0 }]],
    },
    'Holiday DB Fallback': {
      main: [[{ node: 'Determine Holiday', type: 'main', index: 0 }]],
    },
    'Inbox Child Folders': {
      main: [[{ node: 'Resolve License Folder', type: 'main', index: 0 }]],
    },
    'Resolve License Folder': {
      main: [[
        { node: 'License Folder Messages', type: 'main', index: 0 },
        { node: 'Vacation Calendar', type: 'main', index: 0 },
      ]],
    },
    'Inbox Messages': {
      main: [[{ node: 'Build Teams Payload', type: 'main', index: 0 }]],
    },
    'License Folder Messages': {
      main: [[{ node: 'Build Teams Payload', type: 'main', index: 1 }]],
    },
    'Vacation Calendar': {
      main: [[{ node: 'Build Teams Payload', type: 'main', index: 2 }]],
    },
    'Determine Holiday': {
      main: [[{ node: 'Build Teams Payload', type: 'main', index: 3 }]],
    },
    'Build Teams Payload': {
      main: [[{ node: 'Should Send Alert', type: 'main', index: 0 }]],
    },
    'Should Send Alert': {
      main: [[{ node: 'Alert Teams Webhook', type: 'main', index: 0 }]],
    },
  },
  settings: {
    executionOrder: 'v1',
  },
};

fs.mkdirSync(workflowDir, { recursive: true });
fs.writeFileSync(workflowPath, JSON.stringify(workflow, null, 2) + '\n', 'utf8');
console.log(workflowPath);
