const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const WORKFLOW_DIR = path.join(ROOT, 'workflows', 'github-branch-monitor');
const WORKFLOW_JSON_PATH = path.join(WORKFLOW_DIR, 'github-branch-monitor_api.json');

const GITHUB_CREDENTIAL = {
  id: 'o72tcAaFcQlmQR4d',
  name: '__N8N_GITHUB_CREDENTIAL_NAME__',
};

const NOTION_CREDENTIAL = {
  id: 'LrLyYGhPvHMbPfZm',
  name: 'tsupport API',
};

const TEAMS_WEBHOOK =
  'https://redacted.invalid/powerautomate/github-branch-monitor-webhook';
const MONITOR_TITLE = 'github-branch-monitor 상태 알림';

function node(position, name, type, parameters, extra = {}) {
  return {
    parameters,
    type,
    position,
    ...extra,
    name,
  };
}

const baselineCode = [
  "const source = $input.first()?.json ?? {};",
  'const now = new Date();',
  "const parts = new Intl.DateTimeFormat('en-CA', {",
  "  timeZone: 'Asia/Seoul',",
  "  year: 'numeric',",
  "  month: '2-digit',",
  "  day: '2-digit',",
  "  weekday: 'short',",
  "  hour: '2-digit',",
  "  minute: '2-digit',",
  '  hour12: false,',
  '}).formatToParts(now);',
  '',
  "const year = parts.find((p) => p.type === 'year')?.value;",
  "const month = parts.find((p) => p.type === 'month')?.value;",
  "const day = parts.find((p) => p.type === 'day')?.value;",
  "const weekdayName = parts.find((p) => p.type === 'weekday')?.value;",
  "const hour = parts.find((p) => p.type === 'hour')?.value;",
  "const minute = parts.find((p) => p.type === 'minute')?.value;",
  '',
  'if (!year || !month || !day || !weekdayName || !hour || !minute) {',
  "  throw new Error('Failed to resolve current date in Asia/Seoul.');",
  '}',
  '',
  'const todayInt = Number(`${year}${month}${day}`);',
  "const todayDate = `${year}-${month}-${day}`;",
  "const todayMMDD = `${month}${day}`;",
  'const currentHour = Number(hour);',
  'const currentMinute = Number(minute);',
  "const isWeekend = ['Sat', 'Sun'].includes(weekdayName);",
  "const checkSlot = currentHour < 12 ? 'morning' : 'afternoon';",
  "const checkSlotLabel = checkSlot === 'morning' ? '오전 07:55' : '오후 13:55';",
  "const compareSinceLabel = checkSlot === 'morning' ? '이전 체크 이후' : '오전 07:55 체크 이후';",
  "const checkTime = new Intl.DateTimeFormat('sv-SE', {",
  "  timeZone: 'Asia/Seoul',",
  "  year: 'numeric',",
  "  month: '2-digit',",
  "  day: '2-digit',",
  "  hour: '2-digit',",
  "  minute: '2-digit',",
  "  second: '2-digit',",
  '  hour12: false,',
  "}).format(now) + ' KST';",
  '',
  'return [{',
  '  json: {',
  '    ...source,',
  '    Year: Number(year),',
  '    Month: Number(month),',
  '    Day: Number(day),',
  '    Hour: currentHour,',
  '    Minute: currentMinute,',
  '    WeekdayName: weekdayName,',
  '    IsWeekend: isWeekend,',
  '    DefaultIsHoliday: isWeekend,',
  "    DefaultHolidayName: isWeekend ? '주말' : '평일',",
  '    todayInt,',
  '    todayDate,',
  '    todayMMDD,',
  '    checkSlot,',
  '    checkSlotLabel,',
  '    compareSinceLabel,',
  '    checkTime,',
  '  },',
  '}];',
].join('\n');

const holidayJudgeCode = [
  'const recurringHolidays = [',
  "  { date: '0501', dateName: '근로자의 날' },",
  "  { date: '1231', dateName: '창립기념일' },",
  '];',
  '',
  "const baseline = $('Weekday Baseline').first().json;",
  "const apiPayload = $('HTTP Request').first()?.json ?? {};",
  "const dbPayload = $('Holiday DB Fallback').first()?.json ?? {};",
  '',
  'function normalizeApiItems(raw) {',
  '  if (!raw) return [];',
  '  return Array.isArray(raw) ? raw : [raw];',
  '}',
  '',
  'const apiItems = !apiPayload.error',
  "  ? normalizeApiItems(apiPayload.response?.body?.items?.item)",
  '  : [];',
  "const apiMatch = apiItems.find((item) => String(item?.locdate ?? '') === String(baseline.todayInt));",
  'const customMatch = recurringHolidays.find((item) => item.date === baseline.todayMMDD);',
  "const dbFound = !dbPayload.error && [true, 1, '1', 'true'].includes(dbPayload.found_in_db);",
  '',
  'let isHoliday = !!baseline.DefaultIsHoliday;',
  "let holidayName = baseline.DefaultHolidayName || (isHoliday ? '주말' : '평일');",
  "let holidayLookupSource = isHoliday ? 'default-weekend' : 'default-weekday';",
  '',
  'if (apiMatch) {',
  '  isHoliday = true;',
  "  holidayName = String(apiMatch.dateName || '공휴일');",
  "  holidayLookupSource = 'api';",
  '} else if (customMatch) {',
  '  isHoliday = true;',
  '  holidayName = customMatch.dateName;',
  "  holidayLookupSource = 'custom';",
  '} else if (dbFound) {',
  '  isHoliday = true;',
  "  holidayName = String(dbPayload.holiday_name || '공휴일');",
  "  holidayLookupSource = dbPayload.source_type ? `db:${dbPayload.source_type}` : 'db';",
  '}',
  '',
  'return [{',
  '  json: {',
  '    check_date: baseline.todayInt,',
  '    today_date: baseline.todayDate,',
  '    is_holiday: isHoliday,',
  '    holiday_name: holidayName,',
  '    is_weekend: !!baseline.IsWeekend,',
  '    weekday_name: baseline.WeekdayName,',
  "    checkSlot: baseline.checkSlot || '',",
  "    checkSlotLabel: baseline.checkSlotLabel || '',",
  "    compareSinceLabel: baseline.compareSinceLabel || '이전 체크 이후',",
  "    checkTime: baseline.checkTime || '',",
  '    holiday_lookup_source: holidayLookupSource,',
  '    holiday_lookup_failed: Boolean(apiPayload.error) && Boolean(dbPayload.error),',
  "    api_error: apiPayload.error?.message || apiPayload.error || '',",
  "    db_error: dbPayload.error || ''",
  '  }',
  '}];',
].join('\n');

const notificationTargetCode = [
  "const holiday = $('Holiday Judge').first()?.json ?? {};",
  'const vacationItems = $input.all();',
  '',
  "const NONE = '없음';",
  'const people = [',
  "  { name: '김민영', email: 'mykim@vms-solutions.com' },",
  "  { name: '조현재', email: 'jyi30@vms-solutions.com' },",
  "  { name: '김진욱', email: 'jwkim@vms-solutions.com' },",
  '];',
  '',
  "function normalize(value) { return String(value ?? '').normalize('NFC').replace(/\\\\s+/g, '').toLowerCase(); }",
  'function contains(value, keyword) { return normalize(value).includes(normalize(keyword)); }',
  'function collectStrings(value, out = [], depth = 0) {',
  '  if (depth > 10 || value == null) return out;',
  "  if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') { out.push(String(value)); return out; }",
  '  if (Array.isArray(value)) { for (const item of value) collectStrings(item, out, depth + 1); return out; }',
  "  if (typeof value === 'object') { for (const nested of Object.values(value)) collectStrings(nested, out, depth + 1); }",
  '  return out;',
  '}',
  "function ymds(text) { return String(text ?? '').match(/\\\\d{4}-\\\\d{2}-\\\\d{2}/g) || []; }",
  "function ymd(text) { const match = String(text ?? '').match(/\\\\d{4}-\\\\d{2}-\\\\d{2}/); return match ? match[0] : ''; }",
  'function ranges(item) {',
  '  const found = [];',
  '  const uniq = new Set();',
  '  function push(label, start, end) {',
  '    const s = ymd(start);',
  '    const e = ymd(end || start);',
  '    if (!s) return;',
  "    const key = label + '|' + s + '|' + e;",
  '    if (uniq.has(key)) return;',
  '    uniq.add(key);',
  '    found.push({ start: s, end: e || s });',
  '  }',
  '  function walk(value, label, depth) {',
  '    if (depth > 8 || value == null) return;',
  "    if (typeof value === 'string') { const items = ymds(value); if (items.length === 1) push(label, items[0], items[0]); if (items.length >= 2) push(label, items[0], items[1]); return; }",
  "    if (typeof value === 'number' || typeof value === 'boolean') return;",
  '    if (Array.isArray(value)) { value.forEach((item, idx) => walk(item, label + "[" + idx + "]", depth + 1)); return; }',
  "    if (typeof value === 'object') {",
  "      if ('start' in value && ymd(value.start)) push(label + '.start', value.start, value.end || value.start);",
  "      if ('date' in value && value.date && typeof value.date === 'object' && ymd(value.date.start)) push(label + '.date', value.date.start, value.date.end || value.date.start);",
  "      if ('property_date' in value && value.property_date && typeof value.property_date === 'object' && ymd(value.property_date.start)) push(label + '.property_date', value.property_date.start, value.property_date.end || value.property_date.start);",
  '      for (const [key, nested] of Object.entries(value)) walk(nested, label + "." + key, depth + 1);',
  '    }',
  '  }',
  "  walk(item?.json ?? item, 'root', 0);",
  '  return found;',
  '}',
  "function isVacationText(text) { return ['휴가', '연차', '반차', '오전반차', '오후반차', '안식월', '공가', '공휴일', '휴일', 'vacation', 'leave', 'pto', 'dayoff', 'off'].some((keyword) => contains(text, keyword)); }",
  '',
  "const today = String(holiday.today_date || '');",
  'const vacationLookupFailed = vacationItems.some((item) => item?.json?.error);',
  'const todayVacationItems = !today || vacationLookupFailed ? [] : vacationItems.filter((item) => {',
  '  const text = collectStrings(item?.json ?? item).join(" ");',
  '  if (!isVacationText(text)) return false;',
  '  const itemRanges = ranges(item);',
  '  return itemRanges.length > 0 && itemRanges.some((range) => range.start <= today && today <= range.end);',
  '});',
  'const vacationUsers = people.filter((person) => todayVacationItems.some((item) => {',
  '  const text = collectStrings(item?.json ?? item).join(" ");',
  '  return contains(text, person.name) || contains(text, person.email);',
  '}));',
  'const vacationSet = new Set(vacationUsers.map((person) => person.email));',
  'const activeUsers = people.filter((person) => !vacationSet.has(person.email));',
  'const teamsEntities = activeUsers.map((person) => ({',
  '  type: "mention",',
  '  text: "<at>" + person.name + "</at>",',
  '  mentioned: { id: person.email, name: person.name },',
  '}));',
  'const teamsMentionText = activeUsers.map((person) => "<at>" + person.name + "</at>").join(", ");',
  'const activeUsersText = activeUsers.length > 0 ? activeUsers.map((person) => person.name).join(", ") : NONE;',
  'const vacationUsersText = vacationUsers.length > 0 ? vacationUsers.map((person) => person.name).join(", ") : NONE;',
  'const vacationFallbackText = vacationLookupFailed ? "휴가 정보 조회에 실패해 전원을 근무 대상으로 간주했습니다." : "";',
  'const teamsAttentionText = activeUsers.length > 0',
  '  ? `${teamsMentionText} 브랜치 상태 확인 알림입니다.`',
  '  : "담당자 3명 모두 휴가 중입니다. 상태 알림만 전송합니다.";',
  '',
  'return [{',
  '  json: {',
  '    ...holiday,',
  '    watchUserCount: people.length,',
  '    activeUsersText,',
  '    vacationUsersText,',
  '    teamsEntities,',
  '    teamsAttentionText,',
  '    vacationFallbackText,',
  '    allUsersOnVacation: activeUsers.length === 0,',
  '  },',
  '}];',
].join('\n');

const branchMonitorConfigCode = [
  "const source = $input.first()?.json ?? {};",
  '',
  'const monitoredBranches = [',
  `  { owner: 'vmslab', repository: 'Mozart2.0', branch: 'Release/2026.126.1', teamsLabel: '${MONITOR_TITLE}' },`,
  `  { owner: 'vmslab', repository: 'mozart-ui-app', branch: 'Release/2026.126.1', teamsLabel: '${MONITOR_TITLE}' },`,
  '];',
  '',
  'return monitoredBranches.map((cfg) => ({',
  '  json: {',
  '    ...source,',
  '    repoOwner: cfg.owner,',
  '    repository: cfg.repository,',
  '    branch: cfg.branch,',
  "    branchLabel: cfg.teamsLabel || `${cfg.owner}/${cfg.repository}:${cfg.branch}`,",
  "    branchKey: `${cfg.owner}/${cfg.repository}:${cfg.branch}`,",
  "    checkTime: source.checkTime || '',",
  "    checkSlot: source.checkSlot || '',",
  "    checkSlotLabel: source.checkSlotLabel || '',",
  "    compareSinceLabel: source.compareSinceLabel || '이전 체크 이후',",
  "    branchUrl: `https://github.com/${cfg.owner}/${cfg.repository}/tree/${encodeURIComponent(cfg.branch)}`,",
  "    branchApiUrl: `https://api.github.com/repos/${cfg.owner}/${cfg.repository}/branches/${encodeURIComponent(cfg.branch)}`,",
  "    compareBaseUrl: `https://api.github.com/repos/${cfg.owner}/${cfg.repository}/compare`,",
  '  },',
  '}));',
].join('\n');

const comparisonStateCode = [
  "const configItems = $('Branch Monitor Config').all().map((item) => item.json ?? {});",
  'const branchPayloadItems = $input.all().map((item) => item.json ?? {});',
  "const workflowStaticData = $getWorkflowStaticData('global');",
  '',
  'if (!workflowStaticData.githubBranchMonitor) {',
  '  workflowStaticData.githubBranchMonitor = {};',
  '}',
  '',
  'const branchState = workflowStaticData.githubBranchMonitor;',
  '',
  'return branchPayloadItems.map((branchPayload, index) => {',
  '  const config = configItems[index] || {};',
  '  const previousState = branchState[config.branchKey] || null;',
  "  const currentSha = branchPayload.commit?.sha || '';",
  "  const currentCommit = branchPayload.commit?.commit || {};",
  "  const currentCommitDate = currentCommit.committer?.date || currentCommit.author?.date || '';",
  "  const currentCommitMessage = currentCommit.message || '';",
  "  const currentCommitAuthor = currentCommit.committer?.name || currentCommit.author?.name || '';",
  "  const previousSha = previousState?.lastCheckedSha || '';",
  "  const previousCheckedAt = previousState?.lastCheckedAt || '';",
  '  const isInitialization = !previousSha;',
  '  const hasChanged = Boolean(previousSha) && previousSha !== currentSha;',
  '',
  '  if (!currentSha) {',
  "    throw new Error(`Failed to resolve branch head SHA for ${config.branchKey}.`);",
  '  }',
  '',
  '  return {',
  '    json: {',
  '      ...config,',
  '      currentSha,',
  '      currentCommitDate,',
  '      currentCommitMessage,',
  '      currentCommitAuthor,',
  '      previousSha,',
  '      previousCheckedAt,',
  '      isInitialization,',
  '      hasChanged,',
  '      shouldCompare: hasChanged,',
  "      compareUrl: hasChanged ? `${config.compareBaseUrl}/${previousSha}...${currentSha}` : '',",
  '    },',
  '  };',
  '});',
].join('\n');

const buildTeamsPayloadCode = [
  "const notificationTarget = $('Resolve Notification Targets').first()?.json ?? {};",
  "const stateItems = $('If Branch Changed').all().map((item) => item.json ?? {});",
  "const compareItems = $('Fetch Branch Compare').all().map((item) => item.json ?? {});",
  '',
  "const shortSha = (sha) => String(sha || '').slice(0, 7);",
  "const firstLine = (text) => String(text || '').split('\\n')[0].trim();",
  'const formatKst = (iso) => {',
  "  if (!iso) return '';",
  "  return new Intl.DateTimeFormat('sv-SE', {",
  "    timeZone: 'Asia/Seoul',",
  "    year: 'numeric',",
  "    month: '2-digit',",
  "    day: '2-digit',",
  "    hour: '2-digit',",
  "    minute: '2-digit',",
  '    hour12: false,',
  "  }).format(new Date(iso)) + ' KST';",
  '};',
  '',
  'return compareItems.map((compare, index) => {',
  '  const state = stateItems[index] || {};',
  '  const commits = Array.isArray(compare.commits) ? compare.commits : [];',
  '  const files = Array.isArray(compare.files) ? compare.files : [];',
  "  const compareError = compare.error?.message || compare.message || '';",
  "  const teamsEntities = Array.isArray(notificationTarget.teamsEntities) ? notificationTarget.teamsEntities : [];",
  "  const teamsAttentionText = notificationTarget.teamsAttentionText || '';",
  "  const activeUsersText = notificationTarget.activeUsersText || '없음';",
  "  const vacationUsersText = notificationTarget.vacationUsersText || '없음';",
  "  const teamsWarningText = notificationTarget.vacationFallbackText || '';",
  '',
  '  let teamsSummary = `${state.checkSlotLabel} 체크에서 브랜치 변경이 감지되었습니다. (${commits.length} commits)`;',
  "  let teamsDetails = '';",
  '',
  '  if (compareError) {',
  '    teamsSummary = `${state.checkSlotLabel} 체크에서 브랜치 SHA 변경은 감지됐지만 compare 상세 조회는 실패했습니다.`;',
  '    teamsDetails = [',
  '      `확인 회차: ${state.checkSlotLabel}`,',
  '      `변경 기준: ${state.compareSinceLabel}`,',
  '      `저장소: ${state.repoOwner}/${state.repository}`,',
  '      `브랜치: ${state.branch}`,',
  '      `이전 SHA: ${shortSha(state.previousSha)}`,',
  '      `현재 SHA: ${shortSha(state.currentSha)}`,',
  '      `브랜치 링크: ${state.branchUrl}`,',
  '      `오류: ${compareError}`',
  "    ].join('\\n');",
  '  } else {',
  '    const commitLines = commits.slice(0, 10).map((commit, lineIndex) => {',
  "      const message = firstLine(commit.commit?.message || '(no message)');",
  "      const author = commit.commit?.author?.name || commit.author?.login || 'unknown';",
  "      const date = formatKst(commit.commit?.author?.date || commit.commit?.committer?.date || '');",
  "      const link = commit.html_url ? `\\n링크: ${commit.html_url}` : '';",
  '      return `${lineIndex + 1}. ${message}\\n작성자: ${author} | 시각: ${date} | SHA: ${shortSha(commit.sha)}${link}`;',
  '    });',
  '',
  '    const fileLines = files.slice(0, 10).map((file, lineIndex) => {',
  "      const changes = Number.isFinite(file.changes) ? ` (${file.changes} changes)` : '';",
  '      return `${lineIndex + 1}. [${file.status}] ${file.filename}${changes}`;',
  '    });',
  '',
  '    teamsDetails = [',
  '      `확인 회차: ${state.checkSlotLabel}`,',
  '      `변경 기준: ${state.compareSinceLabel}`,',
  '      `비교 SHA: ${shortSha(state.previousSha)} -> ${shortSha(state.currentSha)}`,',
  '      `브랜치 링크: ${state.branchUrl}`,',
  '      `비교 링크: ${compare.html_url || state.branchUrl}`,',
  "      '',",
  '      `커밋 ${commits.length}건`,',
  "      commitLines.length > 0 ? commitLines.join('\\n\\n') : '-',",
  "      '',",
  '      `파일 변경 ${files.length}건`,',
  "      fileLines.length > 0 ? fileLines.join('\\n') : '-'",
  "    ].join('\\n');",
  '  }',
  '',
  '  return {',
  '    json: {',
  '      ...state,',
  '      compareError,',
  "      compareHtmlUrl: compare.html_url || '',",
  '      commitCount: commits.length,',
  '      fileCount: files.length,',
  '      teamsEntities,',
  '      teamsAttentionText,',
  '      activeUsersText,',
  '      vacationUsersText,',
  '      teamsWarningText,',
  `      teamsTitle: state.branchLabel || '${MONITOR_TITLE}',`,
  '      teamsSummary: `${state.repoOwner}/${state.repository} / ${state.branch} - ${teamsSummary}`,',
  '      teamsDetails,',
  '      currentCommitDateText: formatKst(state.currentCommitDate),',
  '    },',
  '  };',
  '});',
].join('\n');

const persistBranchStateCode = [
  'const items = $input.all().map((entry) => entry.json ?? {});',
  "const workflowStaticData = $getWorkflowStaticData('global');",
  '',
  'if (!workflowStaticData.githubBranchMonitor) {',
  '  workflowStaticData.githubBranchMonitor = {};',
  '}',
  '',
  'return items.map((item) => {',
  '  const existing = workflowStaticData.githubBranchMonitor[item.branchKey] || {};',
  '  workflowStaticData.githubBranchMonitor[item.branchKey] = {',
  '    lastCheckedSha: item.currentSha,',
  "    lastCheckedAt: new Date().toISOString(),",
  "    lastCommitDate: item.currentCommitDate || '',",
  "    lastCommitMessage: item.currentCommitMessage || '',",
  "    lastCommitAuthor: item.currentCommitAuthor || '',",
  "    lastNotifiedSha: existing.lastNotifiedSha || '',",
  "    lastNotifiedAt: existing.lastNotifiedAt || '',",
  "    branchUrl: item.branchUrl || '',",
  "    repository: `${item.repoOwner}/${item.repository}`,",
  "    branch: item.branch || ''",
  '  };',
  '',
  '  return {',
  '    json: {',
  '      ...item,',
  '      stateSaved: true,',
  "      notifySkippedReason: item.isInitialization ? 'initialized-baseline' : 'no-change'",
  '    }',
  '  };',
  '});',
].join('\n');

const persistAlertedStateCode = [
  "const items = $('Build Teams Payload').all().map((entry) => entry.json ?? {});",
  "const workflowStaticData = $getWorkflowStaticData('global');",
  '',
  'if (!workflowStaticData.githubBranchMonitor) {',
  '  workflowStaticData.githubBranchMonitor = {};',
  '}',
  '',
  'return items.map((item) => {',
  '  workflowStaticData.githubBranchMonitor[item.branchKey] = {',
  '    lastCheckedSha: item.currentSha,',
  "    lastCheckedAt: new Date().toISOString(),",
  "    lastCommitDate: item.currentCommitDate || '',",
  "    lastCommitMessage: item.currentCommitMessage || '',",
  "    lastCommitAuthor: item.currentCommitAuthor || '',",
  '    lastNotifiedSha: item.currentSha,',
  "    lastNotifiedAt: new Date().toISOString(),",
  "    branchUrl: item.branchUrl || '',",
  "    repository: `${item.repoOwner}/${item.repository}`,",
  "    branch: item.branch || ''",
  '  };',
  '',
  '  return {',
  '    json: {',
  '      ...item,',
  '      stateSaved: true,',
  '      notified: true',
  '    }',
  '  };',
  '});',
].join('\n');

const buildNoChangePayloadCode = [
  "const notificationTarget = $('Resolve Notification Targets').first()?.json ?? {};",
  "const items = $('Persist Branch State').all().map((entry) => entry.json ?? {});",
  "const allStates = $('Build Comparison State').all().map((entry) => entry.json ?? {});",
  '',
  'if (items.length === 0 || allStates.length === 0) {',
  '  return [];',
  '}',
  '',
  'const allNoChange = allStates.every((item) => !item.hasChanged);',
  'const anyInitialization = allStates.some((item) => item.isInitialization);',
  '',
  'if (!allNoChange || anyInitialization) {',
  '  return [];',
  '}',
  '',
  'const first = allStates[0] || {};',
  'const repositoriesText = allStates',
  "  .map((item) => `${item.repoOwner}/${item.repository}`)",
  "  .join(', ');",
  '',
  'return [{',
  '  json: {',
  `    teamsTitle: '${MONITOR_TITLE}',`,
  "    teamsSummary: `${first.checkSlotLabel || ''} 체크 결과 변경 사항이 없습니다.`,",
  "    teamsDetails: '',",
  "    teamsAttentionText: '',",
  "    activeUsersText: '없음',",
  "    vacationUsersText: notificationTarget.vacationUsersText || '없음',",
  '    teamsEntities: [],',
  "    teamsWarningText: notificationTarget.vacationFallbackText || '',",
  "    checkSlotLabel: first.checkSlotLabel || '',",
  "    compareSinceLabel: first.compareSinceLabel || '이전 체크 이후',",
  "    checkTime: first.checkTime || '',",
  '    branchCount: allStates.length,',
  '    repositoriesText,',
  '  },',
  '}];',
].join('\n');

const changedWebhookBody =
  "={{ ({ type: 'message', summary: $json.teamsSummary, text: $json.teamsSummary, attachments: [{ contentType: 'application/vnd.microsoft.card.adaptive', content: { type: 'AdaptiveCard', body: [{ type: 'TextBlock', text: $json.teamsTitle, weight: 'Bolder', size: 'Medium', wrap: true }, { type: 'TextBlock', text: $json.teamsAttentionText || '', wrap: true, spacing: 'Small', isVisible: Boolean($json.teamsAttentionText) }, { type: 'TextBlock', text: $json.teamsSummary, wrap: true, spacing: 'Small' }, { type: 'FactSet', facts: [{ title: '알림 대상', value: $json.activeUsersText || '없음' }, { title: '휴가자', value: $json.vacationUsersText || '없음' }, { title: '저장소', value: `${$json.repoOwner}/${$json.repository}` }, { title: '브랜치', value: $json.branch }, { title: '확인 회차', value: $json.checkSlotLabel || '' }, { title: '변경 기준', value: $json.compareSinceLabel || '' }, { title: '비교 범위', value: `${String($json.previousSha || '').slice(0, 7)} -> ${String($json.currentSha || '').slice(0, 7)}` }, { title: '커밋 수', value: String($json.commitCount ?? 0) + '건' }, { title: '파일 수', value: String($json.fileCount ?? 0) + '건' }, { title: '마지막 커밋 시각', value: $json.currentCommitDateText || '' }, { title: '확인 시각', value: $json.checkTime || '' }] }, { type: 'TextBlock', text: $json.teamsWarningText || '', wrap: true, spacing: 'Medium', color: 'Attention', isVisible: Boolean($json.teamsWarningText) }, { type: 'TextBlock', text: $json.teamsDetails || '', wrap: true, spacing: 'Medium', isVisible: Boolean($json.teamsDetails) }], msteams: { entities: Array.isArray($json.teamsEntities) ? $json.teamsEntities : [] }, '$schema': 'http://adaptivecards.io/schemas/adaptive-card.json', version: '1.4' } }] }) }}";

const noChangeWebhookBody =
  "={{ ({ type: 'message', summary: $json.teamsSummary, text: $json.teamsSummary, attachments: [{ contentType: 'application/vnd.microsoft.card.adaptive', content: { type: 'AdaptiveCard', body: [{ type: 'TextBlock', text: $json.teamsTitle, weight: 'Bolder', size: 'Medium', wrap: true }, { type: 'TextBlock', text: $json.teamsAttentionText || '', wrap: true, spacing: 'Small', isVisible: Boolean($json.teamsAttentionText) }, { type: 'TextBlock', text: $json.teamsSummary, wrap: true, spacing: 'Small' }, { type: 'FactSet', facts: [{ title: '알림 대상', value: $json.activeUsersText || '없음' }, { title: '휴가자', value: $json.vacationUsersText || '없음' }, { title: '감시 대상', value: String($json.branchCount ?? 0) + '개 브랜치' }, { title: '저장소', value: $json.repositoriesText || '' }, { title: '확인 회차', value: $json.checkSlotLabel || '' }, { title: '확인 시각', value: $json.checkTime || '' }] }, { type: 'TextBlock', text: $json.teamsWarningText || '', wrap: true, spacing: 'Medium', color: 'Attention', isVisible: Boolean($json.teamsWarningText) }], msteams: { entities: Array.isArray($json.teamsEntities) ? $json.teamsEntities : [] }, '$schema': 'http://adaptivecards.io/schemas/adaptive-card.json', version: '1.4' } }] }) }}";

const workflow = {
  name: 'github-branch-monitor',
  nodes: [
    node(
      [-360, 0],
      'Schedule Trigger',
      'n8n-nodes-base.scheduleTrigger',
      {
        rule: {
          interval: [
            {
              field: 'weeks',
              triggerAtDay: [1, 2, 3, 4, 5],
              triggerAtHour: 7,
              triggerAtMinute: 55,
            },
            {
              field: 'weeks',
              triggerAtDay: [1, 2, 3, 4, 5],
              triggerAtHour: 13,
              triggerAtMinute: 55,
            },
          ],
        },
      },
      {
        typeVersion: 1.3,
        id: '78b62e8e-f5d7-4d00-9305-6714a352ce95',
        alwaysOutputData: true,
        retryOnFail: true,
      },
    ),
    node(
      [-360, 160],
      'Weekday Baseline',
      'n8n-nodes-base.code',
      { jsCode: baselineCode },
      {
        typeVersion: 2,
        id: '81c42bd7-9129-40a8-bc77-414de550f75b',
        alwaysOutputData: true,
      },
    ),
    node(
      [-120, 160],
      'HTTP Request',
      'n8n-nodes-base.httpRequest',
      {
        url: "=http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo?solYear={{ $json['Year'] }}&numOfRows=50&ServiceKey=ea205130648aa0e11f1cc778bef29d18ef68b212e587c5590792dbd4f0a6b5c0",
        options: {},
      },
      {
        typeVersion: 4.3,
        id: '3cc1bd01-b304-4ca4-91fa-1ecea6f5dce4',
        alwaysOutputData: true,
        onError: 'continueRegularOutput',
      },
    ),
    node(
      [120, 160],
      'Holiday DB Fallback',
      'n8n-nodes-base.microsoftSql',
      {
        operation: 'executeQuery',
        query:
          "=DECLARE @d DATE = CAST('{{ $('Weekday Baseline').item.json.todayDate }}' AS date);\nSELECT\n    CONVERT(VARCHAR(8), @d, 112) AS check_date,\n    CAST(CASE WHEN EXISTS (\n        SELECT 1\n        FROM TsMgmt.dbo.HolidayCalendarKR\n        WHERE HolidayDate = @d\n    ) THEN 1 ELSE 0 END AS bit) AS found_in_db,\n    ISNULL((SELECT TOP 1 HolidayName FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), '') AS holiday_name,\n    ISNULL((SELECT TOP 1 SourceType FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), '') AS source_type,\n    ISNULL((SELECT TOP 1 SourceYear FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), 0) AS source_year;",
      },
      {
        typeVersion: 1.1,
        id: 'f8c0a6ab-9666-4b2f-b8cb-f350dc68f0fd',
        alwaysOutputData: true,
        onError: 'continueRegularOutput',
        credentials: {
          microsoftSql: {
            id: '2dZb5OQPbTyO3052',
            name: 'TsMgmt(DevTest_SQL2022_26)',
          },
        },
      },
    ),
    node(
      [360, 160],
      'Holiday Judge',
      'n8n-nodes-base.code',
      { jsCode: holidayJudgeCode },
      {
        typeVersion: 2,
        id: '7156a2c1-72f2-4368-8683-fdfdf00c90bb',
        alwaysOutputData: true,
      },
    ),
    node(
      [560, 160],
      'If',
      'n8n-nodes-base.if',
      {
        conditions: {
          options: {
            caseSensitive: true,
            leftValue: '',
            typeValidation: 'strict',
            version: 2,
          },
          conditions: [
            {
              id: '1d7a729b-06fd-4f53-a9a1-3730e1fbef44',
              leftValue: '={{ $json.is_holiday }}',
              rightValue: false,
              operator: {
                type: 'boolean',
                operation: 'equals',
              },
            },
          ],
          combinator: 'and',
        },
        options: {},
      },
      {
        typeVersion: 2.2,
        id: '4cfabff5-bf96-4f9f-ab8d-06da1e4ddb9b',
      },
    ),
    node(
      [800, 320],
      'Vacation Calendar',
      'n8n-nodes-base.notion',
      {
        resource: 'databasePage',
        operation: 'getAll',
        databaseId: {
          __rl: true,
          value: '205cb995-8309-80e4-ac2a-c8589a1783eb',
          mode: 'list',
          cachedResultName: 'TS Calendar DB',
          cachedResultUrl: 'https://www.notion.so/205cb995830980e4ac2ac8589a1783eb',
        },
        options: {
          sort: {
            sortValue: [{ key: 'Date|date', direction: 'descending' }],
          },
        },
      },
      {
        typeVersion: 2.2,
        id: '9639eaf4-6d5f-493e-8d95-037b0d3f7dc5',
        alwaysOutputData: true,
        onError: 'continueRegularOutput',
        credentials: {
          notionApi: NOTION_CREDENTIAL,
        },
      },
    ),
    node(
      [1040, 320],
      'Resolve Notification Targets',
      'n8n-nodes-base.code',
      { jsCode: notificationTargetCode },
      {
        typeVersion: 2,
        id: '49ad58d9-f11b-461b-93f8-eb26925b5d10',
        alwaysOutputData: true,
      },
    ),
    node(
      [800, 160],
      'Branch Monitor Config',
      'n8n-nodes-base.code',
      { jsCode: branchMonitorConfigCode },
      {
        typeVersion: 2,
        id: 'd264cc1e-3516-4388-bb08-619a914ca4ad',
        alwaysOutputData: true,
      },
    ),
    node(
      [1040, 160],
      'Fetch Branch Head',
      'n8n-nodes-base.httpRequest',
      {
        url: '={{ $json.branchApiUrl }}',
        authentication: 'predefinedCredentialType',
        nodeCredentialType: 'githubApi',
        sendHeaders: true,
        headerParameters: {
          parameters: [
            {
              name: 'Accept',
              value: 'application/vnd.github+json',
            },
          ],
        },
        options: {},
      },
      {
        typeVersion: 4.3,
        id: '6f069dfe-20c7-4431-9f3f-0c1d8605fd4b',
        alwaysOutputData: true,
        credentials: {
          githubApi: GITHUB_CREDENTIAL,
        },
      },
    ),
    node(
      [1280, 160],
      'Build Comparison State',
      'n8n-nodes-base.code',
      { jsCode: comparisonStateCode },
      {
        typeVersion: 2,
        id: 'b4de7d97-f583-4521-bbfd-03b402a1fb58',
        alwaysOutputData: true,
      },
    ),
    node(
      [1520, 160],
      'If Branch Changed',
      'n8n-nodes-base.if',
      {
        conditions: {
          options: {
            caseSensitive: true,
            leftValue: '',
            typeValidation: 'strict',
            version: 2,
          },
          conditions: [
            {
              id: 'b1621960-ddaa-47c8-8eff-f85a90003d0d',
              leftValue: '={{ $json.shouldCompare }}',
              rightValue: true,
              operator: {
                type: 'boolean',
                operation: 'equals',
              },
            },
          ],
          combinator: 'and',
        },
        options: {},
      },
      {
        typeVersion: 2.2,
        id: '1d1c5f88-e5fb-4f25-b690-94122ad576db',
      },
    ),
    node(
      [1760, 80],
      'Fetch Branch Compare',
      'n8n-nodes-base.httpRequest',
      {
        url: '={{ $json.compareUrl }}',
        authentication: 'predefinedCredentialType',
        nodeCredentialType: 'githubApi',
        sendHeaders: true,
        headerParameters: {
          parameters: [
            {
              name: 'Accept',
              value: 'application/vnd.github+json',
            },
          ],
        },
        options: {},
      },
      {
        typeVersion: 4.3,
        id: '8b463f7f-2187-46c8-a0f4-a1c2867ae46f',
        alwaysOutputData: true,
        onError: 'continueRegularOutput',
        credentials: {
          githubApi: GITHUB_CREDENTIAL,
        },
      },
    ),
    node(
      [2000, 80],
      'Build Teams Payload',
      'n8n-nodes-base.code',
      { jsCode: buildTeamsPayloadCode },
      {
        typeVersion: 2,
        id: 'c48f2661-6345-46f8-bfa2-ad94ae5d855e',
        alwaysOutputData: true,
      },
    ),
    node(
      [2240, 80],
      'Teams Webhook',
      'n8n-nodes-base.httpRequest',
      {
        method: 'POST',
        url: TEAMS_WEBHOOK,
        sendBody: true,
        specifyBody: 'json',
        jsonBody: changedWebhookBody,
        options: {},
      },
      {
        typeVersion: 4.2,
        id: '9e612812-2af7-4ce9-ae6a-536355513f55',
      },
    ),
    node(
      [1760, 280],
      'Persist Branch State',
      'n8n-nodes-base.code',
      { jsCode: persistBranchStateCode },
      {
        typeVersion: 2,
        id: '4390b373-8b59-44c6-b4ff-67fabd4fa42b',
        alwaysOutputData: true,
      },
    ),
    node(
      [2480, 80],
      'Persist Alerted State',
      'n8n-nodes-base.code',
      { jsCode: persistAlertedStateCode },
      {
        typeVersion: 2,
        id: '060d0f5c-0b13-4f03-a90c-70e878f05bd3',
        alwaysOutputData: true,
      },
    ),
    node(
      [2000, 280],
      'Build No Change Payload',
      'n8n-nodes-base.code',
      { jsCode: buildNoChangePayloadCode },
      {
        typeVersion: 2,
        id: '4f751426-1777-4575-9b8c-010fd4d39f0d',
        alwaysOutputData: true,
      },
    ),
    node(
      [2240, 280],
      'Teams Webhook No Change',
      'n8n-nodes-base.httpRequest',
      {
        method: 'POST',
        url: TEAMS_WEBHOOK,
        sendBody: true,
        specifyBody: 'json',
        jsonBody: noChangeWebhookBody,
        options: {},
      },
      {
        typeVersion: 4.2,
        id: 'c6a225cd-b344-48e2-a4a6-a1d6af47b766',
      },
    ),
  ],
  connections: {
    'Schedule Trigger': {
      main: [[{ node: 'Weekday Baseline', type: 'main', index: 0 }]],
    },
    'Weekday Baseline': {
      main: [[{ node: 'HTTP Request', type: 'main', index: 0 }]],
    },
    'HTTP Request': {
      main: [[{ node: 'Holiday DB Fallback', type: 'main', index: 0 }]],
    },
    'Holiday DB Fallback': {
      main: [[{ node: 'Holiday Judge', type: 'main', index: 0 }]],
    },
    'Holiday Judge': {
      main: [[{ node: 'If', type: 'main', index: 0 }]],
    },
    If: {
      main: [[{ node: 'Vacation Calendar', type: 'main', index: 0 }]],
    },
    'Vacation Calendar': {
      main: [[{ node: 'Resolve Notification Targets', type: 'main', index: 0 }]],
    },
    'Resolve Notification Targets': {
      main: [[{ node: 'Branch Monitor Config', type: 'main', index: 0 }]],
    },
    'Branch Monitor Config': {
      main: [[{ node: 'Fetch Branch Head', type: 'main', index: 0 }]],
    },
    'Fetch Branch Head': {
      main: [[{ node: 'Build Comparison State', type: 'main', index: 0 }]],
    },
    'Build Comparison State': {
      main: [[{ node: 'If Branch Changed', type: 'main', index: 0 }]],
    },
    'If Branch Changed': {
      main: [
        [{ node: 'Fetch Branch Compare', type: 'main', index: 0 }],
        [{ node: 'Persist Branch State', type: 'main', index: 0 }],
      ],
    },
    'Fetch Branch Compare': {
      main: [[{ node: 'Build Teams Payload', type: 'main', index: 0 }]],
    },
    'Build Teams Payload': {
      main: [[{ node: 'Teams Webhook', type: 'main', index: 0 }]],
    },
    'Teams Webhook': {
      main: [[{ node: 'Persist Alerted State', type: 'main', index: 0 }]],
    },
    'Persist Branch State': {
      main: [[{ node: 'Build No Change Payload', type: 'main', index: 0 }]],
    },
    'Build No Change Payload': {
      main: [[{ node: 'Teams Webhook No Change', type: 'main', index: 0 }]],
    },
  },
  settings: {
    executionOrder: 'v1',
    callerPolicy: 'workflowsFromSameOwner',
    availableInMCP: false,
  },
};

fs.mkdirSync(WORKFLOW_DIR, { recursive: true });
fs.writeFileSync(WORKFLOW_JSON_PATH, `${JSON.stringify(workflow, null, 4)}\n`, 'utf8');

console.log(`Wrote ${path.relative(ROOT, WORKFLOW_JSON_PATH)}`);
