const fs = require('fs');
const path = require('path');

const root = process.cwd();
const workflowName = 'Notion-In-Review-Inform';
const workflowDir = path.join(root, 'workflows', workflowName);
const workflowPath = path.join(workflowDir, `${workflowName}_api.json`);

const TEAMS_WEBHOOK =
  process.env.TS_NOTION_REVIEW_TEAMS_WEBHOOK || 'https://redacted.invalid/powerautomate/notion-review-webhook';

const NOTION_CREDENTIAL = {
  id: 'LrLyYGhPvHMbPfZm',
  name: 'tsupport API',
};

const TARGET_DATABASE_ID = '77b2e35b-ab50-45cc-8314-e254a806229f';
const TARGET_DATABASE_URL = 'https://www.notion.so/vmssolutions/77b2e35bab5045cc8314e254a806229f?v=16fcb995830980e5a800000cfdbb881d';
const VACATION_DATABASE_ID = '205cb995-8309-80e4-ac2a-c8589a1783eb';

function uuid(seed) {
  const text = `${workflowName}:${seed}`;
  let hash = 0;
  for (let i = 0; i < text.length; i += 1) {
    hash = ((hash << 5) - hash + text.charCodeAt(i)) | 0;
  }
  const hex = (n) => (Math.abs(n).toString(16).padStart(8, '0')).slice(0, 8);
  return `${hex(hash + 1)}-${hex(hash + 2).slice(0, 4)}-${hex(hash + 3).slice(0, 4)}-${hex(hash + 4).slice(0, 4)}-${hex(hash + 5)}${hex(hash + 6)}`;
}

const weekdayBaselineCode = [
  'const now = new Date();',
  "const parts = new Intl.DateTimeFormat('en-CA', {",
  "  timeZone: 'Asia/Seoul',",
  "  year: 'numeric',",
  "  month: '2-digit',",
  "  day: '2-digit',",
  "  weekday: 'long',",
  '}).formatToParts(now);',
  "const pick = (type) => parts.find((part) => part.type === type)?.value || '';",
  "const year = pick('year');",
  "const month = pick('month');",
  "const day = pick('day');",
  "const weekdayEn = pick('weekday');",
  'const weekdayMap = {',
  "  Monday: '\\uC6D4\\uC694\\uC77C',",
  "  Tuesday: '\\uD654\\uC694\\uC77C',",
  "  Wednesday: '\\uC218\\uC694\\uC77C',",
  "  Thursday: '\\uBAA9\\uC694\\uC77C',",
  "  Friday: '\\uAE08\\uC694\\uC77C',",
  "  Saturday: '\\uD1A0\\uC694\\uC77C',",
  "  Sunday: '\\uC77C\\uC694\\uC77C',",
  '};',
  "const isWeekend = weekdayEn === 'Saturday' || weekdayEn === 'Sunday';",
  'return [{',
  '  json: {',
  '    todayDate: `${year}-${month}-${day}`,',
  '    todayInt: `${year}${month}${day}`,',
  '    todayMMDD: `${month}${day}`,',
  '    WeekdayName: weekdayMap[weekdayEn] || weekdayEn,',
  '    IsWeekend: isWeekend,',
  '    DefaultIsHoliday: isWeekend,',
  "    DefaultHolidayName: isWeekend ? '\\uC8FC\\uB9D0' : '\\uD3C9\\uC77C',",
  '  }',
  '}];',
].join('\n');

const determineHolidayCode = [
  "const baseline = $('Weekday Baseline').first().json;",
  "const dbPayload = $('Holiday DB Fallback').first()?.json ?? {};",
  "const dbFound = !dbPayload.error && [true, 1, '1', 'true'].includes(dbPayload.found_in_db);",
  '',
  'let isHoliday = !!baseline.DefaultIsHoliday;',
  "let holidayName = baseline.DefaultHolidayName || (isHoliday ? '\\uC8FC\\uB9D0' : '\\uD3C9\\uC77C');",
  "let holidayLookupSource = isHoliday ? 'default-weekend' : 'default-weekday';",
  '',
  'if (dbFound) {',
  '  isHoliday = true;',
  "  holidayName = String(dbPayload.holiday_name || '\\uACF5\\uD734\\uC77C');",
  "  holidayLookupSource = dbPayload.source_type ? `db:${dbPayload.source_type}` : 'db';",
  '}',
  '',
  'return [{',
  '  json: {',
  '    check_date: baseline.todayInt,',
  '    today_date: baseline.todayDate,',
  '    is_holiday: isHoliday,',
  '    holiday_name: holidayName,',
  '    is_weekend: !!baseline.IsWeekend,',
  '    weekday_name: baseline.WeekdayName,',
  '    holiday_lookup_source: holidayLookupSource,',
  "    db_error: dbPayload.error || '',",
  '  }',
  '}];',
].join('\n');

const buildTeamsPayloadCode = [
  "const holiday = $('Determine Holiday').first()?.json ?? {};",
  "const vacationItems = $('Vacation Calendar').all();",
  "const notionItems = $('In Review Pages').all();",
  '',
  'const targetUser = {',
  "  name: '\\uAE40\\uC9C4\\uC6B1',",
  "  email: 'jwkim@vms-solutions.com',",
  '};',
  '',
  'function normalize(value) { return String(value ?? "").normalize("NFC").replace(/\\s+/g, "").toLowerCase(); }',
  'function contains(value, keyword) { return normalize(value).includes(normalize(keyword)); }',
  'function compactText(value, max = 300) { const text = String(value ?? "").replace(/\\s+/g, " ").trim(); return text.length > max ? text.slice(0, max - 3) + "..." : text; }',
  '',
  'function collectStrings(value, out = [], depth = 0) {',
  '  if (depth > 10 || value == null) return out;',
  '  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") { out.push(String(value)); return out; }',
  '  if (Array.isArray(value)) { for (const item of value) collectStrings(item, out, depth + 1); return out; }',
  '  if (typeof value === "object") { for (const nested of Object.values(value)) collectStrings(nested, out, depth + 1); }',
  '  return out;',
  '}',
  '',
  'function ymds(text) { return String(text ?? "").match(/\\d{4}-\\d{2}-\\d{2}/g) || []; }',
  'function ymd(text) { const match = String(text ?? "").match(/\\d{4}-\\d{2}-\\d{2}/); return match ? match[0] : ""; }',
  '',
  'function ranges(item) {',
  '  const found = [];',
  '  const uniq = new Set();',
  '  function push(label, start, end) {',
  '    const s = ymd(start);',
  '    const e = ymd(end || start);',
  '    if (!s) return;',
  '    const key = label + "|" + s + "|" + e;',
  '    if (uniq.has(key)) return;',
  '    uniq.add(key);',
  '    found.push({ start: s, end: e || s });',
  '  }',
  '  function walk(value, label, depth) {',
  '    if (depth > 8 || value == null) return;',
  '    if (typeof value === "string") {',
  '      const items = ymds(value);',
  '      if (items.length === 1) push(label, items[0], items[0]);',
  '      if (items.length >= 2) push(label, items[0], items[1]);',
  '      return;',
  '    }',
  '    if (typeof value === "number" || typeof value === "boolean") return;',
  '    if (Array.isArray(value)) { value.forEach((item, idx) => walk(item, label + "[" + idx + "]", depth + 1)); return; }',
  '    if (typeof value === "object") {',
  '      if ("start" in value && ymd(value.start)) push(label + ".start", value.start, value.end || value.start);',
  '      if ("date" in value && value.date && typeof value.date === "object" && ymd(value.date.start)) push(label + ".date", value.date.start, value.date.end || value.date.start);',
  '      if ("property_date" in value && value.property_date && typeof value.property_date === "object" && ymd(value.property_date.start)) push(label + ".property_date", value.property_date.start, value.property_date.end || value.property_date.start);',
  '      if ("formula" in value && value.formula && typeof value.formula === "object" && value.formula.type === "date" && value.formula.date && ymd(value.formula.date.start)) push(label + ".formula.date", value.formula.date.start, value.formula.date.end || value.formula.date.start);',
  '      for (const [key, nested] of Object.entries(value)) walk(nested, label + "." + key, depth + 1);',
  '    }',
  '  }',
  '  walk(item?.json ?? item, "root", 0);',
  '  return found;',
  '}',
  '',
  'function isAwayText(text) {',
  "  return ['\\uD734\\uAC00','\\uC5F0\\uCC28','\\uBC18\\uCC28','\\uC624\\uC804\\uBC18\\uCC28','\\uC624\\uD6C4\\uBC18\\uCC28','\\uC548\\uC2DD\\uC6D4','\\uACF5\\uAC00','\\uACF5\\uD734\\uC77C','\\uD734\\uC77C','\\uCD9C\\uC7A5','vacation','leave','pto','dayoff','off','businesstrip'].some((keyword) => contains(text, keyword));",
  '}',
  '',
  'function getStatus(page) {',
  '  const props = page?.properties || {};',
  '  for (const [key, value] of Object.entries(props)) {',
  '    if ((contains(key, "status") || contains(key, "\\uC0C1\\uD0DC")) && value?.type === "status") return String(value.status?.name || "");',
  '    if ((contains(key, "status") || contains(key, "\\uC0C1\\uD0DC")) && value?.type === "select") return String(value.select?.name || "");',
  '  }',
  '  for (const [key, value] of Object.entries(page || {})) {',
  '    if (contains(key, "property_status") || contains(key, "status")) {',
  '      if (typeof value === "string") return String(value);',
  '      if (value && typeof value === "object" && typeof value.name === "string") return String(value.name);',
  '    }',
  '  }',
  '  return "";',
  '}',
  '',
  'function getTitle(page) {',
  '  const props = page?.properties || {};',
  '  for (const value of Object.values(props)) {',
  '    if (value?.type === "title") {',
  '      return (value.title || []).map((item) => item?.plain_text || item?.text?.content || "").join("").trim();',
  '    }',
  '  }',
  '  if (typeof page?.name === "string" && page.name.trim()) return page.name.trim();',
  '  if (typeof page?.property_task === "string" && page.property_task.trim()) return page.property_task.trim();',
  '  return String(page?.url || page?.id || "").trim();',
  '}',
  '',
  "const today = String(holiday.today_date || new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Seoul' }).format(new Date()));",
  'const vacationLookupFailed = vacationItems.some((item) => item?.json?.error);',
  'const notionLookupFailed = notionItems.some((item) => item?.json?.error);',
  'const errorMessages = [',
  '  holiday.db_error ? "\\uACF5\\uD734\\uC77C DB \\uC870\\uD68C \\uC2E4\\uD328: " + compactText(holiday.db_error) : "",',
  '  ...vacationItems.map((item) => item?.json?.error ? "\\uD734\\uAC00 DB \\uC870\\uD68C \\uC2E4\\uD328: " + compactText(item.json.error?.message || item.json.error?.description || item.json.error) : "").filter(Boolean),',
  '  ...notionItems.map((item) => item?.json?.error ? "Notion DB \\uC870\\uD68C \\uC2E4\\uD328: " + compactText(item.json.error?.message || item.json.error?.description || item.json.error) : "").filter(Boolean),',
  '].filter(Boolean);',
  'const hasError = errorMessages.length > 0;',
  'const todayAwayItems = vacationLookupFailed ? [] : vacationItems.filter((item) => {',
  '  const text = collectStrings(item?.json ?? item).join(" ");',
  '  if (!isAwayText(text)) return false;',
  '  const itemRanges = ranges(item);',
  '  return itemRanges.length > 0 && itemRanges.some((range) => range.start <= today && today <= range.end);',
  '});',
  'const targetAway = todayAwayItems.some((item) => {',
  '  const text = collectStrings(item?.json ?? item).join(" ");',
  '  return contains(text, targetUser.name) || contains(text, targetUser.email);',
  '});',
  '',
  'const pages = notionItems.map((item) => item?.json ?? {}).filter((page) => page && typeof page === "object" && !page.error);',
  'const uniquePages = [];',
  'const seenPageIds = new Set();',
  'for (const page of pages) {',
  '  const key = String(page?.id || page?.url || getTitle(page) || "").trim();',
  '  if (!key || seenPageIds.has(key)) continue;',
  '  seenPageIds.add(key);',
  '  uniquePages.push(page);',
  '}',
  'const inReviewPages = uniquePages.filter((page) => getStatus(page) === "In Review");',
  'const shouldSendReview = !hasError && !holiday.is_holiday && !targetAway && inReviewPages.length > 0;',
  'const shouldSendError = hasError;',
  'const shouldSend = shouldSendError || shouldSendReview;',
  '',
  'const teamsEntities = shouldSend',
  '  ? [{ type: "mention", text: "<at>" + targetUser.name + "</at>", mentioned: { id: targetUser.email, name: targetUser.name } }]',
  '  : [];',
  '',
  'const reviewTitleText = "<at>" + targetUser.name + "</at> \\uB2D8, In Review \\uC0C1\\uD0DC \\uD56D\\uBAA9\\uC774 \\uC788\\uC2B5\\uB2C8\\uB2E4.";',
  'const errorTitleText = "<at>" + targetUser.name + "</at> \\uB2D8, Notion-In-Review-Inform \\uC2E4\\uD589 \\uC624\\uB958\\uAC00 \\uBC1C\\uC0DD\\uD588\\uC2B5\\uB2C8\\uB2E4.";',
  "const checkedAt = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Seoul', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }).formatToParts(new Date());",
  "const pick = (type) => checkedAt.find((part) => part.type === type)?.value || '';",
  "const checkedAtText = pick('year') + '-' + pick('month') + '-' + pick('day') + ' ' + pick('hour') + ':' + pick('minute') + ':' + pick('second') + ' KST';",
  '',
  'const body = shouldSendError ? [',
  '  { type: "TextBlock", text: errorTitleText, weight: "Bolder", size: "Medium", wrap: true },',
  '  { type: "FactSet", facts: [',
  "    { title: '\\uD655\\uC778 \\uC2DC\\uAC01', value: checkedAtText },",
  '  ] },',
  '  ...errorMessages.map((message) => ({ type: "TextBlock", text: "- " + message, wrap: true, spacing: "Small", color: "Attention" })),',
  '] : (shouldSendReview ? [',
  '  { type: "TextBlock", text: reviewTitleText, weight: "Bolder", size: "Medium", wrap: true },',
  '  { type: "FactSet", facts: [',
  "    { title: '\\uAC74\\uC218', value: String(inReviewPages.length) + '\\uAC74' },",
  "    { title: '\\uD655\\uC778 \\uC2DC\\uAC01', value: checkedAtText },",
  '  ] },',
  '  ...inReviewPages.map((page) => ({',
  '    type: "TextBlock",',
  '    text: "- [" + getTitle(page) + "](" + String(page.url || TARGET_DATABASE_URL) + ")",',
  '    wrap: true,',
  '    spacing: "Small",',
  '  })),',
  '] : []);',
  '',
  'return [{',
  '  json: {',
  '    alertCount: shouldSend ? (shouldSendError ? 1 : inReviewPages.length) : 0,',
  '    alertMode: shouldSendError ? "error" : (shouldSendReview ? "review" : "none"),',
  '    teamsEntities,',
  '    alertCardBody: body,',
  '    debug: {',
      '      targetAway,',
      '      vacationLookupFailed,',
  '      notionLookupFailed,',
  '      inReviewCount: inReviewPages.length,',
  '      isHoliday: !!holiday.is_holiday,',
  '      hasError,',
    '    }',
  '  }',
  '}];',
].join('\n');

const workflow = {
  name: workflowName,
  nodes: [
    {
      parameters: {
        rule: {
          interval: [{ field: 'cronExpression', expression: '0 0 7-16 * * 1-5' }],
        },
      },
      type: 'n8n-nodes-base.scheduleTrigger',
      typeVersion: 1.3,
      position: [-960, -32],
      id: uuid('schedule'),
      name: 'Review Schedule',
      alwaysOutputData: true,
    },
    {
      parameters: { jsCode: weekdayBaselineCode },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [-720, -32],
      id: uuid('weekday-baseline'),
      name: 'Weekday Baseline',
      alwaysOutputData: true,
    },
    {
      parameters: {
        operation: 'executeQuery',
        query:
          "=DECLARE @d DATE = CAST('{{ $('Weekday Baseline').item.json.todayDate }}' AS date);\nSELECT\n    CONVERT(VARCHAR(8), @d, 112) AS check_date,\n    CAST(CASE WHEN EXISTS (\n        SELECT 1\n        FROM TsMgmt.dbo.HolidayCalendarKR\n        WHERE HolidayDate = @d\n    ) THEN 1 ELSE 0 END AS bit) AS found_in_db,\n    ISNULL((SELECT TOP 1 HolidayName FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), '') AS holiday_name,\n    ISNULL((SELECT TOP 1 SourceType FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), '') AS source_type,\n    ISNULL((SELECT TOP 1 SourceYear FROM TsMgmt.dbo.HolidayCalendarKR WHERE HolidayDate = @d), 0) AS source_year;",
      },
      type: 'n8n-nodes-base.microsoftSql',
      typeVersion: 1.1,
      position: [-480, -32],
      id: uuid('holiday-db'),
      name: 'Holiday DB Fallback',
      alwaysOutputData: true,
      onError: 'continueRegularOutput',
      credentials: {
        microsoftSql: {
          id: '2dZb5OQPbTyO3052',
          name: 'TsMgmt(DevTest_SQL2022_26)',
        },
      },
    },
    {
      parameters: { jsCode: determineHolidayCode },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [-240, -32],
      id: uuid('determine-holiday'),
      name: 'Determine Holiday',
      alwaysOutputData: true,
    },
    {
      parameters: {
        conditions: {
          options: {
            caseSensitive: true,
            leftValue: '',
            typeValidation: 'strict',
            version: 2,
          },
          conditions: [
            {
              id: uuid('if-not-holiday-condition'),
              leftValue: '={{ $json.is_holiday }}',
              rightValue: false,
              operator: {
                type: 'boolean',
                operation: 'equals',
              },
            },
          ],
          combinator: 'and',
        },
        options: {},
      },
      type: 'n8n-nodes-base.if',
      typeVersion: 2.2,
      position: [0, -32],
      id: uuid('if-not-holiday'),
      name: 'Not Holiday',
      alwaysOutputData: false,
    },
    {
      parameters: {
        resource: 'databasePage',
        operation: 'getAll',
        databaseId: {
          __rl: true,
          value: VACATION_DATABASE_ID,
          mode: 'list',
          cachedResultName: 'TS Calendar DB',
          cachedResultUrl: 'https://www.notion.so/205cb995830980e4ac2ac8589a1783eb',
        },
        options: {
          sort: {
            sortValue: [{ key: 'Date|date', direction: 'descending' }],
          },
        },
      },
      type: 'n8n-nodes-base.notion',
      typeVersion: 2.2,
      position: [240, -112],
      id: uuid('vacation-calendar'),
      name: 'Vacation Calendar',
      onError: 'continueRegularOutput',
      credentials: {
        notionApi: NOTION_CREDENTIAL,
      },
    },
    {
      parameters: {
        resource: 'databasePage',
        operation: 'getAll',
        databaseId: {
          __rl: true,
          value: TARGET_DATABASE_ID,
          mode: 'list',
          cachedResultName: 'In Review Target DB',
          cachedResultUrl: TARGET_DATABASE_URL,
        },
        options: {
          sort: {
            sortValue: [{ key: 'Status|status', direction: 'ascending' }],
          },
        },
      },
      type: 'n8n-nodes-base.notion',
      typeVersion: 2.2,
      position: [480, -112],
      id: uuid('in-review-pages'),
      name: 'In Review Pages',
      onError: 'continueRegularOutput',
      credentials: {
        notionApi: NOTION_CREDENTIAL,
      },
    },
    {
      parameters: { jsCode: buildTeamsPayloadCode },
      type: 'n8n-nodes-base.code',
      typeVersion: 2,
      position: [720, -112],
      id: uuid('build-teams-payload'),
      name: 'Build Teams Payload',
      alwaysOutputData: true,
    },
    {
      parameters: {
        conditions: {
          options: {
            caseSensitive: true,
            leftValue: '',
            typeValidation: 'strict',
            version: 2,
          },
          conditions: [
            {
              id: uuid('if-send-alert-condition'),
              leftValue: '={{ $json.alertCount > 0 }}',
              rightValue: true,
              operator: {
                type: 'boolean',
                operation: 'equals',
              },
            },
          ],
          combinator: 'and',
        },
        options: {},
      },
      type: 'n8n-nodes-base.if',
      typeVersion: 2.2,
      position: [960, -112],
      id: uuid('if-send-alert'),
      name: 'Should Send Alert',
    },
    {
      parameters: {
        method: 'POST',
        url: TEAMS_WEBHOOK,
        sendBody: true,
        contentType: 'json',
        specifyBody: 'json',
        bodyParameters: { parameters: [{}] },
        jsonBody:
          "={{ ({ type: 'message', attachments: [{ contentType: 'application/vnd.microsoft.card.adaptive', content: { type: 'AdaptiveCard', body: Array.isArray($json.alertCardBody) ? $json.alertCardBody : [], msteams: { entities: Array.isArray($json.teamsEntities) ? $json.teamsEntities : [] }, '$schema': 'http://adaptivecards.io/schemas/adaptive-card.json', version: '1.4' } }] }) }}",
        options: {},
      },
      type: 'n8n-nodes-base.httpRequest',
      typeVersion: 4.3,
      position: [1200, -112],
      id: uuid('teams-webhook'),
      name: 'Alert Teams Webhook',
      alwaysOutputData: false,
    },
  ],
  connections: {
    'Review Schedule': {
      main: [[{ node: 'Weekday Baseline', type: 'main', index: 0 }]],
    },
    'Weekday Baseline': {
      main: [[{ node: 'Holiday DB Fallback', type: 'main', index: 0 }]],
    },
    'Holiday DB Fallback': {
      main: [[{ node: 'Determine Holiday', type: 'main', index: 0 }]],
    },
    'Determine Holiday': {
      main: [[{ node: 'Not Holiday', type: 'main', index: 0 }]],
    },
    'Not Holiday': {
      main: [[{ node: 'Vacation Calendar', type: 'main', index: 0 }], []],
    },
    'Vacation Calendar': {
      main: [[{ node: 'In Review Pages', type: 'main', index: 0 }]],
    },
    'In Review Pages': {
      main: [[{ node: 'Build Teams Payload', type: 'main', index: 0 }]],
    },
    'Build Teams Payload': {
      main: [[{ node: 'Should Send Alert', type: 'main', index: 0 }]],
    },
    'Should Send Alert': {
      main: [[{ node: 'Alert Teams Webhook', type: 'main', index: 0 }], []],
    },
  },
  settings: {
    executionOrder: 'v1',
  },
};

fs.mkdirSync(workflowDir, { recursive: true });
fs.writeFileSync(workflowPath, JSON.stringify(workflow, null, 2) + '\n', 'utf8');
console.log(workflowPath);
