const fs = require('fs');
const path = require('path');

const workflowPath = path.join(
  __dirname,
  '..',
  'workflows',
  'Plan-Daily-Scrum',
  'Plan-Daily-Scrum_api.json'
);

const workflow = JSON.parse(fs.readFileSync(workflowPath, 'utf8'));

function getNode(id) {
  const node = workflow.nodes.find((item) => item.id === id);
  if (!node) {
    throw new Error(`Node not found: ${id}`);
  }
  return node;
}

const teamCode = [
  "const items = $input.all();",
  "",
  "const allUsers = [",
  "  { name: \"\\uC870\\uD604\\uC7AC\", slackId: \"U07K2APTEVD\", email: \"jyi30@vms-solutions.com\" },",
  "  { name: \"\\uAE40\\uBBFC\\uC601\", slackId: \"U07EEDTJZQE\", email: \"mykim@vms-solutions.com\" }",
  "];",
  "",
  "const adminUser = {",
  "  name: \"\\uAE40\\uC9C4\\uC6B1\",",
  "  slackId: \"U05DQA2L7JT\",",
  "  email: \"jwkim@vms-solutions.com\"",
  "};",
  "",
  "const today = new Date().toISOString().split('T')[0];",
  "const dateString = new Date().toLocaleDateString('ko-KR', { year: 'numeric', month: 'long', day: 'numeric' });",
  "const workLink = \"https://www.notion.so/vmssolutions/Sprint-2decb995830980e7910cd3495f371466\";",
  "",
  "const absentSlackIds = [];",
  "const absentNamesList = [];",
  "",
  "for (const item of items) {",
  "  const data = item.json;",
  "  const itemName = data.name || '';",
  "  const startDate = data.property_date?.start;",
  "  const endDate = data.property_date?.end || startDate;",
  "",
  "  const keywords = [",
  "    \"\\uD734\\uAC00\",",
  "    \"\\uC5F0\\uCC28\",",
  "    \"\\uC548\\uC2DD\\uC6D4\",",
  "    \"\\uACF5\\uAC00\",",
  "    \"\\uACF5\\uD734\\uC77C\",",
  "    \"\\uD734\\uC77C\"",
  "  ];",
  "  const hasKeyword = keywords.some((kw) => itemName.includes(kw));",
  "",
  "  if (hasKeyword && startDate && today >= startDate && today <= endDate) {",
  "    for (const user of allUsers) {",
  "      if (itemName.includes(user.name) && !absentSlackIds.includes(user.slackId)) {",
  "        absentSlackIds.push(user.slackId);",
  "        absentNamesList.push(user.name);",
  "      }",
  "    }",
  "  }",
  "}",
  "",
  "const activeUsers = allUsers.filter((user) => !absentSlackIds.includes(user.slackId));",
  "const notifyAdminOnly = activeUsers.length === 0;",
  "const targetUsers = notifyAdminOnly ? [adminUser] : activeUsers;",
  "const absentNamesText = absentNamesList.length > 0 ? absentNamesList.join(', ') : '\\uC5C6\\uC74C';",
  "",
  "const slackMentions = targetUsers.map((user) => `<@${user.slackId}>`).join(', ');",
  "const teamsText = targetUsers.map((user) => `<at>${user.name}</at>`).join(', ');",
  "const teamsEntities = targetUsers.map((user) => ({",
  "  type: 'mention',",
  "  text: `<at>${user.name}</at>`,",
  "  mentioned: { id: user.email, name: user.name }",
  "}));",
  "",
  "const slackMessage = notifyAdminOnly",
  "  ? `\\uD83D\\uDCE2 ${slackMentions} \\uB2D8!\\n\\n[${dateString}] \\uAE30\\uC900 \\uC804\\uC6D0\\uC774 \\uD734\\uAC00 \\uB4F1\\uC73C\\uB85C \\uBD84\\uB958\\uB418\\uC5B4 \\uB370\\uC77C\\uB9AC \\uC2A4\\uD06C\\uB7FC \\uC54C\\uB9BC \\uB300\\uC0C1\\uC790\\uAC00 \\uC5C6\\uC2B5\\uB2C8\\uB2E4.\\n\\n\\uBD80\\uC7AC \\uC778\\uC6D0: ${absentNamesText}\\n\\uD655\\uC778 \\uBD80\\uD0C1\\uB4DC\\uB9BD\\uB2C8\\uB2E4.`",
  "  : `\\uD83D\\uDCE2 ${slackMentions} \\uB2D8! \\uB370\\uC77C\\uB9AC \\uC2A4\\uD06C\\uB7FC \\uC791\\uC131 \\uC2DC\\uAC04\\uC785\\uB2C8\\uB2E4.\\n\\n[${dateString}] - \\uAE30\\uC220\\uC9C0\\uC6D0 \\uB370\\uC77C\\uB9AC \\uC2A4\\uD06C\\uB7FC\\n\\n*\\uC624\\uB298 \\uD560 \\uC5C5\\uBB34*\\n1. <${workLink}|\\uC624\\uB298 \\uD560 \\uC5C5\\uBB34 \\uD655\\uC778\\uD558\\uAE30>\\n\\n*\\uC624\\uB298 \\uBD80\\uC7AC(\\uD734\\uAC00 \\uB4F1) \\uC778\\uC6D0:* ${absentNamesList.length > 0 ? `\\uC788\\uC74C (${absentNamesText})` : '\\uC5C6\\uC74C'}\\n\\n\\uC624\\uB298 \\uD558\\uB8E8\\uB3C4 \\uD798\\uB0C5\\uC2DC\\uB2E4! \\uD83D\\uDD25`;",
  "",
  "const titleText = notifyAdminOnly",
  "  ? `\\uD83D\\uDCE2 ${teamsText} \\uB2D8! \\uC624\\uB298 \\uB370\\uC77C\\uB9AC \\uC2A4\\uD06C\\uB7FC \\uC54C\\uB9BC \\uB300\\uC0C1\\uC790\\uAC00 \\uC5C6\\uC2B5\\uB2C8\\uB2E4.`",
  "  : `\\uD83D\\uDCE2 ${teamsText} \\uB2D8! \\uB370\\uC77C\\uB9AC \\uC2A4\\uD06C\\uB7FC \\uC791\\uC131 \\uC2DC\\uAC04\\uC785\\uB2C8\\uB2E4.`;",
  "",
  "const subtitleText = notifyAdminOnly",
  "  ? `**[${dateString}]** \\uAE30\\uC900 \\uC804\\uC6D0\\uC774 \\uD734\\uAC00 \\uB4F1\\uC73C\\uB85C \\uBD84\\uB958\\uB418\\uC5C8\\uC2B5\\uB2C8\\uB2E4.`",
  "  : `[${dateString}] - \\uAE30\\uC220\\uC9C0\\uC6D0 \\uB370\\uC77C\\uB9AC \\uC2A4\\uD06C\\uB7FC`;",
  "",
  "const bodyText = notifyAdminOnly",
  "  ? '\\uBD80\\uC7AC \\uC778\\uC6D0\\uC744 \\uD655\\uC778\\uD574 \\uC8FC\\uC138\\uC694.'",
  "  : '**\\uC624\\uB298 \\uD560 \\uC5C5\\uBB34**\\n\\n1. [\\uC624\\uB298 \\uD560 \\uC5C5\\uBB34 \\uD655\\uC778\\uD558\\uAE30](https://www.notion.so/vmssolutions/Sprint-2decb995830980e7910cd3495f371466)';",
  "",
  "const absenceText = `*\\uC624\\uB298 \\uBD80\\uC7AC(\\uD734\\uAC00 \\uB4F1) \\uC778\\uC6D0:* ${absentNamesList.length > 0 ? `\\uC788\\uC74C (${absentNamesText})` : '\\uC5C6\\uC74C'}`;",
  "",
  "const footerText = notifyAdminOnly",
  "  ? '\\uAD00\\uB9AC\\uC790 \\uD655\\uC778 \\uBD80\\uD0C1\\uB4DC\\uB9BD\\uB2C8\\uB2E4.'",
  "  : '\\uC624\\uB298 \\uD558\\uB8E8\\uB3C4 \\uD798\\uB0C5\\uC2DC\\uB2E4! \\uD83D\\uDD25';",
  "",
  "return [{",
  "  json: {",
  "    text: slackMessage,",
  "    teamsText,",
  "    teamsEntities,",
  "    absentNames: absentNamesText,",
  "    absent_count: absentSlackIds.length,",
  "    date: dateString,",
  "    notify_admin_only: notifyAdminOnly,",
  "    titleText,",
  "    subtitleText,",
  "    bodyText,",
  "    absenceText,",
  "    footerText",
  "  }",
  "}];"
].join('\n');

const legacySlackCode = [
  "const items = $input.all();",
  "",
  "const allUsers = [",
  "  { name: \"\\uC870\\uD604\\uC7AC\", slackId: \"U07K2APTEVD\" },",
  "  { name: \"\\uAE40\\uBBFC\\uC601\", slackId: \"U07EEDTJZQE\" }",
  "];",
  "",
  "const adminUser = { name: \"\\uAE40\\uC9C4\\uC6B1\", slackId: \"U05DQA2L7JT\" };",
  "",
  "const today = new Date().toISOString().split('T')[0];",
  "const absentSlackIds = [];",
  "const absentNamesList = [];",
  "",
  "for (const item of items) {",
  "  const data = item.json;",
  "  const itemName = data.name || '';",
  "  const startDate = data.property_date?.start;",
  "  const endDate = data.property_date?.end || startDate;",
  "  const keywords = [\"\\uD734\\uAC00\", \"\\uC5F0\\uCC28\", \"\\uC548\\uC2DD\\uC6D4\", \"\\uACF5\\uAC00\"];",
  "  const hasKeyword = keywords.some((kw) => itemName.includes(kw));",
  "",
  "  if (hasKeyword && startDate && today >= startDate && today <= endDate) {",
  "    for (const user of allUsers) {",
  "      if (itemName.includes(user.name) && !absentSlackIds.includes(user.slackId)) {",
  "        absentSlackIds.push(user.slackId);",
  "        absentNamesList.push(user.name);",
  "      }",
  "    }",
  "  }",
  "}",
  "",
  "const activeUsers = allUsers.filter((user) => !absentSlackIds.includes(user.slackId));",
  "const notifyAdminOnly = activeUsers.length === 0;",
  "const targetUsers = notifyAdminOnly ? [adminUser] : activeUsers;",
  "const mentions = targetUsers.map((user) => `<@${user.slackId}>`).join(', ');",
  "const absentNamesText = absentNamesList.length > 0 ? absentNamesList.join(', ') : '\\uC5C6\\uC74C';",
  "",
  "const dateString = new Date().toLocaleDateString('ko-KR', { year: 'numeric', month: 'long', day: 'numeric' });",
  "const workLink = \"https://www.notion.so/vmssolutions/Sprint-2decb995830980e7910cd3495f371466\";",
  "",
  "const message = notifyAdminOnly",
  "  ? `\\uD83D\\uDCE2 ${mentions} \\uB2D8! \\uB370\\uC77C\\uB9AC \\uC2A4\\uD06C\\uB7FC \\uC54C\\uB9BC \\uB300\\uC0C1\\uC790\\uAC00 \\uC5C6\\uC2B5\\uB2C8\\uB2E4.\\n\\n[${dateString}] \\uAE30\\uC900 \\uC804\\uC6D0\\uC774 \\uD734\\uAC00 \\uB4F1\\uC73C\\uB85C \\uBD84\\uB958\\uB418\\uC5C8\\uC2B5\\uB2C8\\uB2E4.\\n\\uBD80\\uC7AC \\uC778\\uC6D0: ${absentNamesText}`",
  "  : `\\uD83D\\uDCE2 ${mentions} \\uB2D8! \\uB370\\uC77C\\uB9AC \\uC2A4\\uD06C\\uB7FC \\uC791\\uC131 \\uC2DC\\uAC04\\uC785\\uB2C8\\uB2E4.\\n\\n[${dateString}] - \\uAE30\\uC220\\uC9C0\\uC6D0 \\uB370\\uC77C\\uB9AC \\uC2A4\\uD06C\\uB7FC\\n\\n*\\uC624\\uB298 \\uD560 \\uC5C5\\uBB34*\\n1. <${workLink}|\\uC624\\uB298 \\uD560 \\uC5C5\\uBB34 \\uD655\\uC778\\uD558\\uAE30>\\n\\n*\\uC624\\uB298 \\uBD80\\uC7AC(\\uD734\\uAC00 \\uB4F1) \\uC778\\uC6D0:* ${absentSlackIds.length > 0 ? '\\uC788\\uC74C' : '\\uC5C6\\uC74C'}\\n\\uC624\\uB298 \\uD558\\uB8E8\\uB3C4 \\uD798\\uB0C5\\uC2DC\\uB2E4! \\uD83D\\uDD25`;",
  "",
  "return [{",
  "  json: {",
  "    text: message,",
  "    date: today,",
  "    absent_count: absentSlackIds.length,",
  "    absentNames: absentNamesText,",
  "    notify_admin_only: notifyAdminOnly",
  "  }",
  "}];"
].join('\n');

const teamsBody = [
  "={{ ({",
  "  type: 'message',",
  "  attachments: [",
  "    {",
  "      contentType: 'application/vnd.microsoft.card.adaptive',",
  "      content: {",
  "        type: 'AdaptiveCard',",
  "        body: [",
  "          {",
  "            type: 'TextBlock',",
  "            text: $json.titleText,",
  "            weight: 'Bolder',",
  "            size: 'Medium',",
  "            wrap: true,",
  "          },",
  "          {",
  "            type: 'TextBlock',",
  "            text: $json.subtitleText,",
  "            isSubtle: !$json.notify_admin_only,",
  "            wrap: true,",
  "            spacing: 'None',",
  "          },",
  "          {",
  "            type: 'TextBlock',",
  "            text: $json.bodyText,",
  "            wrap: true,",
  "            spacing: 'Medium',",
  "          },",
  "          {",
  "            type: 'TextBlock',",
  "            text: $json.absenceText,",
  "            wrap: true,",
  "            color: $json.absent_count > 0 ? 'Attention' : 'Default',",
  "            spacing: 'Small',",
  "          },",
  "          {",
  "            type: 'TextBlock',",
  "            text: $json.footerText,",
  "            wrap: true,",
  "            spacing: 'Small',",
  "          },",
  "        ],",
  "        msteams: {",
  "          entities: Array.isArray($json.teamsEntities) ? $json.teamsEntities : [],",
  "        },",
  "        '$schema': 'http://adaptivecards.io/schemas/adaptive-card.json',",
  "        version: '1.0',",
  "      },",
  "    },",
  "  ],",
  "}) }}"
].join('\n');

getNode('c139a218-6874-45ec-8535-9b2bb147306c').parameters.jsCode = teamCode;
getNode('ce1674fa-2cb0-4701-bc42-fa5e63017bbe').parameters.jsCode = legacySlackCode;

const teamsNode = getNode('f764b17c-9127-43aa-a3fb-215e98ef54e5');
teamsNode.parameters.contentType = 'json';
teamsNode.parameters.specifyBody = 'json';
teamsNode.parameters.bodyParameters = { parameters: [{}] };
teamsNode.parameters.jsonBody = teamsBody;

fs.writeFileSync(workflowPath, JSON.stringify(workflow, null, 4));
console.log('Updated ' + workflowPath);
